/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Domestique HTTP API
 * The complete HTTP contract served by Domestique. JSON property names are
 * camelCase. All routes except `GET /healthz` require the signed Cloudflare
 * Access assertion; state-changing routes also require the same-origin
 * `Origin` header.
 *
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type { ErrorType } from "./request";
import { domestiqueRequest } from "./request";
export interface Build {
  revision: string;
  imageDigest?: string;
}

export type TargetStatusConvergence =
  (typeof TargetStatusConvergence)[keyof typeof TargetStatusConvergence];

export const TargetStatusConvergence = {
  current: "current",
  lagging: "lagging",
  failed: "failed",
  unauthorized: "unauthorized",
} as const;

export interface TargetStages {
  /** @minimum 0 */
  current: number;
  /** @minimum 0 */
  pending: number;
}

export interface TargetRun {
  completedAt: string;
  result: string;
  failure?: string;
}

export interface TargetStatus {
  id: string;
  authorisation: string;
  convergence: TargetStatusConvergence;
  stages: TargetStages;
  lastRun?: TargetRun;
}

export type SyncActivePhase = (typeof SyncActivePhase)[keyof typeof SyncActivePhase];

export const SyncActivePhase = {
  source: "source",
  targets: "targets",
} as const;

export interface SyncActive {
  phase?: SyncActivePhase;
  startsAt?: string;
  /** @minimum 0 */
  targets: number;
  stages: TargetStages;
}

export interface SyncSchedule {
  source: boolean;
  targets: boolean;
}

export interface SyncPhaseRun {
  lastCompletedAt: string;
  lastResult: string;
  lastFailure?: string;
  sourceStages: number;
  created: number;
  updated: number;
  deleted: number;
}

export interface SyncPhases {
  source?: SyncPhaseRun;
  targets?: SyncPhaseRun;
}

export interface SurfaceCoverage {
  generation?: string;
  builtAt?: string;
  classified: number;
  total: number;
  incomplete: number;
}

export interface WahooRateLimit {
  remaining: number;
  resetsAt?: string;
}

export interface TrustedInventory {
  lastSuccessAt?: string;
  ageSeconds: number;
  maxAgeSeconds: number;
  fresh: boolean;
}

export interface SyncStatus {
  state: string;
  active?: SyncActive;
  lastResult?: string;
  lastCompletedAt?: string;
  sourceStages: number;
  created: number;
  updated: number;
  deleted: number;
  schedule: SyncSchedule;
  phases: SyncPhases;
  surface: SurfaceCoverage;
  wahooRateLimit?: WahooRateLimit;
  trustedInventory?: TrustedInventory;
}

export interface Status {
  ready: boolean;
  converged: boolean;
  build?: Build;
  targets: TargetStatus[];
  sync: SyncStatus;
}

export type SyncRunPhase = (typeof SyncRunPhase)[keyof typeof SyncRunPhase];

export const SyncRunPhase = {
  source: "source",
  targets: "targets",
} as const;

export interface SyncRun {
  reference: string;
  phase: SyncRunPhase;
  completedAt: string;
  result: string;
  failure?: string;
  sourceStages: number;
  created: number;
  updated: number;
  deleted: number;
}

export interface SyncRunPage {
  runs: SyncRun[];
  next?: string;
}

export interface RouteValidation {
  biasPercent: number;
  maePercent: number;
  p90Percent: number;
  /** @minimum 0 */
  evaluatedRides: number;
}

export interface Route {
  provider: string;
  routeId: number;
  stageOrder: number;
  title: string;
  routeName: string;
  stageName: string;
  sourceRevision: string;
  contentHash: string;
  distanceMetres: number;
  ascentMetres: number;
  maxGradientPercent: number;
  pointCount: number;
  movingSeconds?: number;
  validation?: RouteValidation;
}

export interface RouteList {
  stages: Route[];
}

export interface GeoJSONLineString {
  type: "LineString";
  /**
   * @minItems 2
   * @items.minItems 2
   * @items.maxItems 3
   */
  coordinates: number[][];
}

export type SurfaceRangeKind = (typeof SurfaceRangeKind)[keyof typeof SurfaceRangeKind];

export const SurfaceRangeKind = {
  asphalt: "asphalt",
  paving: "paving",
  compacted: "compacted",
  gravel: "gravel",
  ground: "ground",
  unknown: "unknown",
} as const;

export interface SurfaceRange {
  kind: SurfaceRangeKind;
  /** @minimum 0 */
  startIndex: number;
  /** @minimum 0 */
  endIndex: number;
}

export type GeoJSONPropertiesSurface = {
  ranges: SurfaceRange[];
  matchedMetres: number;
};

export interface GeoJSONProperties {
  provider: string;
  routeId: number;
  stageOrder: number;
  title: string;
  routeName: string;
  stageName: string;
  distanceMetres: number;
  ascentMetres: number;
  maxGradientPercent: number;
  pointCount: number;
  surface?: GeoJSONPropertiesSurface;
  cumulativeSeconds?: number[];
}

export interface GeoJSONFeature {
  type: "Feature";
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: number[];
  geometry: GeoJSONLineString;
  properties: GeoJSONProperties;
}

export interface BrowserBasemap {
  /** @minLength 1 */
  name: string;
  styleUrl: string;
  styleUrlDark?: string;
  darkCartography?: boolean;
}

export interface SourceBaseUrls {
  veloplanner?: string;
  komoot?: string;
}

export interface WebUIConfig {
  /** @minItems 1 */
  basemaps: BrowserBasemap[];
  sourceBaseUrls?: SourceBaseUrls;
}

export interface WeatherPoint {
  time: string;
  temperatureCelsius: number;
  apparentTemperatureCelsius: number;
  precipitationMillimetres: number;
  precipitationProbabilityPercent: number;
  windSpeedKmh: number;
  windDirectionDegrees: number;
  weatherCode: number;
}

export interface WeatherForecast {
  points: WeatherPoint[];
}

export type ErrorError = {
  code: string;
  message: string;
};

export interface Error {
  error: ErrorError;
}

export const AcceptedValue = {
  status: "accepted",
} as const;
export type Accepted = typeof AcceptedValue;

/**
 * Missing or invalid Access assertion.
 */
export type UnauthorizedResponse = Error;

/**
 * Assertion identity or origin is not permitted.
 */
export type ForbiddenResponse = Error;

/**
 * Local state is unavailable.
 */
export type UnavailableResponse = Error;

/**
 * Work was accepted to run asynchronously.
 */
export type AcceptedResponse = Accepted;

/**
 * A conflicting run is already active.
 */
export type SyncInProgressResponse = Error;

/**
 * Resource was not found.
 */
export type NotFoundResponse = Error;

/**
 * Request is malformed.
 */
export type InvalidRequestResponse = Error;

/**
 * Provider request failed without exposing provider detail.
 */
export type ProviderUnavailableResponse = Error;

/**
 * Exact browser origin configured for this service.
 */
export type OriginParameter = string;

export type GetSyncRunsParams = {
  after?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};

export type GetWeatherParams = {
  /**
   * @minItems 1
   * @maxItems 48
   * @items.pattern ^-?[0-9]+(\\.[0-9]+)?,-?[0-9]+(\\.[0-9]+)?,.+$
   */
  point: string[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getStatusResponse200 = {
  data: Status;
  status: 200;
};

export type getStatusResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getStatusResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getStatusResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type getStatusResponseSuccess = getStatusResponse200 & {
  headers: Headers;
};
export type getStatusResponseError = (
  | getStatusResponse401
  | getStatusResponse403
  | getStatusResponse503
) & {
  headers: Headers;
};

export const getGetStatusUrl = () => {
  return `/v1/status`;
};

export const getStatus = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getStatusResponseSuccess> => {
  return domestiqueRequest<getStatusResponseSuccess>(getGetStatusUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStatusQueryKey = () => {
  return [`/v1/status`] as const;
};

export const getGetStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>>;
  request?: SecondParameter<typeof domestiqueRequest>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatusQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatus>>> = ({ signal }) =>
    getStatus({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getStatus>>>;
export type GetStatusQueryError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
>;

export function useGetStatus<
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatus>>,
          TError,
          Awaited<ReturnType<typeof getStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetStatus<
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatus>>,
          TError,
          Awaited<ReturnType<typeof getStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetStatus<
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetStatus<
  TData = Awaited<ReturnType<typeof getStatus>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatus>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetStatusQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type triggerSyncResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type triggerSyncResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type triggerSyncResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type triggerSyncResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type triggerSyncResponseSuccess = triggerSyncResponse202 & {
  headers: Headers;
};
export type triggerSyncResponseError = (
  | triggerSyncResponse401
  | triggerSyncResponse403
  | triggerSyncResponse409
) & {
  headers: Headers;
};

export const getTriggerSyncUrl = () => {
  return `/v1/sync`;
};

export const triggerSync = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<triggerSyncResponseSuccess> => {
  return domestiqueRequest<triggerSyncResponseSuccess>(getTriggerSyncUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTriggerSyncMutationOptions = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof triggerSync>>, TError, void, TContext>;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<Awaited<ReturnType<typeof triggerSync>>, TError, void, TContext> => {
  const mutationKey = ["triggerSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerSync>>, void> = () => {
    return triggerSync(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerSyncMutationResult = NonNullable<Awaited<ReturnType<typeof triggerSync>>>;

export type TriggerSyncMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse
>;

export const useTriggerSync = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof triggerSync>>, TError, void, TContext>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof triggerSync>>, TError, void, TContext> => {
  return useMutation(getTriggerSyncMutationOptions(options), queryClient);
};

export type triggerSourceSyncResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type triggerSourceSyncResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type triggerSourceSyncResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type triggerSourceSyncResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type triggerSourceSyncResponseSuccess = triggerSourceSyncResponse202 & {
  headers: Headers;
};
export type triggerSourceSyncResponseError = (
  | triggerSourceSyncResponse401
  | triggerSourceSyncResponse403
  | triggerSourceSyncResponse409
) & {
  headers: Headers;
};

export const getTriggerSourceSyncUrl = () => {
  return `/v1/sync/source`;
};

export const triggerSourceSync = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<triggerSourceSyncResponseSuccess> => {
  return domestiqueRequest<triggerSourceSyncResponseSuccess>(getTriggerSourceSyncUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTriggerSourceSyncMutationOptions = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof triggerSourceSync>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<Awaited<ReturnType<typeof triggerSourceSync>>, TError, void, TContext> => {
  const mutationKey = ["triggerSourceSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerSourceSync>>, void> = () => {
    return triggerSourceSync(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerSourceSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof triggerSourceSync>>
>;

export type TriggerSourceSyncMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse
>;

export const useTriggerSourceSync = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof triggerSourceSync>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof triggerSourceSync>>, TError, void, TContext> => {
  return useMutation(getTriggerSourceSyncMutationOptions(options), queryClient);
};

export type triggerTargetsSyncResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type triggerTargetsSyncResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type triggerTargetsSyncResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type triggerTargetsSyncResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type triggerTargetsSyncResponseSuccess = triggerTargetsSyncResponse202 & {
  headers: Headers;
};
export type triggerTargetsSyncResponseError = (
  | triggerTargetsSyncResponse401
  | triggerTargetsSyncResponse403
  | triggerTargetsSyncResponse409
) & {
  headers: Headers;
};

export const getTriggerTargetsSyncUrl = () => {
  return `/v1/sync/targets`;
};

export const triggerTargetsSync = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<triggerTargetsSyncResponseSuccess> => {
  return domestiqueRequest<triggerTargetsSyncResponseSuccess>(getTriggerTargetsSyncUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTriggerTargetsSyncMutationOptions = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof triggerTargetsSync>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<Awaited<ReturnType<typeof triggerTargetsSync>>, TError, void, TContext> => {
  const mutationKey = ["triggerTargetsSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerTargetsSync>>, void> = () => {
    return triggerTargetsSync(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerTargetsSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof triggerTargetsSync>>
>;

export type TriggerTargetsSyncMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse
>;

export const useTriggerTargetsSync = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof triggerTargetsSync>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof triggerTargetsSync>>, TError, void, TContext> => {
  return useMutation(getTriggerTargetsSyncMutationOptions(options), queryClient);
};

export type triggerTargetSyncResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type triggerTargetSyncResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type triggerTargetSyncResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type triggerTargetSyncResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type triggerTargetSyncResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type triggerTargetSyncResponseSuccess = triggerTargetSyncResponse202 & {
  headers: Headers;
};
export type triggerTargetSyncResponseError = (
  | triggerTargetSyncResponse401
  | triggerTargetSyncResponse403
  | triggerTargetSyncResponse404
  | triggerTargetSyncResponse409
) & {
  headers: Headers;
};

export const getTriggerTargetSyncUrl = (target: string) => {
  return `/v1/sync/targets/${target}`;
};

export const triggerTargetSync = async (
  target: string,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<triggerTargetSyncResponseSuccess> => {
  return domestiqueRequest<triggerTargetSyncResponseSuccess>(getTriggerTargetSyncUrl(target), {
    ...options,
    method: "POST",
  });
};

export const getTriggerTargetSyncMutationOptions = <
  TError = ErrorType<
    UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof triggerTargetSync>>,
    TError,
    TriggerTargetSyncMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof triggerTargetSync>>,
  TError,
  TriggerTargetSyncMutationVariables,
  TContext
> => {
  const mutationKey = ["triggerTargetSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof triggerTargetSync>>,
    TriggerTargetSyncMutationVariables
  > = (props) => {
    const { target } = props ?? {};

    return triggerTargetSync(target, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerTargetSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof triggerTargetSync>>
>;

export type TriggerTargetSyncMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
>;
export type TriggerTargetSyncMutationVariables = { target: string };

export const useTriggerTargetSync = <
  TError = ErrorType<
    UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof triggerTargetSync>>,
      TError,
      TriggerTargetSyncMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof triggerTargetSync>>,
  TError,
  TriggerTargetSyncMutationVariables,
  TContext
> => {
  return useMutation(getTriggerTargetSyncMutationOptions(options), queryClient);
};

export type clearTargetResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type clearTargetResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type clearTargetResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type clearTargetResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type clearTargetResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type clearTargetResponseSuccess = clearTargetResponse202 & {
  headers: Headers;
};
export type clearTargetResponseError = (
  | clearTargetResponse401
  | clearTargetResponse403
  | clearTargetResponse404
  | clearTargetResponse409
) & {
  headers: Headers;
};

export const getClearTargetUrl = (target: string) => {
  return `/v1/targets/${target}/clear`;
};

export const clearTarget = async (
  target: string,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<clearTargetResponseSuccess> => {
  return domestiqueRequest<clearTargetResponseSuccess>(getClearTargetUrl(target), {
    ...options,
    method: "POST",
  });
};

export const getClearTargetMutationOptions = <
  TError = ErrorType<
    UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clearTarget>>,
    TError,
    ClearTargetMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clearTarget>>,
  TError,
  ClearTargetMutationVariables,
  TContext
> => {
  const mutationKey = ["clearTarget"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clearTarget>>,
    ClearTargetMutationVariables
  > = (props) => {
    const { target } = props ?? {};

    return clearTarget(target, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ClearTargetMutationResult = NonNullable<Awaited<ReturnType<typeof clearTarget>>>;

export type ClearTargetMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
>;
export type ClearTargetMutationVariables = { target: string };

export const useClearTarget = <
  TError = ErrorType<
    UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | SyncInProgressResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof clearTarget>>,
      TError,
      ClearTargetMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof clearTarget>>,
  TError,
  ClearTargetMutationVariables,
  TContext
> => {
  return useMutation(getClearTargetMutationOptions(options), queryClient);
};

export type triggerSurfaceSyncResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type triggerSurfaceSyncResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type triggerSurfaceSyncResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type triggerSurfaceSyncResponse409 = {
  data: SyncInProgressResponse;
  status: 409;
};

export type triggerSurfaceSyncResponseSuccess = triggerSurfaceSyncResponse202 & {
  headers: Headers;
};
export type triggerSurfaceSyncResponseError = (
  | triggerSurfaceSyncResponse401
  | triggerSurfaceSyncResponse403
  | triggerSurfaceSyncResponse409
) & {
  headers: Headers;
};

export const getTriggerSurfaceSyncUrl = () => {
  return `/v1/sync/surface`;
};

export const triggerSurfaceSync = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<triggerSurfaceSyncResponseSuccess> => {
  return domestiqueRequest<triggerSurfaceSyncResponseSuccess>(getTriggerSurfaceSyncUrl(), {
    ...options,
    method: "POST",
  });
};

export const getTriggerSurfaceSyncMutationOptions = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof triggerSurfaceSync>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<Awaited<ReturnType<typeof triggerSurfaceSync>>, TError, void, TContext> => {
  const mutationKey = ["triggerSurfaceSync"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerSurfaceSync>>, void> = () => {
    return triggerSurfaceSync(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerSurfaceSyncMutationResult = NonNullable<
  Awaited<ReturnType<typeof triggerSurfaceSync>>
>;

export type TriggerSurfaceSyncMutationError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse
>;

export const useTriggerSurfaceSync = <
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | SyncInProgressResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof triggerSurfaceSync>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof triggerSurfaceSync>>, TError, void, TContext> => {
  return useMutation(getTriggerSurfaceSyncMutationOptions(options), queryClient);
};

export type setSyncScheduleResponse200 = {
  data: SyncSchedule;
  status: 200;
};

export type setSyncScheduleResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type setSyncScheduleResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type setSyncScheduleResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type setSyncScheduleResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type setSyncScheduleResponseSuccess = setSyncScheduleResponse200 & {
  headers: Headers;
};
export type setSyncScheduleResponseError = (
  | setSyncScheduleResponse400
  | setSyncScheduleResponse401
  | setSyncScheduleResponse403
  | setSyncScheduleResponse503
) & {
  headers: Headers;
};

export const getSetSyncScheduleUrl = () => {
  return `/v1/sync/schedule`;
};

export const setSyncSchedule = async (
  syncSchedule: SyncSchedule,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<setSyncScheduleResponseSuccess> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return domestiqueRequest<setSyncScheduleResponseSuccess>(getSetSyncScheduleUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
    body: JSON.stringify(syncSchedule),
  });
};

export const getSetSyncScheduleMutationOptions = <
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof setSyncSchedule>>,
    TError,
    SetSyncScheduleMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof setSyncSchedule>>,
  TError,
  SetSyncScheduleMutationVariables,
  TContext
> => {
  const mutationKey = ["setSyncSchedule"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof setSyncSchedule>>,
    SetSyncScheduleMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return setSyncSchedule(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetSyncScheduleMutationResult = NonNullable<
  Awaited<ReturnType<typeof setSyncSchedule>>
>;
export type SetSyncScheduleMutationBody = SyncSchedule;
export type SetSyncScheduleMutationError = ErrorType<
  InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
>;
export type SetSyncScheduleMutationVariables = { data: SyncSchedule };

export const useSetSyncSchedule = <
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof setSyncSchedule>>,
      TError,
      SetSyncScheduleMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof setSyncSchedule>>,
  TError,
  SetSyncScheduleMutationVariables,
  TContext
> => {
  return useMutation(getSetSyncScheduleMutationOptions(options), queryClient);
};

export type getSyncRunsResponse200 = {
  data: SyncRunPage;
  status: 200;
};

export type getSyncRunsResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type getSyncRunsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSyncRunsResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getSyncRunsResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type getSyncRunsResponseSuccess = getSyncRunsResponse200 & {
  headers: Headers;
};
export type getSyncRunsResponseError = (
  | getSyncRunsResponse400
  | getSyncRunsResponse401
  | getSyncRunsResponse403
  | getSyncRunsResponse503
) & {
  headers: Headers;
};

export const getGetSyncRunsUrl = (params?: GetSyncRunsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/sync/runs?${stringifiedParams}` : `/v1/sync/runs`;
};

export const getSyncRuns = async (
  params?: GetSyncRunsParams,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getSyncRunsResponseSuccess> => {
  return domestiqueRequest<getSyncRunsResponseSuccess>(getGetSyncRunsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetSyncRunsInfiniteQueryKey = (params?: GetSyncRunsParams) => {
  return ["infinite", `/v1/sync/runs`, ...(params ? [params] : [])] as const;
};

export const getGetSyncRunsQueryKey = (params?: GetSyncRunsParams) => {
  return [`/v1/sync/runs`, ...(params ? [params] : [])] as const;
};

export const getGetSyncRunsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSyncRuns>>, GetSyncRunsParams["after"]>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getSyncRuns>>,
        TError,
        TData,
        QueryKey,
        GetSyncRunsParams["after"]
      >
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSyncRunsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getSyncRuns>>,
    QueryKey,
    GetSyncRunsParams["after"]
  > = ({ signal, pageParam }) =>
    getSyncRuns(
      { ...params, after: (pageParam ?? params?.after) as string },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getSyncRuns>>,
    TError,
    TData,
    QueryKey,
    GetSyncRunsParams["after"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSyncRunsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getSyncRuns>>>;
export type GetSyncRunsInfiniteQueryError = ErrorType<
  InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
>;

export function useGetSyncRunsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSyncRuns>>, GetSyncRunsParams["after"]>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params: undefined | GetSyncRunsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getSyncRuns>>,
        TError,
        TData,
        QueryKey,
        GetSyncRunsParams["after"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncRuns>>,
          TError,
          Awaited<ReturnType<typeof getSyncRuns>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSyncRunsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSyncRuns>>, GetSyncRunsParams["after"]>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getSyncRuns>>,
        TError,
        TData,
        QueryKey,
        GetSyncRunsParams["after"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncRuns>>,
          TError,
          Awaited<ReturnType<typeof getSyncRuns>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSyncRunsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSyncRuns>>, GetSyncRunsParams["after"]>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getSyncRuns>>,
        TError,
        TData,
        QueryKey,
        GetSyncRunsParams["after"]
      >
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSyncRunsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSyncRuns>>, GetSyncRunsParams["after"]>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getSyncRuns>>,
        TError,
        TData,
        QueryKey,
        GetSyncRunsParams["after"]
      >
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSyncRunsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetSyncRunsQueryOptions = <
  TData = Awaited<ReturnType<typeof getSyncRuns>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncRuns>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSyncRunsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSyncRuns>>> = ({ signal }) =>
    getSyncRuns(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSyncRuns>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetSyncRunsQueryResult = NonNullable<Awaited<ReturnType<typeof getSyncRuns>>>;
export type GetSyncRunsQueryError = ErrorType<
  InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
>;

export function useGetSyncRuns<
  TData = Awaited<ReturnType<typeof getSyncRuns>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params: undefined | GetSyncRunsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncRuns>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncRuns>>,
          TError,
          Awaited<ReturnType<typeof getSyncRuns>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSyncRuns<
  TData = Awaited<ReturnType<typeof getSyncRuns>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncRuns>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSyncRuns>>,
          TError,
          Awaited<ReturnType<typeof getSyncRuns>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSyncRuns<
  TData = Awaited<ReturnType<typeof getSyncRuns>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncRuns>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetSyncRuns<
  TData = Awaited<ReturnType<typeof getSyncRuns>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
  >,
>(
  params?: GetSyncRunsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSyncRuns>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSyncRunsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getRoutesResponse200 = {
  data: RouteList;
  status: 200;
};

export type getRoutesResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getRoutesResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getRoutesResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type getRoutesResponseSuccess = getRoutesResponse200 & {
  headers: Headers;
};
export type getRoutesResponseError = (
  | getRoutesResponse401
  | getRoutesResponse403
  | getRoutesResponse503
) & {
  headers: Headers;
};

export const getGetRoutesUrl = () => {
  return `/v1/routes`;
};

export const getRoutes = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getRoutesResponseSuccess> => {
  return domestiqueRequest<getRoutesResponseSuccess>(getGetRoutesUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRoutesQueryKey = () => {
  return [`/v1/routes`] as const;
};

export const getGetRoutesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>;
  request?: SecondParameter<typeof domestiqueRequest>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRoutesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoutes>>> = ({ signal }) =>
    getRoutes({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoutes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof getRoutes>>>;
export type GetRoutesQueryError = ErrorType<
  UnauthorizedResponse | ForbiddenResponse | UnavailableResponse
>;

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse | UnavailableResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRoutesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getRouteResponse200 = {
  data: Route;
  status: 200;
};

export type getRouteResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type getRouteResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getRouteResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getRouteResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getRouteResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type getRouteResponseSuccess = getRouteResponse200 & {
  headers: Headers;
};
export type getRouteResponseError = (
  | getRouteResponse400
  | getRouteResponse401
  | getRouteResponse403
  | getRouteResponse404
  | getRouteResponse503
) & {
  headers: Headers;
};

export const getGetRouteUrl = (provider: string, routeId: number, stage: number) => {
  return `/v1/providers/${provider}/routes/${routeId}/stages/${stage}`;
};

export const getRoute = async (
  provider: string,
  routeId: number,
  stage: number,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getRouteResponseSuccess> => {
  return domestiqueRequest<getRouteResponseSuccess>(getGetRouteUrl(provider, routeId, stage), {
    ...options,
    method: "GET",
  });
};

export const getGetRouteQueryKey = (provider: string, routeId: number, stage: number) => {
  return [`/v1/providers/${provider}/routes/${routeId}/stages/${stage}`] as const;
};

export const getGetRouteQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRouteQueryKey(provider, routeId, stage);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoute>>> = ({ signal }) =>
    getRoute(provider, routeId, stage, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      provider !== null &&
      provider !== undefined &&
      routeId !== null &&
      routeId !== undefined &&
      stage !== null &&
      stage !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetRouteQueryResult = NonNullable<Awaited<ReturnType<typeof getRoute>>>;
export type GetRouteQueryError = ErrorType<
  | InvalidRequestResponse
  | UnauthorizedResponse
  | ForbiddenResponse
  | NotFoundResponse
  | UnavailableResponse
>;

export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoute>>,
          TError,
          Awaited<ReturnType<typeof getRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoute>>,
          TError,
          Awaited<ReturnType<typeof getRoute>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRouteQueryOptions(provider, routeId, stage, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getRouteGeometryResponse200 = {
  data: GeoJSONFeature;
  status: 200;
};

export type getRouteGeometryResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type getRouteGeometryResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getRouteGeometryResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getRouteGeometryResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getRouteGeometryResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type getRouteGeometryResponseSuccess = getRouteGeometryResponse200 & {
  headers: Headers;
};
export type getRouteGeometryResponseError = (
  | getRouteGeometryResponse400
  | getRouteGeometryResponse401
  | getRouteGeometryResponse403
  | getRouteGeometryResponse404
  | getRouteGeometryResponse503
) & {
  headers: Headers;
};

export const getGetRouteGeometryUrl = (provider: string, routeId: number, stage: number) => {
  return `/v1/providers/${provider}/routes/${routeId}/stages/${stage}/geometry`;
};

export const getRouteGeometry = async (
  provider: string,
  routeId: number,
  stage: number,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getRouteGeometryResponseSuccess> => {
  return domestiqueRequest<getRouteGeometryResponseSuccess>(
    getGetRouteGeometryUrl(provider, routeId, stage),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetRouteGeometryQueryKey = (provider: string, routeId: number, stage: number) => {
  return [`/v1/providers/${provider}/routes/${routeId}/stages/${stage}/geometry`] as const;
};

export const getGetRouteGeometryQueryOptions = <
  TData = Awaited<ReturnType<typeof getRouteGeometry>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRouteGeometryQueryKey(provider, routeId, stage);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRouteGeometry>>> = ({ signal }) =>
    getRouteGeometry(provider, routeId, stage, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      provider !== null &&
      provider !== undefined &&
      routeId !== null &&
      routeId !== undefined &&
      stage !== null &&
      stage !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetRouteGeometryQueryResult = NonNullable<Awaited<ReturnType<typeof getRouteGeometry>>>;
export type GetRouteGeometryQueryError = ErrorType<
  | InvalidRequestResponse
  | UnauthorizedResponse
  | ForbiddenResponse
  | NotFoundResponse
  | UnavailableResponse
>;

export function useGetRouteGeometry<
  TData = Awaited<ReturnType<typeof getRouteGeometry>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRouteGeometry>>,
          TError,
          Awaited<ReturnType<typeof getRouteGeometry>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRouteGeometry<
  TData = Awaited<ReturnType<typeof getRouteGeometry>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRouteGeometry>>,
          TError,
          Awaited<ReturnType<typeof getRouteGeometry>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRouteGeometry<
  TData = Awaited<ReturnType<typeof getRouteGeometry>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetRouteGeometry<
  TData = Awaited<ReturnType<typeof getRouteGeometry>>,
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
>(
  provider: string,
  routeId: number,
  stage: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRouteGeometry>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRouteGeometryQueryOptions(provider, routeId, stage, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type reprocessRouteResponse202 = {
  data: AcceptedResponse;
  status: 202;
};

export type reprocessRouteResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type reprocessRouteResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type reprocessRouteResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type reprocessRouteResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type reprocessRouteResponse503 = {
  data: UnavailableResponse;
  status: 503;
};

export type reprocessRouteResponseSuccess = reprocessRouteResponse202 & {
  headers: Headers;
};
export type reprocessRouteResponseError = (
  | reprocessRouteResponse400
  | reprocessRouteResponse401
  | reprocessRouteResponse403
  | reprocessRouteResponse404
  | reprocessRouteResponse503
) & {
  headers: Headers;
};

export const getReprocessRouteUrl = (provider: string, routeId: number, stage: number) => {
  return `/v1/providers/${provider}/routes/${routeId}/stages/${stage}/reprocess`;
};

export const reprocessRoute = async (
  provider: string,
  routeId: number,
  stage: number,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<reprocessRouteResponseSuccess> => {
  return domestiqueRequest<reprocessRouteResponseSuccess>(
    getReprocessRouteUrl(provider, routeId, stage),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getReprocessRouteMutationOptions = <
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reprocessRoute>>,
    TError,
    ReprocessRouteMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof domestiqueRequest>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reprocessRoute>>,
  TError,
  ReprocessRouteMutationVariables,
  TContext
> => {
  const mutationKey = ["reprocessRoute"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reprocessRoute>>,
    ReprocessRouteMutationVariables
  > = (props) => {
    const { provider, routeId, stage } = props ?? {};

    return reprocessRoute(provider, routeId, stage, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReprocessRouteMutationResult = NonNullable<Awaited<ReturnType<typeof reprocessRoute>>>;

export type ReprocessRouteMutationError = ErrorType<
  | InvalidRequestResponse
  | UnauthorizedResponse
  | ForbiddenResponse
  | NotFoundResponse
  | UnavailableResponse
>;
export type ReprocessRouteMutationVariables = { provider: string; routeId: number; stage: number };

export const useReprocessRoute = <
  TError = ErrorType<
    | InvalidRequestResponse
    | UnauthorizedResponse
    | ForbiddenResponse
    | NotFoundResponse
    | UnavailableResponse
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reprocessRoute>>,
      TError,
      ReprocessRouteMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reprocessRoute>>,
  TError,
  ReprocessRouteMutationVariables,
  TContext
> => {
  return useMutation(getReprocessRouteMutationOptions(options), queryClient);
};

export type getWebUIConfigResponse200 = {
  data: WebUIConfig;
  status: 200;
};

export type getWebUIConfigResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getWebUIConfigResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getWebUIConfigResponseSuccess = getWebUIConfigResponse200 & {
  headers: Headers;
};
export type getWebUIConfigResponseError = (
  | getWebUIConfigResponse401
  | getWebUIConfigResponse403
) & {
  headers: Headers;
};

export const getGetWebUIConfigUrl = () => {
  return `/v1/webui/config`;
};

export const getWebUIConfig = async (
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getWebUIConfigResponseSuccess> => {
  return domestiqueRequest<getWebUIConfigResponseSuccess>(getGetWebUIConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetWebUIConfigQueryKey = () => {
  return [`/v1/webui/config`] as const;
};

export const getGetWebUIConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getWebUIConfig>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWebUIConfig>>, TError, TData>>;
  request?: SecondParameter<typeof domestiqueRequest>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWebUIConfigQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWebUIConfig>>> = ({ signal }) =>
    getWebUIConfig({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWebUIConfig>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWebUIConfigQueryResult = NonNullable<Awaited<ReturnType<typeof getWebUIConfig>>>;
export type GetWebUIConfigQueryError = ErrorType<UnauthorizedResponse | ForbiddenResponse>;

export function useGetWebUIConfig<
  TData = Awaited<ReturnType<typeof getWebUIConfig>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWebUIConfig>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWebUIConfig>>,
          TError,
          Awaited<ReturnType<typeof getWebUIConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWebUIConfig<
  TData = Awaited<ReturnType<typeof getWebUIConfig>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWebUIConfig>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWebUIConfig>>,
          TError,
          Awaited<ReturnType<typeof getWebUIConfig>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWebUIConfig<
  TData = Awaited<ReturnType<typeof getWebUIConfig>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWebUIConfig>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetWebUIConfig<
  TData = Awaited<ReturnType<typeof getWebUIConfig>>,
  TError = ErrorType<UnauthorizedResponse | ForbiddenResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWebUIConfig>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWebUIConfigQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export type getWeatherResponse200 = {
  data: WeatherForecast;
  status: 200;
};

export type getWeatherResponse400 = {
  data: InvalidRequestResponse;
  status: 400;
};

export type getWeatherResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getWeatherResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getWeatherResponse502 = {
  data: ProviderUnavailableResponse;
  status: 502;
};

export type getWeatherResponseSuccess = getWeatherResponse200 & {
  headers: Headers;
};
export type getWeatherResponseError = (
  | getWeatherResponse400
  | getWeatherResponse401
  | getWeatherResponse403
  | getWeatherResponse502
) & {
  headers: Headers;
};

export const getGetWeatherUrl = (params: GetWeatherParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["point"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? "null" : String(v));
      });
      return;
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/weather?${stringifiedParams}` : `/v1/weather`;
};

export const getWeather = async (
  params: GetWeatherParams,
  options?: Parameters<typeof domestiqueRequest>[1],
): Promise<getWeatherResponseSuccess> => {
  return domestiqueRequest<getWeatherResponseSuccess>(getGetWeatherUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetWeatherQueryKey = (params?: GetWeatherParams) => {
  return [`/v1/weather`, ...(params ? [params] : [])] as const;
};

export const getGetWeatherQueryOptions = <
  TData = Awaited<ReturnType<typeof getWeather>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
  >,
>(
  params: GetWeatherParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWeatherQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeather>>> = ({ signal }) =>
    getWeather(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWeather>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWeatherQueryResult = NonNullable<Awaited<ReturnType<typeof getWeather>>>;
export type GetWeatherQueryError = ErrorType<
  InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
>;

export function useGetWeather<
  TData = Awaited<ReturnType<typeof getWeather>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
  >,
>(
  params: GetWeatherParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeather>>,
          TError,
          Awaited<ReturnType<typeof getWeather>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWeather<
  TData = Awaited<ReturnType<typeof getWeather>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
  >,
>(
  params: GetWeatherParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeather>>,
          TError,
          Awaited<ReturnType<typeof getWeather>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWeather<
  TData = Awaited<ReturnType<typeof getWeather>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
  >,
>(
  params: GetWeatherParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetWeather<
  TData = Awaited<ReturnType<typeof getWeather>>,
  TError = ErrorType<
    InvalidRequestResponse | UnauthorizedResponse | ForbiddenResponse | ProviderUnavailableResponse
  >,
>(
  params: GetWeatherParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeather>>, TError, TData>>;
    request?: SecondParameter<typeof domestiqueRequest>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWeatherQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
