#!/usr/bin/env bash
#
# Starts the browser UI against a synthetic demo library.
#
# One command, no accounts, no snapshot of anyone's routes: it writes a
# throwaway configuration under .local/demo, seeds a fresh database with the
# invented stages in internal/demo, serves them with dev/demoapi, and runs the
# UI dev server against it. Nothing here is tracked by Git.
#
# Safety model — the demo cannot reach a provider or an operator deployment:
#
#   * Every stage, surface and run it shows is generated by internal/demo. No
#     VeloPlanner account is read and no deployed state is copied.
#   * The database is created here and deleted on the next run. It is never the
#     deployed file, and the two services never share one.
#   * VeloPlanner, Wahoo and Pushover all point at an unroutable address, so no
#     code path can reach them even if one tried.
#   * dev/demoapi wires no scheduler, no source client and no reporter. A manual
#     synchronisation re-seeds the synthetic library instead of contacting
#     anything, so the run it reports is real and its data still is not.
#   * The identity gate is the production one. The demo signs an assertion with
#     a key it generates at start-up and verifies it against that key, so the
#     gate runs in full rather than being switched off.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --with-bundle builds the browser UI first, so the demo API embeds a current
# production bundle and serves it at its own port beside the dev server. That is
# the arrangement a deployment runs — the built bundle behind the identity gate,
# the cache headers and the content security policy — and it is what the browser
# suite's bundle project drives. Without the flag the demo is the dev server
# alone, and the API serves whatever bundle the last build left embedded, if any.
WITH_BUNDLE=false
for argument in "$@"; do
  case "${argument}" in
  --with-bundle)
    WITH_BUNDLE=true
    ;;
  *)
    echo "usage: $(basename "$0") [--with-bundle]" >&2
    exit 2
    ;;
  esac
done
DEMO_DIR="${ROOT}/.local/demo"
DEMO_SECRETS="${DEMO_DIR}/secrets"
CONFIG="${DEMO_DIR}/config.toml"
DATABASE="${DEMO_DIR}/state.db"
ASSERTION_FILE="${DEMO_DIR}/assertion"

# Not :8081, so a demo can run beside `mise run dev-api` without either of them
# wondering why the other's routes are missing.
# `go` and `pnpm` are taken from the environment rather than resolved here:
# whatever activated the pinned toolchain for the caller — Mise, in every
# documented setup — has already put them on the path.
GO="${GO:-go}"
PNPM="${PNPM:-pnpm}"

API_PORT="${DOMESTIQUE_DEMO_PORT:-8082}"
API_URL="http://127.0.0.1:${API_PORT}"
# The origin the API is configured to serve its UI at, which state-changing
# requests must come from. Unroutable, and only ever named, never fetched.
BROWSER_ORIGIN="https://127.0.0.1:9"
# The states the two configured slots are seeded in: one holding the whole
# library, one that has never completed its browser onboarding.
SLOT_STATES="${DOMESTIQUE_DEMO_SLOTS:-current,unauthorized}"

mkdir -p "${DEMO_SECRETS}"
chmod 700 "${DEMO_DIR}" "${DEMO_SECRETS}"

# Placeholders, spelled out here so it is obvious there is no real credential in
# a demo. The encryption key is 32 bytes of base64url; the rest are never sent
# anywhere, because nothing the demo runs has a destination to send them to.
printf 'A%.0s' $(seq 43) > "${DEMO_SECRETS}/state_encryption_key"
for placeholder in veloplanner_email veloplanner_password wahoo_client_secret \
  pushover_application_token pushover_user_key; do
  printf 'demo-placeholder' > "${DEMO_SECRETS}/${placeholder}"
done
chmod 600 "${DEMO_SECRETS}"/*

cat > "${CONFIG}" <<EOF
# Generated by dev/demo.sh. Do not edit by hand; re-run the script instead.
# Every provider below is unroutable on purpose.

[http]
listen_address = ":${API_PORT}"

[access.cloudflare]
# A local team: dev/demoapi generates the signing key and publishes it to the
# production verifier in process. There is no Cloudflare account behind this.
team_domain = "demo"
application_aud = "demo-application"
allowed_email = "rider@example.test"

[state]
database_path = "${DATABASE}"
encryption_key_file = "${DEMO_SECRETS}/state_encryption_key"

[veloplanner]
base_url = "${BROWSER_ORIGIN}"
email_file = "${DEMO_SECRETS}/veloplanner_email"
password_file = "${DEMO_SECRETS}/veloplanner_password"

[wahoo]
api_base_url = "${BROWSER_ORIGIN}"
oauth_base_url = "${BROWSER_ORIGIN}"
client_id = "demo-placeholder"
client_secret_file = "${DEMO_SECRETS}/wahoo_client_secret"
redirect_url = "${BROWSER_ORIGIN}/oauth/wahoo/callback"

[[wahoo.targets]]
id = "rider-a"

[[wahoo.targets]]
id = "rider-b"

[sync]
initial_delay = "8760h"
interval = "1h"
max_deletions_per_target = 5
empty_source_deletion = "deny"

[surface]
# Empty: the demo's classifications are seeded, so no map extract is ever
# downloaded and no surface index is ever built.
regions = []

# A single tile provider with several distinct cartographies makes the desktop
# map reviewable without widening the demo's network boundary. These are demo
# choices only; production keeps its own configured default.
[[webui.basemaps]]
name = "Streets"
style_url = "https://tiles.openfreemap.org/styles/bright"
style_url_dark = "https://tiles.openfreemap.org/styles/dark"

[[webui.basemaps]]
name = "Positron"
style_url = "https://tiles.openfreemap.org/styles/positron"

[[webui.basemaps]]
name = "Liberty"
style_url = "https://tiles.openfreemap.org/styles/liberty"

[[webui.basemaps]]
name = "Dark"
style_url = "https://tiles.openfreemap.org/styles/dark"
dark_cartography = true

[[webui.basemaps]]
name = "Fiord"
style_url = "https://tiles.openfreemap.org/styles/fiord"

[notifications.pushover]
base_url = "${BROWSER_ORIGIN}"
application_token_file = "${DEMO_SECRETS}/pushover_application_token"
user_key_file = "${DEMO_SECRETS}/pushover_user_key"
EOF
chmod 600 "${CONFIG}"

export DOMESTIQUE_CONFIG_FILE="${CONFIG}"
export CGO_ENABLED=0

# Built rather than `go run`, because `go run` starts a child of its own: the
# process this script can signal would not be the one holding the port, and
# stopping the demo would leave an API behind still serving it.
# Before the binary, because the bundle is embedded at compile time: building it
# afterwards would leave the running API serving the previous one. The bundler
# empties dist, which would remove the placeholder that keeps the go:embed
# pattern valid, so it is restored the same way `mise run ui-build` does.
if [[ "${WITH_BUNDLE}" == true ]]; then
  "${PNPM}" --dir "${ROOT}/internal/webui/app" run build
  touch "${ROOT}/internal/webui/app/dist/.gitkeep"
fi

BIN_DIR="${DEMO_DIR}/bin"
mkdir -p "${BIN_DIR}"
"${GO}" build -o "${BIN_DIR}/" "${ROOT}/dev/demoapi"

# A fresh database every run, so the demo is the fixture and not whatever last
# week's session left behind.
rm -f "${DATABASE}" "${DATABASE}-wal" "${DATABASE}-shm" "${ASSERTION_FILE}"

"${BIN_DIR}/demoapi" -assertion-file "${ASSERTION_FILE}" -states "${SLOT_STATES}" &
API_PID=$!

cleanup() {
  if kill -0 "${API_PID}" 2>/dev/null; then
    kill "${API_PID}" 2>/dev/null || true
    wait "${API_PID}" 2>/dev/null || true
  fi
  rm -f "${ASSERTION_FILE}"
}
trap cleanup EXIT INT TERM

for _ in $(seq 100); do
  if [[ -s "${ASSERTION_FILE}" ]] && curl -fsS "${API_URL}/healthz" >/dev/null 2>&1; then
    break
  fi
  if ! kill -0 "${API_PID}" 2>/dev/null; then
    echo "error: the demo API exited before it was ready" >&2
    exit 1
  fi
  sleep 0.2
done
if [[ ! -s "${ASSERTION_FILE}" ]]; then
  echo "error: the demo API did not become ready" >&2
  exit 1
fi

echo "Demo API on ${API_URL}; starting the UI dev server on http://127.0.0.1:5173"
DOMESTIQUE_DEV_API="${API_URL}" \
  DOMESTIQUE_DEV_ASSERTION="$(cat "${ASSERTION_FILE}")" \
  DOMESTIQUE_DEV_ORIGIN="${BROWSER_ORIGIN}" \
  "${PNPM}" --dir "${ROOT}/internal/webui/app" run dev
