#!/usr/bin/env bash
#
# Starts the browser UI against a synthetic demo library.
#
# One command, no accounts, no snapshot of anyone's routes: it writes a
# throwaway configuration under .local/demo, seeds a fresh database with the
# invented stages in internal/demo, serves them with dev/demoapi, and runs the
# UI dev server against it. Nothing here is tracked by Git.
#
# Safety model — the demo cannot reach a provider or an operator deployment:
#
#   * Every stage, surface and run it shows is generated by internal/demo. No
#     VeloPlanner account is read and no deployed state is copied.
#   * The database is created here and deleted on the next run. It is never the
#     deployed file, and the two services never share one.
#   * VeloPlanner, Wahoo and Pushover are all seeded pointing at this demo's own
#     origin, which serves the UI and nothing else, so no code path can reach a
#     provider even if one tried.
#   * dev/demoapi wires no scheduler, no source client and no reporter. A manual
#     synchronisation re-seeds the synthetic library instead of contacting
#     anything, so the run it reports is real and its data still is not.
#   * The identity gate is the production one. The demo signs an assertion with
#     a key it generates at start-up and verifies it against that key, so the
#     gate runs in full rather than being switched off.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# --with-bundle builds the browser UI first, so the demo API embeds a current
# production bundle and serves it at its own port beside the dev server. That is
# the arrangement a deployment runs — the built bundle behind the identity gate,
# the cache headers and the content security policy — and it is what the browser
# suite's bundle project drives. Without the flag the demo is the dev server
# alone, and the API serves whatever bundle the last build left embedded, if any.
WITH_BUNDLE=false

# --tailnet publishes the demo on this machine's MagicDNS name, so a phone or a
# second desktop can open it.
#
# `tailscale serve` rather than a wider listening address, for two reasons. It
# reaches the tailnet and nothing else, where Vite — which binds one address —
# could only offer every network this machine is on at once. And the macOS
# application firewall drops incoming connections to binaries it has no rule
# for, which `node` is and Tailscale's network extension is not: Serve arrives
# through the extension and dials loopback, so the firewall never sees a
# connection to the dev server at all and needs no exception for one.
#
# Whoever opens it is the demo rider, because the dev server signs every request
# it proxies with the demo's own assertion. Everything behind that is synthetic
# and no provider is reachable, so what a tailnet peer is being handed is the
# invented library and the button that re-seeds it. Serve keeps that inside a
# set of devices already admitted; Funnel would not, which is why this is Serve.
TAILNET=false
for argument in "$@"; do
  case "${argument}" in
  --with-bundle)
    WITH_BUNDLE=true
    ;;
  --tailnet)
    TAILNET=true
    ;;
  *)
    echo "usage: $(basename "$0") [--with-bundle] [--tailnet]" >&2
    exit 2
    ;;
  esac
done

if [[ "${TAILNET}" == true ]] && ! command -v tailscale > /dev/null 2>&1; then
  echo "error: --tailnet needs the tailscale CLI on PATH" >&2
  exit 2
fi

DEMO_DIR="${ROOT}/.local/demo"
DEMO_SECRETS="${DEMO_DIR}/secrets"
CONFIG="${DEMO_DIR}/config.toml"
DATABASE="${DEMO_DIR}/state.db"
ASSERTION_FILE="${DEMO_DIR}/assertion"

# Not :8081, so a demo can run beside `mise run dev-api` without either of them
# wondering why the other's routes are missing.
# `go` and `pnpm` are taken from the environment rather than resolved here:
# whatever activated the pinned toolchain for the caller — Mise, in every
# documented setup — has already put them on the path.
GO="${GO:-go}"
PNPM="${PNPM:-pnpm}"

# PORT is set per preview; deriving the API's port from it keeps two demos
# on one machine from proxying into each other's identity gate.
API_PORT="${DOMESTIQUE_DEMO_PORT:-$(( ${PORT:-8081} + 1 ))}"
API_URL="http://127.0.0.1:${API_PORT}"
# Where the dev server answers. vite.config.ts reads the same PORT variable
# and pins the result with `strictPort`, so this names that port, not chooses.
UI_PORT="${PORT:-5173}"
# The origin the API is configured to serve its UI at, which state-changing
# requests must come from. Unroutable, and only ever named, never fetched.
BROWSER_ORIGIN="https://127.0.0.1:9"
# The states the two configured slots are seeded in: one holding the whole
# library, one that has never completed its browser onboarding.
SLOT_STATES="${DOMESTIQUE_DEMO_SLOTS:-current,unauthorized}"

mkdir -p "${DEMO_SECRETS}"
chmod 700 "${DEMO_DIR}" "${DEMO_SECRETS}"

# A placeholder, spelled out here so it is obvious there is no real credential
# in a demo: 32 bytes of base64url. Every other credential is a setting now, and
# dev/demoapi seeds those as placeholders too.
printf 'A%.0s' $(seq 43) > "${DEMO_SECRETS}/state_encryption_key"
chmod 600 "${DEMO_SECRETS}"/*

cat > "${CONFIG}" <<EOF
# Generated by dev/demo.sh. Do not edit by hand; re-run the script instead.
# Every provider below is unroutable on purpose.

[http]
listen_address = ":${API_PORT}"
browser_origin_url = "${BROWSER_ORIGIN}"

[access.cloudflare]
# A local team: dev/demoapi generates the signing key and publishes it to the
# production verifier in process. There is no Cloudflare account behind this.
team_domain = "demo"
application_aud = "demo-application"
allowed_email = "rider@example.test"

[state]
database_path = "${DATABASE}"
encryption_key_file = "${DEMO_SECRETS}/state_encryption_key"

# Everything else — the Wahoo application and its two target slots, the library,
# the cartographies, the credentials and the year-long delay before a scheduled
# run — lives in the state database now, and dev/demoapi seeds it at start-up.
# Every address it seeds is this demo's own origin, which serves the UI and
# nothing else.
EOF
chmod 600 "${CONFIG}"

export DOMESTIQUE_CONFIG_FILE="${CONFIG}"
export CGO_ENABLED=0

# Built rather than `go run`, because `go run` starts a child of its own: the
# process this script can signal would not be the one holding the port, and
# stopping the demo would leave an API behind still serving it.
# Before the binary, because the bundle is embedded at compile time: building it
# afterwards would leave the running API serving the previous one.
if [[ "${WITH_BUNDLE}" == true ]]; then
  "${PNPM}" --dir "${ROOT}/internal/webui/app" run build
fi

BIN_DIR="${DEMO_DIR}/bin"
mkdir -p "${BIN_DIR}"
"${GO}" build -o "${BIN_DIR}/" "${ROOT}/dev/demoapi"

# A fresh database every run, so the demo is the fixture and not whatever last
# week's session left behind.
rm -f "${DATABASE}" "${DATABASE}-wal" "${DATABASE}-shm" "${ASSERTION_FILE}"

"${BIN_DIR}/demoapi" -assertion-file "${ASSERTION_FILE}" -states "${SLOT_STATES}" &
API_PID=$!

SERVE_PID=""

cleanup() {
  if [[ -n "${SERVE_PID}" ]] && kill -0 "${SERVE_PID}" 2>/dev/null; then
    kill "${SERVE_PID}" 2>/dev/null || true
    wait "${SERVE_PID}" 2>/dev/null || true
  fi
  if kill -0 "${API_PID}" 2>/dev/null; then
    kill "${API_PID}" 2>/dev/null || true
    wait "${API_PID}" 2>/dev/null || true
  fi
  rm -f "${ASSERTION_FILE}"
}
trap cleanup EXIT INT TERM

for _ in $(seq 100); do
  if [[ -s "${ASSERTION_FILE}" ]] && curl -fsS "${API_URL}/healthz" >/dev/null 2>&1; then
    break
  fi
  if ! kill -0 "${API_PID}" 2>/dev/null; then
    echo "error: the demo API exited before it was ready" >&2
    exit 1
  fi
  sleep 0.2
done
if [[ ! -s "${ASSERTION_FILE}" ]]; then
  echo "error: the demo API did not become ready" >&2
  exit 1
fi

# Serve's own foreground mode, not `--bg`. The shell does put the process in the
# background; what matters is that tailscaled did not, so the configuration is
# held for as long as this process lives and taken away when it dies — stopping
# the demo stops publishing it. `--bg` would hand the configuration to tailscaled
# to keep, outliving the demo and proxying a port with nothing behind it.
#
# Started before the dev server because the dev server is this script's
# foreground process and never returns. The same port on both sides, so hot
# reload keeps talking to the origin the page came from.
if [[ "${TAILNET}" == true ]]; then
  tailscale serve --http="${UI_PORT}" "${UI_PORT}" &
  SERVE_PID=$!

  # A Serve that took the port prints its URL and stays; one that could not —
  # Tailscale stopped, the node not logged in, this port already served, a
  # permission it does not have — prints why and exits at once. `set -e` does
  # not see a background command fail, so without this the demo would come up
  # published nowhere and say nothing about it. The reason is already on screen
  # above, so this says what it means rather than repeating it.
  for _ in $(seq 20); do
    if ! kill -0 "${SERVE_PID}" 2>/dev/null; then
      echo "error: tailscale serve exited; the demo would not be on the tailnet" >&2
      exit 1
    fi
    sleep 0.1
  done
fi

echo "Demo API on ${API_URL}; starting the UI dev server on http://127.0.0.1:${UI_PORT}"
DOMESTIQUE_DEV_API="${API_URL}" \
  DOMESTIQUE_DEV_ASSERTION="$(cat "${ASSERTION_FILE}")" \
  DOMESTIQUE_DEV_ORIGIN="${BROWSER_ORIGIN}" \
  DOMESTIQUE_DEV_TAILNET="${TAILNET}" \
  "${PNPM}" --dir "${ROOT}/internal/webui/app" run dev
