#!/usr/bin/env bash
#
# Prepares a local development environment that shows real route data.
#
# It snapshots the deployed SQLite state into .local/dev and writes a
# development configuration beside it. Nothing here is tracked by Git.
#
# Safety model — the development service may read VeloPlanner, but must never
# reach Wahoo:
#
#   * The snapshot is a copy. Writes during development cannot affect the
#     deployed database, and the two services never share a SQLite file.
#   * The state encryption key is a deliberate placeholder, so the stored Wahoo
#     refresh tokens cannot be decrypted. Synchronisation therefore fails at the
#     state step, which happens *before* any Wahoo request is attempted.
#   * The Wahoo endpoints additionally point at an unroutable address, so even a
#     code change that got past the step above could not reach the real API.
#   * Scheduled synchronisation is pushed a year out, so a run only ever happens
#     when you ask for one with POST /v1/sync. Such a run refreshes routes and
#     geometry from VeloPlanner, then stops before Wahoo.
#
set -euo pipefail

CONTAINER="${DOMESTIQUE_CONTAINER:-domestique-domestique-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_DIR="${ROOT}/.local/dev"
DEV_SECRETS="${DEV_DIR}/secrets"
DEPLOYED_SECRETS="${ROOT}/.local/run/secrets"

if ! docker inspect "${CONTAINER}" >/dev/null 2>&1; then
  echo "error: container ${CONTAINER} not found; start the deployment first" >&2
  exit 1
fi

for secret in veloplanner_email veloplanner_password; do
  if [[ ! -r "${DEPLOYED_SECRETS}/${secret}" ]]; then
    echo "error: ${DEPLOYED_SECRETS}/${secret} is missing or unreadable" >&2
    exit 1
  fi
done

# The Cloudflare Access identifiers are public identifiers rather than secrets,
# but they belong to the deployment rather than to this repository, so they are
# read out of the running container instead of being written down here.
DEPLOYED_CONFIG="$(mktemp)"
trap 'rm -f "${DEPLOYED_CONFIG}"' EXIT

if ! docker cp "${CONTAINER}:/etc/domestique/config.toml" "${DEPLOYED_CONFIG}" >/dev/null 2>&1; then
  echo "error: cannot read /etc/domestique/config.toml from ${CONTAINER}; the deployment must mount its configuration there" >&2
  exit 1
fi

cloudflare_identifier() {
  awk -v key="$1" '
    /^\[/ { section = $0; next }
    section == "[access.cloudflare]" && $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
      sub(/^[^=]*=[[:space:]]*/, "")
      gsub(/^["'"'"']|["'"'"']$/, "")
      print
      exit
    }
  ' "${DEPLOYED_CONFIG}"
}

CF_TEAM_DOMAIN="$(cloudflare_identifier team_domain)"
CF_APPLICATION_AUD="$(cloudflare_identifier application_aud)"
CF_ALLOWED_EMAIL="$(cloudflare_identifier allowed_email)"

missing=()
[[ -n "${CF_TEAM_DOMAIN}" ]] || missing+=("team_domain")
[[ -n "${CF_APPLICATION_AUD}" ]] || missing+=("application_aud")
[[ -n "${CF_ALLOWED_EMAIL}" ]] || missing+=("allowed_email")

if ((${#missing[@]} > 0)); then
  echo "error: the deployed configuration has no access.cloudflare ${missing[*]}; the deployment must be gated by Cloudflare Access before development can mirror it" >&2
  exit 1
fi

mkdir -p "${DEV_SECRETS}"

# Snapshot the deployed state. The write-ahead log is copied too so the snapshot
# includes committed transactions that have not yet been checkpointed; the
# shared-memory file is intentionally skipped because SQLite rebuilds it.
rm -f "${DEV_DIR}/state.db" "${DEV_DIR}/state.db-wal" "${DEV_DIR}/state.db-shm"
docker cp "${CONTAINER}:/var/lib/domestique/state.db" "${DEV_DIR}/state.db"
docker cp "${CONTAINER}:/var/lib/domestique/state.db-wal" "${DEV_DIR}/state.db-wal" 2>/dev/null || true
chmod 600 "${DEV_DIR}/state.db"

# A placeholder key: 32 zero bytes. It is deliberately not the deployed key, so
# the stored Wahoo refresh tokens stay undecryptable in development.
printf 'A%.0s' $(seq 43) > "${DEV_SECRETS}/state_encryption_key"
printf 'development-placeholder' > "${DEV_SECRETS}/wahoo_client_secret"
printf 'development-placeholder' > "${DEV_SECRETS}/pushover_application_token"
printf 'development-placeholder' > "${DEV_SECRETS}/pushover_user_key"
chmod 600 "${DEV_SECRETS}"/*

cat > "${DEV_DIR}/config.toml" <<EOF
# Generated by dev/setup.sh. Do not edit by hand; re-run the script instead.
# This configuration reads real VeloPlanner data and cannot reach Wahoo.

[http]
listen_address = ":8081"
# The readiness listener defaults to :8081, which the snapshot service serves on,
# and the two must never be the same port.
readiness_address = ":8083"

[access.cloudflare]
# The deployed Access application, so the identity gate behaves exactly as it
# does in production.
team_domain = "${CF_TEAM_DOMAIN}"
application_aud = "${CF_APPLICATION_AUD}"
allowed_email = "${CF_ALLOWED_EMAIL}"

[state]
database_path = "${DEV_DIR}/state.db"
encryption_key_file = "${DEV_SECRETS}/state_encryption_key"

[veloplanner]
base_url = "https://veloplanner.com"
email_file = "${DEPLOYED_SECRETS}/veloplanner_email"
password_file = "${DEPLOYED_SECRETS}/veloplanner_password"

[wahoo]
# Unroutable on purpose: development must never reach the real Wahoo API.
api_base_url = "https://127.0.0.1:9"
oauth_base_url = "https://127.0.0.1:9"
client_id = "development-placeholder"
client_secret_file = "${DEV_SECRETS}/wahoo_client_secret"
redirect_url = "https://127.0.0.1:9/oauth/wahoo/callback"

[[wahoo.targets]]
id = "rider-a"

[[wahoo.targets]]
id = "rider-b"

[sync]
# A year out, so nothing synchronises unless you ask for it explicitly.
initial_delay = "8760h"

[notifications.pushover]
application_token_file = "${DEV_SECRETS}/pushover_application_token"
user_key_file = "${DEV_SECRETS}/pushover_user_key"
EOF

stages=$(sqlite3 "${DEV_DIR}/state.db" "SELECT COUNT(*) FROM stage_geometry;" 2>/dev/null || echo "?")
echo "Snapshot ready: ${DEV_DIR}/state.db (${stages} cached stage geometries)"
echo "Start the API with 'mise run dev-api', then the UI with 'mise run ui-dev'."
