#!/usr/bin/env bash
#
# Prepares a local development environment that shows real route data.
#
# It snapshots the deployed SQLite state into .local/dev and writes a
# development configuration beside it. Nothing here is tracked by Git.
#
# Safety model — the development service may read VeloPlanner, but must never
# reach Wahoo:
#
#   * The snapshot is a copy. Writes during development cannot affect the
#     deployed database, and the two services never share a SQLite file.
#   * The state encryption key is a deliberate placeholder, so the stored Wahoo
#     refresh tokens cannot be decrypted. Synchronisation therefore fails at the
#     state step, which happens *before* any Wahoo request is attempted.
#   * The settings the snapshot carries are the deployed ones, so they are
#     rewritten in the copy: the Wahoo endpoints are pointed at an unroutable
#     address, and scheduled synchronisation is pushed a year out so a run only
#     ever happens when you ask for one with POST /v1/sync.
#   * Every stored credential is deleted from the copy. They are encrypted under
#     the deployed key, which this environment does not have, so they could not
#     be used here in any case; deleting them means a development service that
#     reaches an upstream reaches it as nobody.
#
set -euo pipefail

CONTAINER="${DOMESTIQUE_CONTAINER:-domestique-domestique-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV_DIR="${ROOT}/.local/dev"
DEV_SECRETS="${DEV_DIR}/secrets"
DEPLOYED_SECRETS="${ROOT}/.local/run/secrets"

if ! docker inspect "${CONTAINER}" >/dev/null 2>&1; then
  echo "error: container ${CONTAINER} not found; start the deployment first" >&2
  exit 1
fi

# The snapshot is only safe once it has been rewritten, and that needs sqlite3.
if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "error: sqlite3 is required to make the snapshot safe for development" >&2
  exit 1
fi

# The development service never reaches the sign-in provider: it mints a session
# row directly, below, with cross-subject rights, so every admin-only surface is
# reachable locally regardless of the operator's own Auth0 role.
DEV_SUBJECT="${DOMESTIQUE_DEV_SUBJECT:-}"
if [[ -z "${DEV_SUBJECT}" ]]; then
  read -r -p "Auth0 subject (sub claim) to sign in as: " DEV_SUBJECT
fi
if [[ -z "${DEV_SUBJECT}" ]]; then
  echo "error: a subject is required; set DOMESTIQUE_DEV_SUBJECT or answer the prompt" >&2
  exit 1
fi

mkdir -p "${DEV_SECRETS}"

# Snapshot the deployed state. The write-ahead log is copied too so the snapshot
# includes committed transactions that have not yet been checkpointed; the
# shared-memory file is intentionally skipped because SQLite rebuilds it.
rm -f "${DEV_DIR}/state.db" "${DEV_DIR}/state.db-wal" "${DEV_DIR}/state.db-shm"
docker cp "${CONTAINER}:/var/lib/domestique/state.db" "${DEV_DIR}/state.db"
docker cp "${CONTAINER}:/var/lib/domestique/state.db-wal" "${DEV_DIR}/state.db-wal" 2>/dev/null || true
chmod 600 "${DEV_DIR}/state.db"

# The snapshot carries the deployed settings, which name the real Wahoo API and
# schedule a run a minute after start. Rewrite both before the service ever
# reads this file.
sqlite3 "${DEV_DIR}/state.db" <<'SQL'
UPDATE runtime_settings SET
  wahoo_api_base_url = 'https://127.0.0.1:9',
  wahoo_oauth_base_url = 'https://127.0.0.1:9',
  wahoo_client_id = 'development-placeholder',
  sync_initial_delay_seconds = 31536000;
DELETE FROM runtime_secret;
SQL

# A placeholder key: 32 zero bytes. It is deliberately not the deployed key, so
# the stored Wahoo refresh tokens stay undecryptable in development.
printf 'A%.0s' $(seq 43) > "${DEV_SECRETS}/state_encryption_key"
# A placeholder too: the development service never exchanges a code, because the
# session it serves is minted straight into the snapshot below.
printf 'development-placeholder' > "${DEV_SECRETS}/auth0_client_secret"
chmod 600 "${DEV_SECRETS}"/*

cat > "${DEV_DIR}/config.toml" <<EOF
# Generated by dev/setup.sh. Do not edit by hand; re-run the script instead.
# Everything else is a setting, held in the snapshot and edited in the browser.

[http]
listen_address = ":8081"
# The readiness listener defaults to :8081, which the snapshot service serves on,
# and the two must never be the same port.
readiness_address = ":8083"
# Unroutable on purpose, and the same address the Wahoo endpoints are pointed
# at below: this is the origin an authorization comes back to.
browser_origin_url = "https://127.0.0.1:9"

[auth.auth0]
# Unroutable on purpose: development never signs in through the provider, it
# reads the session minted into the snapshot below.
domain = "127.0.0.1:9"
client_id = "development-placeholder"
client_secret_file = "${DEV_SECRETS}/auth0_client_secret"

[state]
database_path = "${DEV_DIR}/state.db"
encryption_key_file = "${DEV_SECRETS}/state_encryption_key"
EOF

# The gate admits a browser session and nothing else, so development needs one
# before the UI can load. Minted straight into the snapshot; the raw token is
# printed once, here, and stored nowhere.
DEV_SESSION="$(
  CGO_ENABLED=0 "${GO:-go}" run "${ROOT}/dev/session" \
    -database "${DEV_DIR}/state.db" -subject "${DEV_SUBJECT}" -admin
)"

stages=$(sqlite3 "${DEV_DIR}/state.db" "SELECT COUNT(*) FROM stage_geometry;" 2>/dev/null || echo "?")
echo "Snapshot ready: ${DEV_DIR}/state.db (${stages} cached stage geometries)"
echo "Start the API with 'mise run dev-api', then the UI with:"
echo
echo "  export DOMESTIQUE_DEV_SESSION=${DEV_SESSION}"
echo "  mise run ui-dev"
echo
echo "To synchronise from a library, enter its credentials on the settings page;"
echo "the deployed ones are in ${DEPLOYED_SECRETS}."
