//go:build go1.22

// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AcceptedStatus.
const (
	AcceptedStatusAccepted AcceptedStatus = "accepted"
)

// Valid indicates whether the value is a known member of the AcceptedStatus enum.
func (e AcceptedStatus) Valid() bool {
	switch e {
	case AcceptedStatusAccepted:
		return true
	default:
		return false
	}
}

// Defines values for GeoJSONFeatureType.
const (
	Feature GeoJSONFeatureType = "Feature"
)

// Valid indicates whether the value is a known member of the GeoJSONFeatureType enum.
func (e GeoJSONFeatureType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for GeoJSONLineStringType.
const (
	LineString GeoJSONLineStringType = "LineString"
)

// Valid indicates whether the value is a known member of the GeoJSONLineStringType enum.
func (e GeoJSONLineStringType) Valid() bool {
	switch e {
	case LineString:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready ReadinessStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for SurfaceRangeKind.
const (
	Asphalt   SurfaceRangeKind = "asphalt"
	Compacted SurfaceRangeKind = "compacted"
	Gravel    SurfaceRangeKind = "gravel"
	Ground    SurfaceRangeKind = "ground"
	Paving    SurfaceRangeKind = "paving"
	Unknown   SurfaceRangeKind = "unknown"
)

// Valid indicates whether the value is a known member of the SurfaceRangeKind enum.
func (e SurfaceRangeKind) Valid() bool {
	switch e {
	case Asphalt:
		return true
	case Compacted:
		return true
	case Gravel:
		return true
	case Ground:
		return true
	case Paving:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SyncActivePhase.
const (
	SyncActivePhaseSource  SyncActivePhase = "source"
	SyncActivePhaseTargets SyncActivePhase = "targets"
)

// Valid indicates whether the value is a known member of the SyncActivePhase enum.
func (e SyncActivePhase) Valid() bool {
	switch e {
	case SyncActivePhaseSource:
		return true
	case SyncActivePhaseTargets:
		return true
	default:
		return false
	}
}

// Defines values for SyncRunPhase.
const (
	SyncRunPhaseSource  SyncRunPhase = "source"
	SyncRunPhaseTargets SyncRunPhase = "targets"
)

// Valid indicates whether the value is a known member of the SyncRunPhase enum.
func (e SyncRunPhase) Valid() bool {
	switch e {
	case SyncRunPhaseSource:
		return true
	case SyncRunPhaseTargets:
		return true
	default:
		return false
	}
}

// Defines values for TargetStatusConvergence.
const (
	TargetStatusConvergenceCurrent      TargetStatusConvergence = "current"
	TargetStatusConvergenceFailed       TargetStatusConvergence = "failed"
	TargetStatusConvergenceLagging      TargetStatusConvergence = "lagging"
	TargetStatusConvergenceUnauthorized TargetStatusConvergence = "unauthorized"
)

// Valid indicates whether the value is a known member of the TargetStatusConvergence enum.
func (e TargetStatusConvergence) Valid() bool {
	switch e {
	case TargetStatusConvergenceCurrent:
		return true
	case TargetStatusConvergenceFailed:
		return true
	case TargetStatusConvergenceLagging:
		return true
	case TargetStatusConvergenceUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyReason.
const (
	StateIncomplete UnreadyReason = "state_incomplete"
	StateUnreadable UnreadyReason = "state_unreadable"
)

// Valid indicates whether the value is a known member of the UnreadyReason enum.
func (e UnreadyReason) Valid() bool {
	switch e {
	case StateIncomplete:
		return true
	case StateUnreadable:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyStatus.
const (
	UnreadyStatusUnready UnreadyStatus = "unready"
)

// Valid indicates whether the value is a known member of the UnreadyStatus enum.
func (e UnreadyStatus) Valid() bool {
	switch e {
	case UnreadyStatusUnready:
		return true
	default:
		return false
	}
}

// Accepted defines model for Accepted.
type Accepted struct {
	Status AcceptedStatus `json:"status"`
}

// AcceptedStatus defines model for Accepted.Status.
type AcceptedStatus string

// BrowserBasemap defines model for BrowserBasemap.
type BrowserBasemap struct {
	DarkCartography *bool   `json:"darkCartography,omitempty"`
	Name            string  `json:"name"`
	StyleUrl        string  `json:"styleUrl"`
	StyleUrlDark    *string `json:"styleUrlDark,omitempty"`
}

// Build defines model for Build.
type Build struct {
	ImageDigest *string `json:"imageDigest,omitempty"`
	Revision    string  `json:"revision"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// GeoJSONFeature defines model for GeoJSONFeature.
type GeoJSONFeature struct {
	Bbox       []float32          `json:"bbox"`
	Geometry   GeoJSONLineString  `json:"geometry"`
	Properties GeoJSONProperties  `json:"properties"`
	Type       GeoJSONFeatureType `json:"type"`
}

// GeoJSONFeatureType defines model for GeoJSONFeature.Type.
type GeoJSONFeatureType string

// GeoJSONLineString defines model for GeoJSONLineString.
type GeoJSONLineString struct {
	Coordinates [][]float32           `json:"coordinates"`
	Type        GeoJSONLineStringType `json:"type"`
}

// GeoJSONLineStringType defines model for GeoJSONLineString.Type.
type GeoJSONLineStringType string

// GeoJSONProperties defines model for GeoJSONProperties.
type GeoJSONProperties struct {
	AscentMetres       float32    `json:"ascentMetres"`
	CumulativeSeconds  *[]float32 `json:"cumulativeSeconds,omitempty"`
	DistanceMetres     float32    `json:"distanceMetres"`
	MaxGradientPercent float32    `json:"maxGradientPercent"`
	PointCount         int        `json:"pointCount"`
	Provider           string     `json:"provider"`
	RouteId            int64      `json:"routeId"`
	RouteName          string     `json:"routeName"`
	StageName          string     `json:"stageName"`
	StageOrder         int        `json:"stageOrder"`
	Surface            *struct {
		MatchedMetres float32        `json:"matchedMetres"`
		Ranges        []SurfaceRange `json:"ranges"`
	} `json:"surface,omitempty"`
	Title string `json:"title"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Manifest defines model for Manifest.
type Manifest struct {
	Display string `json:"display"`
	Icons   []struct {
		Sizes string `json:"sizes"`
		Src   string `json:"src"`
		Type  string `json:"type"`
	} `json:"icons"`
	Name      string `json:"name"`
	ShortName string `json:"short_name"`
	StartUrl  string `json:"start_url"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Route defines model for Route.
type Route struct {
	AscentMetres       float32          `json:"ascentMetres"`
	ContentHash        string           `json:"contentHash"`
	DistanceMetres     float32          `json:"distanceMetres"`
	MaxGradientPercent float32          `json:"maxGradientPercent"`
	MovingSeconds      *float32         `json:"movingSeconds,omitempty"`
	PointCount         int              `json:"pointCount"`
	Provider           string           `json:"provider"`
	RouteId            int64            `json:"routeId"`
	RouteName          string           `json:"routeName"`
	SourceRevision     string           `json:"sourceRevision"`
	StageName          string           `json:"stageName"`
	StageOrder         int              `json:"stageOrder"`
	Title              string           `json:"title"`
	Validation         *RouteValidation `json:"validation,omitempty"`
}

// RouteList defines model for RouteList.
type RouteList struct {
	Stages []Route `json:"stages"`
}

// RouteValidation defines model for RouteValidation.
type RouteValidation struct {
	BiasPercent    float32 `json:"biasPercent"`
	EvaluatedRides int     `json:"evaluatedRides"`
	MaePercent     float32 `json:"maePercent"`
	P90Percent     float32 `json:"p90Percent"`
}

// SourceBaseUrls defines model for SourceBaseUrls.
type SourceBaseUrls struct {
	Komoot      *string `json:"komoot,omitempty"`
	Veloplanner *string `json:"veloplanner,omitempty"`
}

// Status defines model for Status.
type Status struct {
	Build     *Build         `json:"build,omitempty"`
	Converged bool           `json:"converged"`
	Ready     bool           `json:"ready"`
	Sync      SyncStatus     `json:"sync"`
	Targets   []TargetStatus `json:"targets"`
}

// SurfaceCoverage defines model for SurfaceCoverage.
type SurfaceCoverage struct {
	BuiltAt    *time.Time `json:"builtAt,omitempty"`
	Classified int        `json:"classified"`
	Generation *string    `json:"generation,omitempty"`
	Incomplete int        `json:"incomplete"`
	Total      int        `json:"total"`
}

// SurfaceRange defines model for SurfaceRange.
type SurfaceRange struct {
	EndIndex   int              `json:"endIndex"`
	Kind       SurfaceRangeKind `json:"kind"`
	StartIndex int              `json:"startIndex"`
}

// SurfaceRangeKind defines model for SurfaceRange.Kind.
type SurfaceRangeKind string

// SyncActive defines model for SyncActive.
type SyncActive struct {
	Phase    *SyncActivePhase `json:"phase,omitempty"`
	Stages   TargetStages     `json:"stages"`
	StartsAt *time.Time       `json:"startsAt,omitempty"`
	Targets  int              `json:"targets"`
}

// SyncActivePhase defines model for SyncActive.Phase.
type SyncActivePhase string

// SyncPhaseRun defines model for SyncPhaseRun.
type SyncPhaseRun struct {
	Created         int       `json:"created"`
	Deleted         int       `json:"deleted"`
	LastCompletedAt time.Time `json:"lastCompletedAt"`
	LastFailure     *string   `json:"lastFailure,omitempty"`
	LastResult      string    `json:"lastResult"`
	SourceStages    int       `json:"sourceStages"`
	Updated         int       `json:"updated"`
}

// SyncPhases defines model for SyncPhases.
type SyncPhases struct {
	Source  *SyncPhaseRun `json:"source,omitempty"`
	Targets *SyncPhaseRun `json:"targets,omitempty"`
}

// SyncRun defines model for SyncRun.
type SyncRun struct {
	CompletedAt  time.Time    `json:"completedAt"`
	Created      int          `json:"created"`
	Deleted      int          `json:"deleted"`
	Failure      *string      `json:"failure,omitempty"`
	Phase        SyncRunPhase `json:"phase"`
	Reference    string       `json:"reference"`
	Result       string       `json:"result"`
	SourceStages int          `json:"sourceStages"`
	Updated      int          `json:"updated"`
}

// SyncRunPhase defines model for SyncRun.Phase.
type SyncRunPhase string

// SyncRunPage defines model for SyncRunPage.
type SyncRunPage struct {
	Next *string   `json:"next,omitempty"`
	Runs []SyncRun `json:"runs"`
}

// SyncSchedule defines model for SyncSchedule.
type SyncSchedule struct {
	Source  bool `json:"source"`
	Targets bool `json:"targets"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	Active           *SyncActive       `json:"active,omitempty"`
	Created          int               `json:"created"`
	Deleted          int               `json:"deleted"`
	LastCompletedAt  *time.Time        `json:"lastCompletedAt,omitempty"`
	LastResult       *string           `json:"lastResult,omitempty"`
	Phases           SyncPhases        `json:"phases"`
	Schedule         SyncSchedule      `json:"schedule"`
	SourceStages     int               `json:"sourceStages"`
	State            string            `json:"state"`
	Surface          SurfaceCoverage   `json:"surface"`
	TrustedInventory *TrustedInventory `json:"trustedInventory,omitempty"`
	Updated          int               `json:"updated"`
	WahooRateLimit   *WahooRateLimit   `json:"wahooRateLimit,omitempty"`
}

// TargetRun defines model for TargetRun.
type TargetRun struct {
	CompletedAt time.Time `json:"completedAt"`
	Failure     *string   `json:"failure,omitempty"`
	Result      string    `json:"result"`
}

// TargetStages defines model for TargetStages.
type TargetStages struct {
	Current int `json:"current"`
	Pending int `json:"pending"`
}

// TargetStatus defines model for TargetStatus.
type TargetStatus struct {
	Authorisation string                  `json:"authorisation"`
	Convergence   TargetStatusConvergence `json:"convergence"`
	Id            string                  `json:"id"`
	LastRun       *TargetRun              `json:"lastRun,omitempty"`
	Stages        TargetStages            `json:"stages"`
}

// TargetStatusConvergence defines model for TargetStatus.Convergence.
type TargetStatusConvergence string

// TrustedInventory defines model for TrustedInventory.
type TrustedInventory struct {
	AgeSeconds    int        `json:"ageSeconds"`
	Fresh         bool       `json:"fresh"`
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	MaxAgeSeconds int        `json:"maxAgeSeconds"`
}

// Unready defines model for Unready.
type Unready struct {
	Reason UnreadyReason `json:"reason"`
	Status UnreadyStatus `json:"status"`
}

// UnreadyReason defines model for Unready.Reason.
type UnreadyReason string

// UnreadyStatus defines model for Unready.Status.
type UnreadyStatus string

// WahooRateLimit defines model for WahooRateLimit.
type WahooRateLimit struct {
	Remaining int        `json:"remaining"`
	ResetsAt  *time.Time `json:"resetsAt,omitempty"`
}

// WeatherForecast defines model for WeatherForecast.
type WeatherForecast struct {
	Points []WeatherPoint `json:"points"`
}

// WeatherPoint defines model for WeatherPoint.
type WeatherPoint struct {
	ApparentTemperatureCelsius      float32   `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres        float32   `json:"precipitationMillimetres"`
	PrecipitationProbabilityPercent float32   `json:"precipitationProbabilityPercent"`
	TemperatureCelsius              float32   `json:"temperatureCelsius"`
	Time                            time.Time `json:"time"`
	WeatherCode                     int       `json:"weatherCode"`
	WindDirectionDegrees            float32   `json:"windDirectionDegrees"`
	WindSpeedKmh                    float32   `json:"windSpeedKmh"`
}

// WebUIConfig defines model for WebUIConfig.
type WebUIConfig struct {
	Basemaps       []BrowserBasemap `json:"basemaps"`
	SourceBaseUrls *SourceBaseUrls  `json:"sourceBaseUrls,omitempty"`
}

// Origin defines model for Origin.
type Origin = string

// Provider defines model for Provider.
type Provider = string

// RouteId defines model for RouteId.
type RouteId = int64

// Stage defines model for Stage.
type Stage = int

// Target defines model for Target.
type Target = string

// AuthorizationFailed defines model for AuthorizationFailed.
type AuthorizationFailed = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ProviderUnavailable defines model for ProviderUnavailable.
type ProviderUnavailable = Error

// SyncInProgress defines model for SyncInProgress.
type SyncInProgress = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unavailable defines model for Unavailable.
type Unavailable = Error

// CompleteOAuthParams defines parameters for CompleteOAuth.
type CompleteOAuthParams struct {
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
}

// ReprocessRouteParams defines parameters for ReprocessRoute.
type ReprocessRouteParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// RedirectLegacyReprocessParams defines parameters for RedirectLegacyReprocess.
type RedirectLegacyReprocessParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// TriggerSyncParams defines parameters for TriggerSync.
type TriggerSyncParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// GetSyncRunsParams defines parameters for GetSyncRuns.
type GetSyncRunsParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// SetSyncScheduleParams defines parameters for SetSyncSchedule.
type SetSyncScheduleParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// TriggerSourceSyncParams defines parameters for TriggerSourceSync.
type TriggerSourceSyncParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// TriggerSurfaceSyncParams defines parameters for TriggerSurfaceSync.
type TriggerSurfaceSyncParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// TriggerTargetsSyncParams defines parameters for TriggerTargetsSync.
type TriggerTargetsSyncParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// TriggerTargetSyncParams defines parameters for TriggerTargetSync.
type TriggerTargetSyncParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// ClearTargetParams defines parameters for ClearTarget.
type ClearTargetParams struct {
	// Origin Exact browser origin configured for this service.
	Origin Origin `json:"Origin"`
}

// GetWeatherParams defines parameters for GetWeather.
type GetWeatherParams struct {
	Point []string `form:"point" json:"point"`
}

// SetSyncScheduleJSONRequestBody defines body for SetSyncSchedule for application/json ContentType.
type SetSyncScheduleJSONRequestBody = SyncSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	GetIndex(w http.ResponseWriter, r *http.Request)

	// (GET /assets/{asset})
	GetAsset(w http.ResponseWriter, r *http.Request, asset string)

	// (GET /favicon.svg)
	GetFavicon(w http.ResponseWriter, r *http.Request)

	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /icon-256.png)
	GetIcon256(w http.ResponseWriter, r *http.Request)

	// (GET /icon-512.png)
	GetIcon512(w http.ResponseWriter, r *http.Request)

	// (GET /manifest.webmanifest)
	GetManifest(w http.ResponseWriter, r *http.Request)

	// (GET /oauth/wahoo/callback)
	CompleteOAuth(w http.ResponseWriter, r *http.Request, params CompleteOAuthParams)

	// (GET /oauth/wahoo/start/{target})
	StartOAuth(w http.ResponseWriter, r *http.Request, target Target)

	// (GET /routes/{provider}/{routeId}/{stage})
	GetRoutePage(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (GET /routes/{routeId}/{stage})
	RedirectLegacyRoutePage(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (GET /settings)
	GetSettingsPage(w http.ResponseWriter, r *http.Request)

	// (GET /sync)
	GetSyncPage(w http.ResponseWriter, r *http.Request)

	// (GET /v1/providers/{provider}/routes/{routeId}/stages/{stage})
	GetRoute(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (GET /v1/providers/{provider}/routes/{routeId}/stages/{stage}/geometry)
	GetRouteGeometry(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (POST /v1/providers/{provider}/routes/{routeId}/stages/{stage}/reprocess)
	ReprocessRoute(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage, params ReprocessRouteParams)

	// (GET /v1/routes)
	GetRoutes(w http.ResponseWriter, r *http.Request)

	// (GET /v1/routes/{routeId}/stages/{stage})
	RedirectLegacyRoute(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (GET /v1/routes/{routeId}/stages/{stage}/geometry)
	RedirectLegacyGeometry(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (POST /v1/routes/{routeId}/stages/{stage}/reprocess)
	RedirectLegacyReprocess(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage, params RedirectLegacyReprocessParams)

	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync)
	TriggerSync(w http.ResponseWriter, r *http.Request, params TriggerSyncParams)

	// (GET /v1/sync/runs)
	GetSyncRuns(w http.ResponseWriter, r *http.Request, params GetSyncRunsParams)

	// (PUT /v1/sync/schedule)
	SetSyncSchedule(w http.ResponseWriter, r *http.Request, params SetSyncScheduleParams)

	// (POST /v1/sync/source)
	TriggerSourceSync(w http.ResponseWriter, r *http.Request, params TriggerSourceSyncParams)

	// (POST /v1/sync/surface)
	TriggerSurfaceSync(w http.ResponseWriter, r *http.Request, params TriggerSurfaceSyncParams)

	// (POST /v1/sync/targets)
	TriggerTargetsSync(w http.ResponseWriter, r *http.Request, params TriggerTargetsSyncParams)

	// (POST /v1/sync/targets/{target})
	TriggerTargetSync(w http.ResponseWriter, r *http.Request, target Target, params TriggerTargetSyncParams)

	// (POST /v1/targets/{target}/clear)
	ClearTarget(w http.ResponseWriter, r *http.Request, target Target, params ClearTargetParams)

	// (GET /v1/weather)
	GetWeather(w http.ResponseWriter, r *http.Request, params GetWeatherParams)

	// (GET /v1/webui/config)
	GetWebUIConfig(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset" -------------
	var asset string

	err = runtime.BindStyledParameterWithOptions("simple", "asset", r.PathValue("asset"), &asset, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, asset)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavicon operation middleware
func (siw *ServerInterfaceWrapper) GetFavicon(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavicon(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIcon256 operation middleware
func (siw *ServerInterfaceWrapper) GetIcon256(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIcon256(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIcon512 operation middleware
func (siw *ServerInterfaceWrapper) GetIcon512(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIcon512(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManifest operation middleware
func (siw *ServerInterfaceWrapper) GetManifest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManifest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteOAuth operation middleware
func (siw *ServerInterfaceWrapper) CompleteOAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteOAuthParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteOAuth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartOAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOAuth(w, r, target)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoutePage operation middleware
func (siw *ServerInterfaceWrapper) GetRoutePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoutePage(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyRoutePage operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyRoutePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyRoutePage(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettingsPage operation middleware
func (siw *ServerInterfaceWrapper) GetSettingsPage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettingsPage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncPage operation middleware
func (siw *ServerInterfaceWrapper) GetSyncPage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncPage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoute operation middleware
func (siw *ServerInterfaceWrapper) GetRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoute(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRouteGeometry operation middleware
func (siw *ServerInterfaceWrapper) GetRouteGeometry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRouteGeometry(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReprocessRoute operation middleware
func (siw *ServerInterfaceWrapper) ReprocessRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReprocessRouteParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReprocessRoute(w, r, provider, routeId, stage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoutes operation middleware
func (siw *ServerInterfaceWrapper) GetRoutes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoutes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyRoute operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyRoute(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyGeometry operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyGeometry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyGeometry(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyReprocess operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyReprocess(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RedirectLegacyReprocessParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyReprocess(w, r, routeId, stage, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerSyncParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncRuns operation middleware
func (siw *ServerInterfaceWrapper) GetSyncRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSyncRunsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSyncSchedule operation middleware
func (siw *ServerInterfaceWrapper) SetSyncSchedule(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SetSyncScheduleParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSyncSchedule(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSourceSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSourceSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerSourceSyncParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSourceSync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSurfaceSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSurfaceSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerSurfaceSyncParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSurfaceSync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTargetsSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerTargetsSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerTargetsSyncParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTargetsSync(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTargetSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerTargetSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params TriggerTargetSyncParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTargetSync(w, r, target, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearTarget operation middleware
func (siw *ServerInterfaceWrapper) ClearTarget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ClearTargetParams

	headers := r.Header

	// ------------- Required header parameter "Origin" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Origin")]; found {
		var Origin Origin
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Origin", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Origin", valueList[0], &Origin, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Origin", Err: err})
			return
		}

		params.Origin = Origin

	} else {
		err := fmt.Errorf("Header parameter Origin is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Origin", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearTarget(w, r, target, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWeather operation middleware
func (siw *ServerInterfaceWrapper) GetWeather(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWeatherParams

	// ------------- Required query parameter "point" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "point", r.URL.Query(), &params.Point, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "point"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "point", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWeather(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebUIConfig operation middleware
func (siw *ServerInterfaceWrapper) GetWebUIConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebUIConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync", wrapper.TriggerSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/source", wrapper.TriggerSourceSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/targets", wrapper.TriggerTargetsSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/targets/{target}", wrapper.TriggerTargetSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/targets/{target}/clear", wrapper.ClearTarget)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/surface", wrapper.TriggerSurfaceSync)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/sync/schedule", wrapper.SetSyncSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/sync/runs", wrapper.GetSyncRuns)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes", wrapper.GetRoutes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}", wrapper.GetRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}/geometry", wrapper.GetRouteGeometry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}/reprocess", wrapper.ReprocessRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}", wrapper.RedirectLegacyRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}/geometry", wrapper.RedirectLegacyGeometry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}/reprocess", wrapper.RedirectLegacyReprocess)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/webui/config", wrapper.GetWebUIConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/weather", wrapper.GetWeather)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/oauth/wahoo/start/{target}", wrapper.StartOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/oauth/wahoo/callback", wrapper.CompleteOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/assets/{asset}", wrapper.GetAsset)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/favicon.svg", wrapper.GetFavicon)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/icon-256.png", wrapper.GetIcon256)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/icon-512.png", wrapper.GetIcon512)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/manifest.webmanifest", wrapper.GetManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/{$}", wrapper.GetIndex)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/routes/{provider}/{routeId}/{stage}", wrapper.GetRoutePage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/routes/{routeId}/{stage}", wrapper.RedirectLegacyRoutePage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sync", wrapper.GetSyncPage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/settings", wrapper.GetSettingsPage)

	return m
}
