//go:build go1.22

// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AcceptedStatus.
const (
	AcceptedStatusAccepted AcceptedStatus = "accepted"
)

// Valid indicates whether the value is a known member of the AcceptedStatus enum.
func (e AcceptedStatus) Valid() bool {
	switch e {
	case AcceptedStatusAccepted:
		return true
	default:
		return false
	}
}

// Defines values for GeoJSONFeatureType.
const (
	Feature GeoJSONFeatureType = "Feature"
)

// Valid indicates whether the value is a known member of the GeoJSONFeatureType enum.
func (e GeoJSONFeatureType) Valid() bool {
	switch e {
	case Feature:
		return true
	default:
		return false
	}
}

// Defines values for GeoJSONLineStringType.
const (
	LineString GeoJSONLineStringType = "LineString"
)

// Valid indicates whether the value is a known member of the GeoJSONLineStringType enum.
func (e GeoJSONLineStringType) Valid() bool {
	switch e {
	case LineString:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready ReadinessStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for SurfaceRangeKind.
const (
	Asphalt   SurfaceRangeKind = "asphalt"
	Compacted SurfaceRangeKind = "compacted"
	Gravel    SurfaceRangeKind = "gravel"
	Ground    SurfaceRangeKind = "ground"
	Paving    SurfaceRangeKind = "paving"
	Unknown   SurfaceRangeKind = "unknown"
)

// Valid indicates whether the value is a known member of the SurfaceRangeKind enum.
func (e SurfaceRangeKind) Valid() bool {
	switch e {
	case Asphalt:
		return true
	case Compacted:
		return true
	case Gravel:
		return true
	case Ground:
		return true
	case Paving:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SyncActivePhase.
const (
	SyncActivePhaseSource  SyncActivePhase = "source"
	SyncActivePhaseTargets SyncActivePhase = "targets"
)

// Valid indicates whether the value is a known member of the SyncActivePhase enum.
func (e SyncActivePhase) Valid() bool {
	switch e {
	case SyncActivePhaseSource:
		return true
	case SyncActivePhaseTargets:
		return true
	default:
		return false
	}
}

// Defines values for SyncRunPhase.
const (
	SyncRunPhaseSource  SyncRunPhase = "source"
	SyncRunPhaseTargets SyncRunPhase = "targets"
)

// Valid indicates whether the value is a known member of the SyncRunPhase enum.
func (e SyncRunPhase) Valid() bool {
	switch e {
	case SyncRunPhaseSource:
		return true
	case SyncRunPhaseTargets:
		return true
	default:
		return false
	}
}

// Defines values for TargetStatusConvergence.
const (
	TargetStatusConvergenceCurrent      TargetStatusConvergence = "current"
	TargetStatusConvergenceFailed       TargetStatusConvergence = "failed"
	TargetStatusConvergenceLagging      TargetStatusConvergence = "lagging"
	TargetStatusConvergenceUnauthorized TargetStatusConvergence = "unauthorized"
)

// Valid indicates whether the value is a known member of the TargetStatusConvergence enum.
func (e TargetStatusConvergence) Valid() bool {
	switch e {
	case TargetStatusConvergenceCurrent:
		return true
	case TargetStatusConvergenceFailed:
		return true
	case TargetStatusConvergenceLagging:
		return true
	case TargetStatusConvergenceUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyReason.
const (
	StateIncomplete UnreadyReason = "state_incomplete"
	StateUnreadable UnreadyReason = "state_unreadable"
)

// Valid indicates whether the value is a known member of the UnreadyReason enum.
func (e UnreadyReason) Valid() bool {
	switch e {
	case StateIncomplete:
		return true
	case StateUnreadable:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyStatus.
const (
	UnreadyStatusUnready UnreadyStatus = "unready"
)

// Valid indicates whether the value is a known member of the UnreadyStatus enum.
func (e UnreadyStatus) Valid() bool {
	switch e {
	case UnreadyStatusUnready:
		return true
	default:
		return false
	}
}

// Accepted defines model for Accepted.
type Accepted struct {
	Status AcceptedStatus `json:"status"`
}

// AcceptedStatus defines model for Accepted.Status.
type AcceptedStatus string

// BrowserBasemap defines model for BrowserBasemap.
type BrowserBasemap struct {
	DarkCartography *bool   `json:"darkCartography,omitempty"`
	Name            string  `json:"name"`
	StyleUrl        string  `json:"styleUrl"`
	StyleUrlDark    *string `json:"styleUrlDark,omitempty"`
}

// Build defines model for Build.
type Build struct {
	ImageDigest *string `json:"imageDigest,omitempty"`
	Revision    string  `json:"revision"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// GeoJSONFeature defines model for GeoJSONFeature.
type GeoJSONFeature struct {
	Bbox       []float64          `json:"bbox"`
	Geometry   GeoJSONLineString  `json:"geometry"`
	Properties GeoJSONProperties  `json:"properties"`
	Type       GeoJSONFeatureType `json:"type"`
}

// GeoJSONFeatureType defines model for GeoJSONFeature.Type.
type GeoJSONFeatureType string

// GeoJSONLineString defines model for GeoJSONLineString.
type GeoJSONLineString struct {
	Coordinates [][]float64           `json:"coordinates"`
	Type        GeoJSONLineStringType `json:"type"`
}

// GeoJSONLineStringType defines model for GeoJSONLineString.Type.
type GeoJSONLineStringType string

// GeoJSONProperties defines model for GeoJSONProperties.
type GeoJSONProperties struct {
	AscentMetres       float64    `json:"ascentMetres"`
	CumulativeSeconds  *[]float64 `json:"cumulativeSeconds,omitempty"`
	DistanceMetres     float64    `json:"distanceMetres"`
	MaxGradientPercent float64    `json:"maxGradientPercent"`
	PointCount         int        `json:"pointCount"`
	Provider           string     `json:"provider"`
	RouteId            int64      `json:"routeId"`
	RouteName          string     `json:"routeName"`
	StageName          string     `json:"stageName"`
	StageOrder         int        `json:"stageOrder"`
	Surface            *struct {
		MatchedMetres float64        `json:"matchedMetres"`
		Ranges        []SurfaceRange `json:"ranges"`
	} `json:"surface,omitempty"`
	Title string `json:"title"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Manifest defines model for Manifest.
type Manifest struct {
	Display string `json:"display"`
	Icons   []struct {
		Sizes string `json:"sizes"`
		Src   string `json:"src"`
		Type  string `json:"type"`
	} `json:"icons"`
	Name      string `json:"name"`
	ShortName string `json:"short_name"`
	StartUrl  string `json:"start_url"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Route defines model for Route.
type Route struct {
	AscentMetres       float64          `json:"ascentMetres"`
	ContentHash        string           `json:"contentHash"`
	DistanceMetres     float64          `json:"distanceMetres"`
	MaxGradientPercent float64          `json:"maxGradientPercent"`
	MovingSeconds      *float64         `json:"movingSeconds,omitempty"`
	PointCount         int              `json:"pointCount"`
	Provider           string           `json:"provider"`
	RouteId            int64            `json:"routeId"`
	RouteName          string           `json:"routeName"`
	SourceRevision     string           `json:"sourceRevision"`
	StageName          string           `json:"stageName"`
	StageOrder         int              `json:"stageOrder"`
	Title              string           `json:"title"`
	Validation         *RouteValidation `json:"validation,omitempty"`
}

// RouteList defines model for RouteList.
type RouteList struct {
	Stages []Route `json:"stages"`
}

// RouteValidation defines model for RouteValidation.
type RouteValidation struct {
	BiasPercent    float64 `json:"biasPercent"`
	EvaluatedRides int     `json:"evaluatedRides"`
	MaePercent     float64 `json:"maePercent"`
	P90Percent     float64 `json:"p90Percent"`
}

// SourceBaseUrls defines model for SourceBaseUrls.
type SourceBaseUrls struct {
	Komoot      *string `json:"komoot,omitempty"`
	Veloplanner *string `json:"veloplanner,omitempty"`
}

// Status defines model for Status.
type Status struct {
	Build     *Build         `json:"build,omitempty"`
	Converged bool           `json:"converged"`
	Ready     bool           `json:"ready"`
	Sync      SyncStatus     `json:"sync"`
	Targets   []TargetStatus `json:"targets"`
}

// SurfaceCoverage defines model for SurfaceCoverage.
type SurfaceCoverage struct {
	BuiltAt    *time.Time `json:"builtAt,omitempty"`
	Classified int        `json:"classified"`
	Generation *string    `json:"generation,omitempty"`
	Incomplete int        `json:"incomplete"`
	Total      int        `json:"total"`
}

// SurfaceRange defines model for SurfaceRange.
type SurfaceRange struct {
	EndIndex   int              `json:"endIndex"`
	Kind       SurfaceRangeKind `json:"kind"`
	StartIndex int              `json:"startIndex"`
}

// SurfaceRangeKind defines model for SurfaceRange.Kind.
type SurfaceRangeKind string

// SyncActive defines model for SyncActive.
type SyncActive struct {
	Phase    *SyncActivePhase `json:"phase,omitempty"`
	Stages   TargetStages     `json:"stages"`
	StartsAt *time.Time       `json:"startsAt,omitempty"`
	Targets  int              `json:"targets"`
}

// SyncActivePhase defines model for SyncActive.Phase.
type SyncActivePhase string

// SyncPhaseRun defines model for SyncPhaseRun.
type SyncPhaseRun struct {
	Created         int       `json:"created"`
	Deleted         int       `json:"deleted"`
	LastCompletedAt time.Time `json:"lastCompletedAt"`
	LastFailure     *string   `json:"lastFailure,omitempty"`
	LastResult      string    `json:"lastResult"`
	SourceStages    int       `json:"sourceStages"`
	Updated         int       `json:"updated"`
}

// SyncPhases defines model for SyncPhases.
type SyncPhases struct {
	Source  *SyncPhaseRun `json:"source,omitempty"`
	Targets *SyncPhaseRun `json:"targets,omitempty"`
}

// SyncRun defines model for SyncRun.
type SyncRun struct {
	CompletedAt  time.Time    `json:"completedAt"`
	Created      int          `json:"created"`
	Deleted      int          `json:"deleted"`
	Failure      *string      `json:"failure,omitempty"`
	Phase        SyncRunPhase `json:"phase"`
	Reference    string       `json:"reference"`
	Result       string       `json:"result"`
	SourceStages int          `json:"sourceStages"`
	Updated      int          `json:"updated"`
}

// SyncRunPhase defines model for SyncRun.Phase.
type SyncRunPhase string

// SyncRunPage defines model for SyncRunPage.
type SyncRunPage struct {
	Next *string   `json:"next,omitempty"`
	Runs []SyncRun `json:"runs"`
}

// SyncSchedule defines model for SyncSchedule.
type SyncSchedule struct {
	Source  bool `json:"source"`
	Targets bool `json:"targets"`
}

// SyncStatus defines model for SyncStatus.
type SyncStatus struct {
	Active           *SyncActive       `json:"active,omitempty"`
	Created          int               `json:"created"`
	Deleted          int               `json:"deleted"`
	LastCompletedAt  *time.Time        `json:"lastCompletedAt,omitempty"`
	LastResult       *string           `json:"lastResult,omitempty"`
	Phases           SyncPhases        `json:"phases"`
	Schedule         SyncSchedule      `json:"schedule"`
	SourceStages     int               `json:"sourceStages"`
	State            string            `json:"state"`
	Surface          SurfaceCoverage   `json:"surface"`
	TrustedInventory *TrustedInventory `json:"trustedInventory,omitempty"`
	Updated          int               `json:"updated"`
	WahooRateLimit   *WahooRateLimit   `json:"wahooRateLimit,omitempty"`
}

// TargetRun defines model for TargetRun.
type TargetRun struct {
	CompletedAt time.Time `json:"completedAt"`
	Failure     *string   `json:"failure,omitempty"`
	Result      string    `json:"result"`
}

// TargetStages defines model for TargetStages.
type TargetStages struct {
	Current int `json:"current"`
	Pending int `json:"pending"`
}

// TargetStatus defines model for TargetStatus.
type TargetStatus struct {
	Authorisation string                  `json:"authorisation"`
	Convergence   TargetStatusConvergence `json:"convergence"`
	Id            string                  `json:"id"`
	LastRun       *TargetRun              `json:"lastRun,omitempty"`
	Stages        TargetStages            `json:"stages"`
}

// TargetStatusConvergence defines model for TargetStatus.Convergence.
type TargetStatusConvergence string

// TrustedInventory defines model for TrustedInventory.
type TrustedInventory struct {
	AgeSeconds    int        `json:"ageSeconds"`
	Fresh         bool       `json:"fresh"`
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	MaxAgeSeconds int        `json:"maxAgeSeconds"`
}

// Unready defines model for Unready.
type Unready struct {
	Reason UnreadyReason `json:"reason"`
	Status UnreadyStatus `json:"status"`
}

// UnreadyReason defines model for Unready.Reason.
type UnreadyReason string

// UnreadyStatus defines model for Unready.Status.
type UnreadyStatus string

// WahooRateLimit defines model for WahooRateLimit.
type WahooRateLimit struct {
	Remaining int        `json:"remaining"`
	ResetsAt  *time.Time `json:"resetsAt,omitempty"`
}

// WeatherForecast defines model for WeatherForecast.
type WeatherForecast struct {
	Points []WeatherPoint `json:"points"`
}

// WeatherPoint defines model for WeatherPoint.
type WeatherPoint struct {
	ApparentTemperatureCelsius      float64   `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres        float64   `json:"precipitationMillimetres"`
	PrecipitationProbabilityPercent float64   `json:"precipitationProbabilityPercent"`
	TemperatureCelsius              float64   `json:"temperatureCelsius"`
	Time                            time.Time `json:"time"`
	WeatherCode                     int       `json:"weatherCode"`
	WindDirectionDegrees            float64   `json:"windDirectionDegrees"`
	WindSpeedKmh                    float64   `json:"windSpeedKmh"`
}

// WebUIConfig defines model for WebUIConfig.
type WebUIConfig struct {
	Basemaps       []BrowserBasemap `json:"basemaps"`
	SourceBaseUrls *SourceBaseUrls  `json:"sourceBaseUrls,omitempty"`
}

// Provider defines model for Provider.
type Provider = string

// RouteId defines model for RouteId.
type RouteId = int64

// Stage defines model for Stage.
type Stage = int

// Target defines model for Target.
type Target = string

// AuthorizationFailed defines model for AuthorizationFailed.
type AuthorizationFailed = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidRequest defines model for InvalidRequest.
type InvalidRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ProviderUnavailable defines model for ProviderUnavailable.
type ProviderUnavailable = Error

// SyncInProgress defines model for SyncInProgress.
type SyncInProgress = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unavailable defines model for Unavailable.
type Unavailable = Error

// CompleteOAuthParams defines parameters for CompleteOAuth.
type CompleteOAuthParams struct {
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
}

// GetSyncRunsParams defines parameters for GetSyncRuns.
type GetSyncRunsParams struct {
	After *string `form:"after,omitempty" json:"after,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWeatherParams defines parameters for GetWeather.
type GetWeatherParams struct {
	Point []string `form:"point" json:"point"`
}

// SetSyncScheduleJSONRequestBody defines body for SetSyncSchedule for application/json ContentType.
type SetSyncScheduleJSONRequestBody = SyncSchedule

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	GetIndex(w http.ResponseWriter, r *http.Request)

	// (GET /assets/{asset})
	GetAsset(w http.ResponseWriter, r *http.Request, asset string)

	// (GET /favicon.svg)
	GetFavicon(w http.ResponseWriter, r *http.Request)

	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /icon-256.png)
	GetIcon256(w http.ResponseWriter, r *http.Request)

	// (GET /icon-512.png)
	GetIcon512(w http.ResponseWriter, r *http.Request)

	// (GET /manifest.webmanifest)
	GetManifest(w http.ResponseWriter, r *http.Request)

	// (GET /oauth/wahoo/callback)
	CompleteOAuth(w http.ResponseWriter, r *http.Request, params CompleteOAuthParams)

	// (GET /oauth/wahoo/start/{target})
	StartOAuth(w http.ResponseWriter, r *http.Request, target Target)

	// (GET /routes/{provider}/{routeId}/{stage})
	GetRoutePage(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (GET /routes/{routeId}/{stage})
	RedirectLegacyRoutePage(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (GET /settings)
	GetSettingsPage(w http.ResponseWriter, r *http.Request)

	// (GET /sync)
	GetSyncPage(w http.ResponseWriter, r *http.Request)

	// (GET /v1/providers/{provider}/routes/{routeId}/stages/{stage})
	GetRoute(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (GET /v1/providers/{provider}/routes/{routeId}/stages/{stage}/geometry)
	GetRouteGeometry(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (POST /v1/providers/{provider}/routes/{routeId}/stages/{stage}/reprocess)
	ReprocessRoute(w http.ResponseWriter, r *http.Request, provider Provider, routeId RouteId, stage Stage)

	// (GET /v1/routes)
	GetRoutes(w http.ResponseWriter, r *http.Request)

	// (GET /v1/routes/{routeId}/stages/{stage})
	RedirectLegacyRoute(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (GET /v1/routes/{routeId}/stages/{stage}/geometry)
	RedirectLegacyGeometry(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (POST /v1/routes/{routeId}/stages/{stage}/reprocess)
	RedirectLegacyReprocess(w http.ResponseWriter, r *http.Request, routeId RouteId, stage Stage)

	// (GET /v1/status)
	GetStatus(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync)
	TriggerSync(w http.ResponseWriter, r *http.Request)

	// (GET /v1/sync/runs)
	GetSyncRuns(w http.ResponseWriter, r *http.Request, params GetSyncRunsParams)

	// (PUT /v1/sync/schedule)
	SetSyncSchedule(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync/source)
	TriggerSourceSync(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync/surface)
	TriggerSurfaceSync(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync/targets)
	TriggerTargetsSync(w http.ResponseWriter, r *http.Request)

	// (POST /v1/sync/targets/{target})
	TriggerTargetSync(w http.ResponseWriter, r *http.Request, target Target)

	// (POST /v1/targets/{target}/clear)
	ClearTarget(w http.ResponseWriter, r *http.Request, target Target)

	// (GET /v1/weather)
	GetWeather(w http.ResponseWriter, r *http.Request, params GetWeatherParams)

	// (GET /v1/webui/config)
	GetWebUIConfig(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "asset" -------------
	var asset string

	err = runtime.BindStyledParameterWithOptions("simple", "asset", r.PathValue("asset"), &asset, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "asset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAsset(w, r, asset)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavicon operation middleware
func (siw *ServerInterfaceWrapper) GetFavicon(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavicon(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIcon256 operation middleware
func (siw *ServerInterfaceWrapper) GetIcon256(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIcon256(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIcon512 operation middleware
func (siw *ServerInterfaceWrapper) GetIcon512(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIcon512(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetManifest operation middleware
func (siw *ServerInterfaceWrapper) GetManifest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetManifest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteOAuth operation middleware
func (siw *ServerInterfaceWrapper) CompleteOAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteOAuthParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteOAuth(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartOAuth operation middleware
func (siw *ServerInterfaceWrapper) StartOAuth(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartOAuth(w, r, target)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoutePage operation middleware
func (siw *ServerInterfaceWrapper) GetRoutePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoutePage(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyRoutePage operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyRoutePage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyRoutePage(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSettingsPage operation middleware
func (siw *ServerInterfaceWrapper) GetSettingsPage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettingsPage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncPage operation middleware
func (siw *ServerInterfaceWrapper) GetSyncPage(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncPage(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoute operation middleware
func (siw *ServerInterfaceWrapper) GetRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoute(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRouteGeometry operation middleware
func (siw *ServerInterfaceWrapper) GetRouteGeometry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRouteGeometry(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReprocessRoute operation middleware
func (siw *ServerInterfaceWrapper) ReprocessRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider Provider

	err = runtime.BindStyledParameterWithOptions("simple", "provider", r.PathValue("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "provider", Err: err})
		return
	}

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReprocessRoute(w, r, provider, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoutes operation middleware
func (siw *ServerInterfaceWrapper) GetRoutes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoutes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyRoute operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyRoute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyRoute(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyGeometry operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyGeometry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyGeometry(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RedirectLegacyReprocess operation middleware
func (siw *ServerInterfaceWrapper) RedirectLegacyReprocess(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "routeId" -------------
	var routeId RouteId

	err = runtime.BindStyledParameterWithOptions("simple", "routeId", r.PathValue("routeId"), &routeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "routeId", Err: err})
		return
	}

	// ------------- Path parameter "stage" -------------
	var stage Stage

	err = runtime.BindStyledParameterWithOptions("simple", "stage", r.PathValue("stage"), &stage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stage", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RedirectLegacyReprocess(w, r, routeId, stage)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatus operation middleware
func (siw *ServerInterfaceWrapper) GetStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSyncRuns operation middleware
func (siw *ServerInterfaceWrapper) GetSyncRuns(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSyncRunsParams

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSyncRuns(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSyncSchedule operation middleware
func (siw *ServerInterfaceWrapper) SetSyncSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSyncSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSourceSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSourceSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSourceSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerSurfaceSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerSurfaceSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerSurfaceSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTargetsSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerTargetsSync(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTargetsSync(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerTargetSync operation middleware
func (siw *ServerInterfaceWrapper) TriggerTargetSync(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerTargetSync(w, r, target)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearTarget operation middleware
func (siw *ServerInterfaceWrapper) ClearTarget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "target" -------------
	var target Target

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearTarget(w, r, target)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWeather operation middleware
func (siw *ServerInterfaceWrapper) GetWeather(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWeatherParams

	// ------------- Required query parameter "point" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "point", r.URL.Query(), &params.Point, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "point"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "point", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWeather(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebUIConfig operation middleware
func (siw *ServerInterfaceWrapper) GetWebUIConfig(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebUIConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/status", wrapper.GetStatus)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync", wrapper.TriggerSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/source", wrapper.TriggerSourceSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/targets", wrapper.TriggerTargetsSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/targets/{target}", wrapper.TriggerTargetSync)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/targets/{target}/clear", wrapper.ClearTarget)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/sync/surface", wrapper.TriggerSurfaceSync)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/sync/schedule", wrapper.SetSyncSchedule)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/sync/runs", wrapper.GetSyncRuns)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes", wrapper.GetRoutes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}", wrapper.GetRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}/geometry", wrapper.GetRouteGeometry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/providers/{provider}/routes/{routeId}/stages/{stage}/reprocess", wrapper.ReprocessRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}", wrapper.RedirectLegacyRoute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}/geometry", wrapper.RedirectLegacyGeometry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/routes/{routeId}/stages/{stage}/reprocess", wrapper.RedirectLegacyReprocess)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/webui/config", wrapper.GetWebUIConfig)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/weather", wrapper.GetWeather)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/oauth/wahoo/start/{target}", wrapper.StartOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/oauth/wahoo/callback", wrapper.CompleteOAuth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/assets/{asset}", wrapper.GetAsset)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/favicon.svg", wrapper.GetFavicon)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/icon-256.png", wrapper.GetIcon256)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/icon-512.png", wrapper.GetIcon512)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/manifest.webmanifest", wrapper.GetManifest)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/{$}", wrapper.GetIndex)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/routes/{provider}/{routeId}/{stage}", wrapper.GetRoutePage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/routes/{routeId}/{stage}", wrapper.RedirectLegacyRoutePage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sync", wrapper.GetSyncPage)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/settings", wrapper.GetSettingsPage)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3pcxu3kv9XULPvw25lKFKynXrR1tYrRT6iPB8sUU4+2N4EnGkO8TQDTAAMJUal/30Lx9w3KSrWW3+x",
	"KQ6Oxq8b3Y1G9/DO8VgUMwpUCuf0zokxxxFI4PqvOWcb4gNXnwl1Tp0Yy7XjOhRHoP5KH7sOhz8SwsF3",
	"TiVPwHWEt4YIq34RoW+BBnLtnB67jtzGqqeQnNDAub93nUuWSLjwW6bg9mnXDCvGIyydU4dQ+f1zx1VT",
	"kiiJihMSKiEArmdcSBxAy3xCP+tZT9fgV5gHIFtGl+bh7nDdq64iZlSAZtCZ50EsQaPnMSqB6qlxHIfE",
	"w5IwOv2XYFR9l0/xNw4r59T5j2nO+ql5KqbZgHouH4THSazGcU6dXxm/RjdYIGwbIckQTyjCYku9NWeU",
	"JSLcHjn3rnMmhEGhjSq8wWbsMm11+VgxKqc3bLU6Kbe0A7+iHvNV21NniQVo/tcHIREOYBqrZnuOITbB",
	"d7dRuMc4Em7l1BOib+G63VCcasy6iKJE4mUIaI3FGnxUQB9hxZ0jx3XWgH2718+xt4bJOaOSs/ryhNpf",
	"cbIMieeiCN9OcAD/8+z4xbPvZ7OZi0g6W8OKFW1niVwzTv7U07/GJHxAkX3FOeNNEHxQsyK11UBItNKz",
	"IoFXYGX0R85uBPBL8AkHT1NRHiB9gpbYu1bCvjQ90MeLCnhvmSFdfW7f203IvGZ8SXwf6OHxUHuSa/4T",
	"H6gkcosYR4yTgFBEBKJMohh4RKQEXyP009W7txW6tFSuZXUH9Mrjq2gJvg9+hiFQybfIZ14SAd1BGCmb",
	"eKpVi8Rd0A0OiX9puH94cO1ECscIh8okWQzfQoC9bbuQzYFHWE2CIpBr5k9iDgL4htAAcdvrwaTtHaZk",
	"1Y1HZJt8Nw6YbOQmwwHLkvpJp3hwpr9n8jVLqP8Y7BYs4R5oe6g2zkrNqxmu1c4ApSIZ+hWvGUO4qBx3",
	"YnXmASWctEAzf/+mySbvbxhr0Mzfvylxm3i1Ve3P6dQz/UjxBpNQm56DMz2dtGpTbohcs0QiuI2ZUPs2",
	"dYyRDxKTUIvF4pcOBuzrVdRIXfzyCExYbKl3QeecBRyMP3NgA4Y8Rlch8aRWjom2WjjkgP0twp4kG9BQ",
	"f6TplnoMN+MdEZrpjCNijA5SXrQQ2s3iZlMbqh5PVJXeCJGQWIICKcnnPtLOpR2geobAvk/UCDiccxYr",
	"4tU5Y4VDAa467mVf3amTkkxEUVrSY0Gj15srr09p1y9ZO7b8l9KVuU/2IxYQ4XgkST7m1+eYSxZwHK+3",
	"BSO4ZCwETNUM5ijWc9ByHSG3IXzkYb96zdu+xPx6gDoug6HpKczXiEpCwrH80YrlJQmsta8RzWFDhLUs",
	"3RRmLZtIMxI4jjTYoY/HfGhcRwRC2PN89zL0CHn7+mIq7Q2VTWt+A+znxYf3rwHLhMPIhSyX7FbzR0Ik",
	"StLis6R0gqJJtASu14hvL0zz5zq6kf9hm2LO8Va1DIBFIPm2T3HYJbwlFBYZlGVCB3QvLPY+pSXXByk+",
	"fTtAP3UNMIUVlOjpYENhDWNFinGfUCzthkkZshtnnhU5c1LnTOfDKnSFNQ1Er7iYDrDmJQRGgIWFB1S+",
	"A8lhKDZeEiUhVlZ5AR6j/mhwqyj5REhMPRhFRYRv33DsE6ByDtyzJndAx5gRKs9ZQov6Mwv1uXn0s1G7",
	"5lHNWniyPpRu/d4apgbzgoOepx94mZDC2CLhK+yN1VIRlt4a/FFIc0yDylbq0iELQ9il6lXndtUGmbHd",
	"CmFNki6JDAeYg2LwOgsyF8BMBypyp8iLmji65T3SKHklqWoi/ifAoXJJ9nTF2PU+TlgxSjDG/SIiDvG2",
	"UUrV+aMsGmPWR/40H+rCz73G71N92gMB9xRL9ei2T6NAVdQQbd2Ka8blb7Rjp3L5W2J8ymFOYT5gsbub",
	"QZ0C20T2JWCfUHsw20ua9AFrH4HSdzyPYHDMkeonLNaNDHhc+xGxDaFBwfQ9KZujo1uX7WeEfc1Sm5Z2",
	"HX2EzoJeXRZEi9UvefOHV/EVGMoidhgLoBf1lozWvprs4dbXbMk+s2sHbaXzlxKvxpyCCBbjthNscJhg",
	"Cf4l8a2Pkt7EzprkO8Iw0t/7YTamQwWp4oJKk5cGri2jCdmFFrofsYCPPByrva9ZxJgcErXYQMjiEFNq",
	"tmhv0KJOZ2YoxjA+DWV0CaeJdxiNvgEemOBUPZZjDFPjI7GlXq8HuqWeXYRan76cH76DzE1/oX+n/2pN",
	"aL6gfEJLbKMoGB/5nG2A2yDHSKzlWUWcsYSJJBE0iYQXYiHIipTwLuypACjwbLvXnTyqYApBQovOZxKH",
	"TY+qkZqcjLRTafAOpMxpYmQ4ivoX1Ifbfp1yTczdElDV5JODRbzGod7jeGMO64pI7JkoaMDxBkL9Qd9K",
	"uU5Crym7KUbSKu7hIEIqcGmqSv3dfE2NWG2pd6bD5SORitdYQBEAYx8LstyysACGb6fARJP0csQY6S1s",
	"4BHoFXZhu7FTiM3V4i+TsZbO44Bl24byQQl0y8MQC3luZd4fA4Tq+BqT0AYnG59fgkhC2eH7LTKu1SlL",
	"Yr9tTRV0q2soTV6Zys2wymfIIepky+gzjpHbAfYh43pZwIZ3u2+hewdJ2kUWdhe/VYcE7aYIOKyAA/Wg",
	"5ULiUSQyJyJdhltCNiPkQaTzMqHz8Yabwm3LpU1CRwTYrJT1+iYJbdd6C28NfhLCzhus7poVtlH1YfX4",
	"0S5VFSp3cUVxZgL7ULTGcq/ttJc279DWcab/BukkY1sLTO11kNO2g/ahvnFu3sN5HHpAVDjzeJW88ERI",
	"8C/oBqhk/XdbV9X23frBdW7wmrFLrI7dEZF9w/9abt0UBst0i3Yr7MJH6ZMCj5pk3jhLj2RCugxBq9Ku",
	"Xb42aNj2leUiNmZxCef29N7txsdAfXtdOMJRTIfP+3fSv4M+Mkkrov2AlZ4erQlNjW9OWYiDwJxDTGqS",
	"PnIUkmGarDLx253EhA5z262Z2cXTr6BMFM1lJMrr7vTTrxpUxRgOBMWrygaXiEMptFwwagquRaLzfsbs",
	"rQjfnnVOWoGnQGG1c0peEy4faRYqGQEHB2yzkTI3Tym33xI9mk33Nl81ns5LR8DKnUJCR90quCkxTav7",
	"taa/Ry0ywoRaddAQJgcBY46hNW8zHb2RcMByDfw14+Dh0RFfHUge7g7ayeaqV69PaMfuINqMM3J/xTFW",
	"muoKohi4zg45h1CQZPD9CAePxERqxfCOhCGJxtzllLrPOVviJQmJ3I4LFMtdqdcSM1g13Bicz8uJT0W3",
	"hVD/pc4lJoy+hIDDYCBU10UM4P8zWu8S7U5priPhdjG5g4H9zKlQ3bL+Mm7N8rv8eHHO6IqMTRhamqzE",
	"4Vuuks1YygI6rl8si1rgv9NTLreuXUikxDYmugnwEk7kVnn3UXoc0sYrzVmtZ64vSEDBR+chS/xViDnU",
	"8lzRinEk16DzdEmQcPBRzAn1SIzDIx3EdU5tDnJeFXe+mpiBJj/fyElOQA5QTP4JGiFbPPJB16zUKXx1",
	"iz2ZVZjYypYCLYY8IpAusPDgCF1axNByi2ADfItYbEPcSK6xRCYMibBON2Yc3XAiQZjMWhdh6qOI+RCG",
	"4COsmqXAIs0mQFwLoxqLIoyy8kq0BA8nAtTANpk8zSInuoiEwyoR4Jf6R0Qoo9kKpIWlhpuuXqMrVgfs",
	"SvPKGG7009XVXKEluUJRQWRweckiEJL8kcAR+nnx4T2yu2KL1LwCYQ6fqYcjCM+xgCN0FoZIX6gKBLce",
	"xBL9/ubVFZqudW7Ln78jK6ZaUkRVqD7TqlT9t0F74q0xDXTmtxkch4KVx8IRTAzXP9PfDRq/I4PS0Wea",
	"3feeOvmSzKrP5heO62yAm9tu5/hodjRTAsdioDgmzqnz7Oj4aKYj/XKt98tU/WNrPTOhufCdU+cNZHH4",
	"UrXmyWzWtqmzdlNdc3XvOs9nx/2NS5nuutOz/k55yZkOTuJAaH1hds0kIc4X9f1UFwmK6Z3+/75rsaau",
	"wS0VD39qLIDFtuXwqqUvu2BoCHosEFWP5/09suKkTtRXeKNrNcQm6IL8tWm2k4RllShPEiCrRbrAsUl0",
	"zdg8SN2FnaG5RkhrLyJQaOpRCtbWOf1kFqF4Nzl58f2RrbxqVSMeoycvvt+JzVnF15Nks0boxfHJEIRe",
	"HJ/8P0Qoq6K8gWVUyNhsQyrL6twFqry88ylCxRQtUx3mnXo4DJfYu26FKg3S6zrOFqv2RwK6QiF/a4SO",
	"+XaU8zd3tDUpw83fsyEwVgvbNZhDzGZDlf5f4IlobjVwTrvi0ztzF9TukCxUsxbmNZGTN7GRSacB9ZP+",
	"xZTrfp8C5q7zYkiPYuFiG590ME8ZZf2H9s+nd2n+5f30zuZf3k/vdPS2053UmYVz8x6WcfzL3lej9ltP",
	"2/S9MwOamhfG7OaKfjXufMqUwZxIRdm+wGBnpuwP9LPZ3/thqLxn4UnaKQFSEhqIrt2xsG3m6YuKnqxE",
	"pimarSvdUu/pr3JzPE31YEkl1vajudYarCCfhnJ8kNOWzVVveMuBZBx8pBFDEUjsY4mPBtveyjtivlqV",
	"saedTkUSx3vK5LRYXdwpnG8KRbxPVkgDYCNfglMpDO+T2BTObxJ7MInlEJuAjLkwFY1+jm3yNNTqgJNI",
	"/hK/b2JVCb81XHN9+lK7V/r0RQHfKY1G8HoVoXAObRd1qVifpiFpQkx2y1TRPV//abODC+OdqIazzVM6",
	"1/wbben7gazs9z3KPN3ZA/nG1kdl6yADXdqsWYdvnP2L4hc72dNUIPJUwNZzf57ydyDDmRZt1q3muUml",
	"RWH2/rREPG0TmUZZmvfWFSdBAHyhGu3vaj6SvP4w4I67/GrCQ3mBCtxpWpTTFce6VG0G3SXhldQ5PaPv",
	"kkKd/Frs6MMK6+z8k5lOFrbvLZ/Nel6RfshYTrEoqvEVjxRuQMjJinAhkZdwwTiKcQBP4JB8mM07LVbr",
	"xEnTjZeRsaxSx+TXgJA/MpPz/WCcy4uByumGkidwf2CpKc/dfNixTf5dZeVgKiwv1+s2E6aA6Zux2APp",
	"vAyuG2rT7hvWe2BdKDTtxNpc+4tvWO+PdSk9YwDoFvOHSdP4epk1Msr5NXG3ytipFwLm7ew9V4+v0h+6",
	"+cbYr5axtk6m6+RiS73qfITbONR1SSZ9u+k4oivIOlO9sxKaGEsJXI3xv5N/fJpNfvjy3X9+/nxkPv3X",
	"P9zGL4+++1tLQWX6duS/95XbyK0uBlgxHh32Arta59fgwabPkMBRHIJAhGaVIYz7wJ+ETztgmzb9ckPv",
	"OegGlgmZelnRVrvA5rVdB+VnPk0DL23+5YTRcIt4QiWJ8pIonP0gwF+VmmKRHaBW1KbQdUB22+t3lzpT",
	"p6Bb7ur57wHHUYQl8YoFOehsfoF0RdNyq4t1IP1BIPNjSlZrFGm8d+/Sr02qYeGLQpqN+rb64wcs1j/Z",
	"xNNXoKKQCAkUuJvWNQlQKk1CuEUrziJNkvl9K7TG1A/Vhst/hS57lapa+e3Ez8qHJgm1bySe6EqXA/yw",
	"QxowfT57fn//fwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
