// Code generated by libopenapi generator/golang. DO NOT EDIT.

package contract

import (
	"encoding/json"
	"time"
)

type Error_Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Error struct {
	Error Error_Error `json:"error"`
}

type Health struct {
	Status string `json:"status"`
}

type Readiness struct {
	Status string `json:"status"`
}

type Unready_Reason string

const (
	Unready_ReasonStateUnreadable Unready_Reason = "state_unreadable"
	Unready_ReasonStateIncomplete Unready_Reason = "state_incomplete"
)

type Unready struct {
	Status string         `json:"status"`
	Reason Unready_Reason `json:"reason"`
}

type Accepted struct {
	Status string `json:"status"`
}

type TargetRoutes struct {
	Current int `json:"current"`
	Pending int `json:"pending"`
}

type TargetRun struct {
	CompletedAt time.Time `json:"completedAt"`
	Result      string    `json:"result"`
	Failure     *string   `json:"failure,omitempty"`
}

type TargetStatus_Convergence string

const (
	TargetStatus_ConvergenceCurrent      TargetStatus_Convergence = "current"
	TargetStatus_ConvergenceLagging      TargetStatus_Convergence = "lagging"
	TargetStatus_ConvergenceFailed       TargetStatus_Convergence = "failed"
	TargetStatus_ConvergenceUnauthorized TargetStatus_Convergence = "unauthorized"
)

type TargetStatus struct {
	ID            string                   `json:"id"`
	Authorisation string                   `json:"authorisation"`
	Convergence   TargetStatus_Convergence `json:"convergence"`
	Routes        TargetRoutes             `json:"routes"`
	LastRun       *TargetRun               `json:"lastRun,omitempty"`
}

type RouteValidation struct {
	BiasPercent    float64 `json:"biasPercent"`
	MaePercent     float64 `json:"maePercent"`
	P90percent     float64 `json:"p90Percent"`
	EvaluatedRides int     `json:"evaluatedRides"`
}

type Route struct {
	Provider           string           `json:"provider"`
	SourceRouteID      int64            `json:"sourceRouteId"`
	StageOrder         int              `json:"stageOrder"`
	Title              string           `json:"title"`
	SourceRouteName    string           `json:"sourceRouteName"`
	RouteName          string           `json:"routeName"`
	SourceRevision     string           `json:"sourceRevision"`
	ContentHash        string           `json:"contentHash"`
	DistanceMetres     float64          `json:"distanceMetres"`
	AscentMetres       float64          `json:"ascentMetres"`
	DescentMetres      float64          `json:"descentMetres"`
	MaxGradientPercent float64          `json:"maxGradientPercent"`
	PointCount         int              `json:"pointCount"`
	MovingSeconds      *float64         `json:"movingSeconds,omitempty"`
	Validation         *RouteValidation `json:"validation,omitempty"`
}

type RouteList struct {
	Routes []Route `json:"routes"`
}

type SyncPhaseRun struct {
	LastCompletedAt time.Time `json:"lastCompletedAt"`
	LastResult      string    `json:"lastResult"`
	LastFailure     *string   `json:"lastFailure,omitempty"`
	SourceRoutes    int       `json:"sourceRoutes"`
	Created         int       `json:"created"`
	Updated         int       `json:"updated"`
	Deleted         int       `json:"deleted"`
}

type SyncPhases struct {
	Source  *SyncPhaseRun `json:"source,omitempty"`
	Targets *SyncPhaseRun `json:"targets,omitempty"`
}

type SyncActive_Phase string

const (
	SyncActive_PhaseSource  SyncActive_Phase = "source"
	SyncActive_PhaseTargets SyncActive_Phase = "targets"
)

type SyncActive struct {
	Phase    *SyncActive_Phase `json:"phase,omitempty"`
	StartsAt *time.Time        `json:"startsAt,omitempty"`
	Targets  int               `json:"targets"`
	Routes   TargetRoutes      `json:"routes"`
}

type SurfaceCoverage struct {
	Generation *string    `json:"generation,omitempty"`
	BuiltAt    *time.Time `json:"builtAt,omitempty"`
	Classified int        `json:"classified"`
	Total      int        `json:"total"`
	Incomplete int        `json:"incomplete"`
	// EnrichmentFailures How many stages currently have a surface or duration enrichment pass recorded against them as unable to finish.
	EnrichmentFailures int `json:"enrichmentFailures"`
}

type WahooRateLimit struct {
	Remaining int        `json:"remaining"`
	ResetsAt  *time.Time `json:"resetsAt,omitempty"`
}

type TrustedInventory struct {
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	AgeSeconds    int        `json:"ageSeconds"`
	MaxAgeSeconds int        `json:"maxAgeSeconds"`
	Fresh         bool       `json:"fresh"`
}

type SyncStatus struct {
	State            string            `json:"state"`
	Active           *SyncActive       `json:"active,omitempty"`
	LastResult       *string           `json:"lastResult,omitempty"`
	LastCompletedAt  *time.Time        `json:"lastCompletedAt,omitempty"`
	SourceRoutes     int               `json:"sourceRoutes"`
	Created          int               `json:"created"`
	Updated          int               `json:"updated"`
	Deleted          int               `json:"deleted"`
	Phases           SyncPhases        `json:"phases"`
	Surface          SurfaceCoverage   `json:"surface"`
	WahooRateLimit   *WahooRateLimit   `json:"wahooRateLimit,omitempty"`
	TrustedInventory *TrustedInventory `json:"trustedInventory,omitempty"`
}

type Build struct {
	Revision    string  `json:"revision"`
	ImageDigest *string `json:"imageDigest,omitempty"`
}

type Status struct {
	Ready     bool           `json:"ready"`
	Converged bool           `json:"converged"`
	Build     *Build         `json:"build,omitempty"`
	Targets   []TargetStatus `json:"targets"`
	Sync      SyncStatus     `json:"sync"`
}

type SyncRun_Phase string

const (
	SyncRun_PhaseSource  SyncRun_Phase = "source"
	SyncRun_PhaseTargets SyncRun_Phase = "targets"
)

type SyncRun struct {
	Reference    string        `json:"reference"`
	Phase        SyncRun_Phase `json:"phase"`
	CompletedAt  time.Time     `json:"completedAt"`
	Result       string        `json:"result"`
	Failure      *string       `json:"failure,omitempty"`
	SourceRoutes int           `json:"sourceRoutes"`
	Created      int           `json:"created"`
	Updated      int           `json:"updated"`
	Deleted      int           `json:"deleted"`
}

type SyncRunPage struct {
	Runs []SyncRun `json:"runs"`
	Next *string   `json:"next,omitempty"`
}

// Settings_SecretsSet Whether each credential is stored. This is the whole of what any observable surface is told about one: never the value, only that there is one to replace.
type Settings_SecretsSet struct {
	AdditionalProperties map[string]bool `json:"-"`
}

func (m *Settings_SecretsSet) UnmarshalJSON(data []byte) error {
	type Alias Settings_SecretsSet
	var known Alias
	if err := json.Unmarshal(data, &known); err != nil {
		return err
	}
	*m = Settings_SecretsSet(known)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if len(raw) == 0 {
		return nil
	}
	m.AdditionalProperties = make(map[string]bool, len(raw))
	for key, value := range raw {
		var decoded bool
		if err := json.Unmarshal(value, &decoded); err != nil {
			return err
		}
		m.AdditionalProperties[key] = decoded
	}
	return nil
}

func (m Settings_SecretsSet) MarshalJSON() ([]byte, error) {
	type Alias Settings_SecretsSet
	encoded, err := json.Marshal(Alias(m))
	if err != nil {
		return nil, err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(encoded, &object); err != nil {
		return nil, err
	}
	for key, value := range m.AdditionalProperties {
		encodedValue, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		object[key] = encodedValue
	}
	return json.Marshal(object)
}

// Settings The settings held in the state database rather than in the configuration file, which take effect on the next run or the next request rather than on the next restart.
type Settings struct {
	// Timezone The IANA zone this service reads local time in: what a scheduled time of day means, and what hour a forecast describes.
	Timezone      string               `json:"timezone"`
	Sync          SyncSettings         `json:"sync"`
	Notifications NotificationSettings `json:"notifications"`
	Basemaps      []BrowserBasemap     `json:"basemaps"`
	Surface       SurfaceSettings      `json:"surface"`
	Wahoo         WahooSettings        `json:"wahoo"`
	// Sources The libraries a run reads, in the order it reads them. An empty list is a service nobody has configured yet, not an error.
	Sources   []SourceSettings  `json:"sources"`
	RideModel RideModelSettings `json:"rideModel"`
	// Alerts Every alert this service can raise, and whether it is delivered. An alert nobody has ruled on is delivered: a fault nobody has heard of is the one worth hearing about.
	Alerts []AlertSetting `json:"alerts"`
	// SecretsSet Whether each credential is stored. This is the whole of what any observable surface is told about one: never the value, only that there is one to replace.
	SecretsSet map[string]bool `json:"secretsSet"`
	// Missing The settings still to be entered, in the order the page offers them. Everything a run needs is here, and so are the Pushover credentials while notifications are on, which no run needs but every notification does. Empty is a configured service.
	Missing []string `json:"missing"`
}

// WahooApplicationUpdate The registered application, without the slots it writes to. Those are replaced on their own.
type WahooApplicationUpdate struct {
	// APIBaseURL The origin route reads and writes are sent to.
	APIBaseURL string `json:"apiBaseUrl"`
	// OauthBaseURL The origin an authorization and a token refresh are sent to.
	OauthBaseURL string `json:"oauthBaseUrl"`
	// ClientID The registered application's public identifier.
	ClientID string `json:"clientId"`
	// ClientSecret The application's secret, sent only when it was typed into the form. Left out it keeps the stored value, which is how a page that was never told the secret can save the rest of the application; sent empty it removes the credential.
	ClientSecret *string `json:"clientSecret,omitempty"`
}

type TargetsUpdate struct {
	// Targets The destination slots, in the order they are offered. A slot name is the identity every stored authorization, target route and recorded run already carries, so renaming one abandons that slot's state rather than moving it.
	Targets []string `json:"targets"`
}

// SourceUpdate One library, and the account it is read with.
type SourceUpdate struct {
	// Read Whether a run reads this library at all. Off takes it out of the list without forgetting the account it was read with.
	Read bool `json:"read"`
	// BaseURL The source's own web application, which is both the origin the service reads and the one a route is linked back to.
	BaseURL string `json:"baseUrl"`
	// Email The account's email address, sent only when it was typed. The rules the application secret follows apply here too.
	Email *string `json:"email,omitempty"`
	// Password The account's password, on the same terms as the email address.
	Password *string `json:"password,omitempty"`
}

type AlertSetting struct {
	// Task The background activity the alert is about.
	Task string `json:"task"`
	// Alert The stable reason the alert names. It never carries provider text, a route name, or an upstream identifier.
	Alert string `json:"alert"`
	// Enabled Whether this alert is delivered.
	Enabled bool `json:"enabled"`
	// Decided Whether anybody has ruled on it. An alert nobody has ruled on is delivered, which is not the same as one somebody switched on.
	Decided bool `json:"decided"`
}

type AlertsUpdate struct {
	// Alerts What the operator has decided. Deciding is what creates a record, so an alert left out of this list keeps whatever it had.
	Alerts []AlertDecision `json:"alerts"`
}

type AlertDecision struct {
	Task    string `json:"task"`
	Alert   string `json:"alert"`
	Enabled bool   `json:"enabled"`
}

type NotificationsUpdate struct {
	// Enabled The switch for the whole channel. Off, nothing is sent at all: a failure, a blocked run, a recovery and a task that has stopped succeeding are held back as surely as a routine success is. Which alerts are sent while it is on is a decision per task and per reason, held in the alert matrix.
	Enabled bool `json:"enabled"`
	// PushoverBaseURL The origin the application token and user key are sent to.
	PushoverBaseURL string `json:"pushoverBaseUrl"`
	// ApplicationToken The Pushover application's token, sent only when it was typed. The rules the application secret follows apply here too.
	ApplicationToken *string `json:"applicationToken,omitempty"`
	// UserKey The recipient key, on the same terms as the application token.
	UserKey *string `json:"userKey,omitempty"`
}

type BasemapsUpdate struct {
	Basemaps []BrowserBasemap `json:"basemaps"`
}

type TaskScheduleUpdate struct {
	// Enabled Whether the schedule may start this task. It governs unattended runs only.
	Enabled bool `json:"enabled"`
}

type TaskList struct {
	Tasks []Task `json:"tasks"`
}

type Task struct {
	// Name What a trigger asks for.
	Name string `json:"name"`
	// Scheduled Whether the task has a schedule at all.
	Scheduled bool `json:"scheduled"`
	// Enabled Whether the schedule may start it. A task nobody has ruled on runs. It governs unattended runs only.
	Enabled bool `json:"enabled"`
	// Running How many attempts of this task are in flight.
	Running int `json:"running"`
	// IntervalSeconds The gap between runs for a task on a fixed schedule. Absent for a task with no schedule, or a calendar one, whose gap changes with the wall clock.
	IntervalSeconds *int `json:"intervalSeconds,omitempty"`
	// NextRunAt When the next scheduled run is due. Absent for a task nothing schedules, and while the task's own scheduled run is under way. A run somebody asked for does not disturb the schedule, so this stays put during one.
	NextRunAt *time.Time `json:"nextRunAt,omitempty"`
}

// TaskRun One recorded attempt. It carries the aggregate record and nothing about what the attempt touched.
type TaskRun struct {
	Task string `json:"task"`
	// Argument What the attempt was over, such as a target slot. Absent for a task that covers only one thing.
	Argument *string `json:"argument,omitempty"`
	// Trigger What started the attempt: `schedule`, `manual`, or `chain`. Absent for an attempt recorded before this was written down.
	Trigger    *string   `json:"trigger,omitempty"`
	StartedAt  time.Time `json:"startedAt"`
	FinishedAt time.Time `json:"finishedAt"`
	Outcome    string    `json:"outcome"`
	// Detail A stable, safe-to-display reason for the outcome. Never provider text, a route name, or an upstream identifier.
	Detail *string `json:"detail,omitempty"`
	// Reference The name an alert about this attempt carries.
	Reference string `json:"reference"`
}

type TaskRunPage struct {
	Runs []TaskRun `json:"runs"`
	Next *string   `json:"next,omitempty"`
}

type TimezoneUpdate struct {
	// Timezone An IANA zone name this service can load, such as Europe/Berlin.
	Timezone string `json:"timezone"`
}

type SyncSettings struct {
	// AllowEmptySourceDeletion Whether a source that reports an empty library may delete the last routes a target holds. It stays on until it is turned off again.
	AllowEmptySourceDeletion bool `json:"allowEmptySourceDeletion"`
	// StaleAfterSeconds How long the trusted source inventory may go without a successful refresh before it is reported and notified as stale.
	StaleAfterSeconds int `json:"staleAfterSeconds"`
	// InitialDelaySeconds How long after start the first run is attempted. It is read by the start it delays, so an edit reaches the next restart rather than the next run.
	InitialDelaySeconds int `json:"initialDelaySeconds"`
}

type NotificationSettings struct {
	// Enabled The switch for the whole channel. Off, nothing is sent at all: a failure, a blocked run, a recovery and a task that has stopped succeeding are held back as surely as a routine success is. Which alerts are sent while it is on is a decision per task and per reason, held in the alert matrix.
	Enabled bool `json:"enabled"`
	// PushoverBaseURL The origin the application token and user key are sent to.
	PushoverBaseURL string `json:"pushoverBaseUrl"`
}

type WahooSettings struct {
	// APIBaseURL The origin route reads and writes are sent to. Empty until the application is registered, which is a service that runs nothing rather than one that is broken.
	APIBaseURL string `json:"apiBaseUrl"`
	// OauthBaseURL The origin an authorization and a token refresh are sent to.
	OauthBaseURL string `json:"oauthBaseUrl"`
	// ClientID The registered application's public identifier. Its secret is not here: it is written through secrets and read back only as set.
	ClientID string `json:"clientId"`
	// Targets The destination slots, in the order they are offered. A slot name is the identity every stored authorization, target route and recorded run already carries, so renaming one abandons that slot's state rather than moving it.
	Targets []string `json:"targets"`
}

type SourceSettings_Provider string

const (
	SourceSettings_ProviderVeloplanner SourceSettings_Provider = "veloplanner"
	SourceSettings_ProviderKomoot      SourceSettings_Provider = "komoot"
)

type SourceSettings struct {
	Provider SourceSettings_Provider `json:"provider"`
	// BaseURL The source's own web application, which is both the origin the service reads and the one a route is linked back to.
	BaseURL string `json:"baseUrl"`
}

type RideModelSettings struct {
	// CoefficientsFile The coefficient file the offline fitting tooling emits, named by an absolute path the service can read. Empty is predicted moving time switched off, which is also the default.
	CoefficientsFile string `json:"coefficientsFile"`
}

type SurfaceSettings struct {
	// Regions The Geofabrik region paths the surface index is built from. An empty list switches classification off.
	Regions []string `json:"regions"`
	// RebuildIntervalSeconds How often the index is rebuilt. Required whether or not a region is named: the rebuild schedule runs either way, and with no region it simply builds nothing.
	RebuildIntervalSeconds int `json:"rebuildIntervalSeconds"`
}

type BrowserBasemap struct {
	Name            string  `json:"name"`
	StyleURL        string  `json:"styleUrl"`
	StyleURLDark    *string `json:"styleUrlDark,omitempty"`
	DarkCartography *bool   `json:"darkCartography,omitempty"`
}

type WebUIConfig struct {
	Basemaps       []BrowserBasemap `json:"basemaps"`
	SourceBaseUrls *SourceBaseUrls  `json:"sourceBaseUrls,omitempty"`
	Identity       BrowserIdentity  `json:"identity"`
}

// BrowserIdentity Who the gate let through. It names the reader rather than identifying them: it is how a session can be seen to be the one intended.
type BrowserIdentity struct {
	Display string `json:"display"`
}

type SourceBaseUrls struct {
	Veloplanner *string `json:"veloplanner,omitempty"`
	Komoot      *string `json:"komoot,omitempty"`
}

type SurfaceRange_Kind string

const (
	SurfaceRange_KindAsphalt   SurfaceRange_Kind = "asphalt"
	SurfaceRange_KindPaving    SurfaceRange_Kind = "paving"
	SurfaceRange_KindCompacted SurfaceRange_Kind = "compacted"
	SurfaceRange_KindGravel    SurfaceRange_Kind = "gravel"
	SurfaceRange_KindGround    SurfaceRange_Kind = "ground"
	SurfaceRange_KindUnknown   SurfaceRange_Kind = "unknown"
)

type SurfaceRange struct {
	Kind       SurfaceRange_Kind `json:"kind"`
	StartIndex int               `json:"startIndex"`
	EndIndex   int               `json:"endIndex"`
}

type GeoJSONLineString struct {
	Type        string      `json:"type"`
	Coordinates [][]float64 `json:"coordinates"`
}

type GeoJSONProperties_Surface struct {
	Ranges        []SurfaceRange `json:"ranges"`
	MatchedMetres float64        `json:"matchedMetres"`
}

type GeoJSONProperties struct {
	Provider           string                     `json:"provider"`
	SourceRouteID      int64                      `json:"sourceRouteId"`
	StageOrder         int                        `json:"stageOrder"`
	Title              string                     `json:"title"`
	SourceRouteName    string                     `json:"sourceRouteName"`
	RouteName          string                     `json:"routeName"`
	DistanceMetres     float64                    `json:"distanceMetres"`
	AscentMetres       float64                    `json:"ascentMetres"`
	DescentMetres      float64                    `json:"descentMetres"`
	MaxGradientPercent float64                    `json:"maxGradientPercent"`
	PointCount         int                        `json:"pointCount"`
	Surface            *GeoJSONProperties_Surface `json:"surface,omitempty"`
	CumulativeSeconds  []float64                  `json:"cumulativeSeconds,omitempty"`
}

type GeoJSONFeature struct {
	Type       string            `json:"type"`
	Bbox       []float64         `json:"bbox"`
	Geometry   GeoJSONLineString `json:"geometry"`
	Properties GeoJSONProperties `json:"properties"`
}

type WeatherPoint struct {
	Time                            time.Time `json:"time"`
	TemperatureCelsius              float64   `json:"temperatureCelsius"`
	ApparentTemperatureCelsius      float64   `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres        float64   `json:"precipitationMillimetres"`
	PrecipitationProbabilityPercent float64   `json:"precipitationProbabilityPercent"`
	WindSpeedKmh                    float64   `json:"windSpeedKmh"`
	WindDirectionDegrees            float64   `json:"windDirectionDegrees"`
	WeatherCode                     int       `json:"weatherCode"`
}

type WeatherForecast struct {
	Points []WeatherPoint `json:"points"`
}
