// Code generated by libopenapi generator/golang. DO NOT EDIT.

package contract

import "time"

type Error_Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Error struct {
	Error Error_Error `json:"error"`
}

type Health struct {
	Status string `json:"status"`
}

type Readiness struct {
	Status string `json:"status"`
}

type Unready_Reason string

const (
	Unready_ReasonStateUnreadable Unready_Reason = "state_unreadable"
	Unready_ReasonStateIncomplete Unready_Reason = "state_incomplete"
)

type Unready struct {
	Status string         `json:"status"`
	Reason Unready_Reason `json:"reason"`
}

type Accepted struct {
	Status string `json:"status"`
}

type TargetStages struct {
	Current int `json:"current"`
	Pending int `json:"pending"`
}

type TargetRun struct {
	CompletedAt time.Time `json:"completedAt"`
	Result      string    `json:"result"`
	Failure     *string   `json:"failure,omitempty"`
}

type TargetStatus_Convergence string

const (
	TargetStatus_ConvergenceCurrent      TargetStatus_Convergence = "current"
	TargetStatus_ConvergenceLagging      TargetStatus_Convergence = "lagging"
	TargetStatus_ConvergenceFailed       TargetStatus_Convergence = "failed"
	TargetStatus_ConvergenceUnauthorized TargetStatus_Convergence = "unauthorized"
)

type TargetStatus struct {
	ID            string                   `json:"id"`
	Authorisation string                   `json:"authorisation"`
	Convergence   TargetStatus_Convergence `json:"convergence"`
	Stages        TargetStages             `json:"stages"`
	LastRun       *TargetRun               `json:"lastRun,omitempty"`
}

type RouteValidation struct {
	BiasPercent    float64 `json:"biasPercent"`
	MaePercent     float64 `json:"maePercent"`
	P90percent     float64 `json:"p90Percent"`
	EvaluatedRides int     `json:"evaluatedRides"`
}

type Route struct {
	Provider           string           `json:"provider"`
	RouteID            int64            `json:"routeId"`
	StageOrder         int              `json:"stageOrder"`
	Title              string           `json:"title"`
	RouteName          string           `json:"routeName"`
	StageName          string           `json:"stageName"`
	SourceRevision     string           `json:"sourceRevision"`
	ContentHash        string           `json:"contentHash"`
	DistanceMetres     float64          `json:"distanceMetres"`
	AscentMetres       float64          `json:"ascentMetres"`
	MaxGradientPercent float64          `json:"maxGradientPercent"`
	PointCount         int              `json:"pointCount"`
	MovingSeconds      *float64         `json:"movingSeconds,omitempty"`
	Validation         *RouteValidation `json:"validation,omitempty"`
}

type RouteList struct {
	Stages []Route `json:"stages"`
}

type SyncSchedule struct {
	Source  bool `json:"source"`
	Targets bool `json:"targets"`
}

type SyncPhaseRun struct {
	LastCompletedAt time.Time `json:"lastCompletedAt"`
	LastResult      string    `json:"lastResult"`
	LastFailure     *string   `json:"lastFailure,omitempty"`
	SourceStages    int       `json:"sourceStages"`
	Created         int       `json:"created"`
	Updated         int       `json:"updated"`
	Deleted         int       `json:"deleted"`
}

type SyncPhases struct {
	Source  *SyncPhaseRun `json:"source,omitempty"`
	Targets *SyncPhaseRun `json:"targets,omitempty"`
}

type SyncActive_Phase string

const (
	SyncActive_PhaseSource  SyncActive_Phase = "source"
	SyncActive_PhaseTargets SyncActive_Phase = "targets"
)

type SyncActive struct {
	Phase    *SyncActive_Phase `json:"phase,omitempty"`
	StartsAt *time.Time        `json:"startsAt,omitempty"`
	Targets  int               `json:"targets"`
	Stages   TargetStages      `json:"stages"`
}

type SurfaceCoverage struct {
	Generation *string    `json:"generation,omitempty"`
	BuiltAt    *time.Time `json:"builtAt,omitempty"`
	Classified int        `json:"classified"`
	Total      int        `json:"total"`
	Incomplete int        `json:"incomplete"`
}

type WahooRateLimit struct {
	Remaining int        `json:"remaining"`
	ResetsAt  *time.Time `json:"resetsAt,omitempty"`
}

type TrustedInventory struct {
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	AgeSeconds    int        `json:"ageSeconds"`
	MaxAgeSeconds int        `json:"maxAgeSeconds"`
	Fresh         bool       `json:"fresh"`
}

type SyncStatus struct {
	State            string            `json:"state"`
	Active           *SyncActive       `json:"active,omitempty"`
	LastResult       *string           `json:"lastResult,omitempty"`
	LastCompletedAt  *time.Time        `json:"lastCompletedAt,omitempty"`
	SourceStages     int               `json:"sourceStages"`
	Created          int               `json:"created"`
	Updated          int               `json:"updated"`
	Deleted          int               `json:"deleted"`
	Schedule         SyncSchedule      `json:"schedule"`
	Phases           SyncPhases        `json:"phases"`
	Surface          SurfaceCoverage   `json:"surface"`
	WahooRateLimit   *WahooRateLimit   `json:"wahooRateLimit,omitempty"`
	TrustedInventory *TrustedInventory `json:"trustedInventory,omitempty"`
}

type Build struct {
	Revision    string  `json:"revision"`
	ImageDigest *string `json:"imageDigest,omitempty"`
}

type Status struct {
	Ready     bool           `json:"ready"`
	Converged bool           `json:"converged"`
	Build     *Build         `json:"build,omitempty"`
	Targets   []TargetStatus `json:"targets"`
	Sync      SyncStatus     `json:"sync"`
}

type SyncRun_Phase string

const (
	SyncRun_PhaseSource  SyncRun_Phase = "source"
	SyncRun_PhaseTargets SyncRun_Phase = "targets"
)

type SyncRun struct {
	Reference    string        `json:"reference"`
	Phase        SyncRun_Phase `json:"phase"`
	CompletedAt  time.Time     `json:"completedAt"`
	Result       string        `json:"result"`
	Failure      *string       `json:"failure,omitempty"`
	SourceStages int           `json:"sourceStages"`
	Created      int           `json:"created"`
	Updated      int           `json:"updated"`
	Deleted      int           `json:"deleted"`
}

type SyncRunPage struct {
	Runs []SyncRun `json:"runs"`
	Next *string   `json:"next,omitempty"`
}

// Settings The settings held in the state database rather than in the configuration file, which take effect on the next run or the next request rather than on the next restart.
type Settings struct {
	Sync          SyncSettings         `json:"sync"`
	Notifications NotificationSettings `json:"notifications"`
	Basemaps      []BrowserBasemap     `json:"basemaps"`
	Surface       SurfaceSettings      `json:"surface"`
}

type SyncSettings struct {
	// AllowEmptySourceDeletion Whether a source that reports an empty library may delete the last routes a target holds. It stays on until it is turned off again.
	AllowEmptySourceDeletion bool `json:"allowEmptySourceDeletion"`
	// StaleAfterSeconds How long the trusted source inventory may go without a successful refresh before it is reported and notified as stale.
	StaleAfterSeconds int `json:"staleAfterSeconds"`
}

type NotificationSettings_SuccessPolicy string

const (
	NotificationSettings_SuccessPolicyEvery  NotificationSettings_SuccessPolicy = "every"
	NotificationSettings_SuccessPolicyQuiet  NotificationSettings_SuccessPolicy = "quiet"
	NotificationSettings_SuccessPolicyDigest NotificationSettings_SuccessPolicy = "digest"
)

type NotificationSettings struct {
	// Enabled The switch for the whole channel. Off suppresses a failure and a stale inventory as surely as it suppresses a routine success.
	Enabled       bool                               `json:"enabled"`
	SuccessPolicy NotificationSettings_SuccessPolicy `json:"successPolicy"`
	// DigestIntervalSeconds The period one digest covers, read only by the digest policy.
	DigestIntervalSeconds int `json:"digestIntervalSeconds"`
	// PushoverBaseURL The origin the application token and user key are sent to.
	PushoverBaseURL string `json:"pushoverBaseUrl"`
}

type SurfaceSettings struct {
	// Regions The Geofabrik region paths the surface index is built from. An empty list switches classification off.
	Regions []string `json:"regions"`
	// RebuildIntervalSeconds How often the index is rebuilt. Required whether or not a region is named: the rebuild schedule runs either way, and with no region it simply builds nothing.
	RebuildIntervalSeconds int `json:"rebuildIntervalSeconds"`
}

type BrowserBasemap struct {
	Name            string  `json:"name"`
	StyleURL        string  `json:"styleUrl"`
	StyleURLDark    *string `json:"styleUrlDark,omitempty"`
	DarkCartography *bool   `json:"darkCartography,omitempty"`
}

type WebUIConfig struct {
	Basemaps       []BrowserBasemap `json:"basemaps"`
	SourceBaseUrls *SourceBaseUrls  `json:"sourceBaseUrls,omitempty"`
	Identity       BrowserIdentity  `json:"identity"`
}

// BrowserIdentity Who the gate let through. There is one authorised address, so this names the reader rather than identifying them: it is how a session can be seen to be the one intended, and where the way out of it lives.
type BrowserIdentity struct {
	Email string `json:"email"`
	// SignOutURL Where to end the session, served by whatever fronts this service rather than by the service itself. Absent when nothing does, so the page offers no way out instead of a link that answers 404.
	SignOutURL *string `json:"signOutUrl,omitempty"`
}

type SourceBaseUrls struct {
	Veloplanner *string `json:"veloplanner,omitempty"`
	Komoot      *string `json:"komoot,omitempty"`
}

type SurfaceRange_Kind string

const (
	SurfaceRange_KindAsphalt   SurfaceRange_Kind = "asphalt"
	SurfaceRange_KindPaving    SurfaceRange_Kind = "paving"
	SurfaceRange_KindCompacted SurfaceRange_Kind = "compacted"
	SurfaceRange_KindGravel    SurfaceRange_Kind = "gravel"
	SurfaceRange_KindGround    SurfaceRange_Kind = "ground"
	SurfaceRange_KindUnknown   SurfaceRange_Kind = "unknown"
)

type SurfaceRange struct {
	Kind       SurfaceRange_Kind `json:"kind"`
	StartIndex int               `json:"startIndex"`
	EndIndex   int               `json:"endIndex"`
}

type GeoJSONLineString struct {
	Type        string      `json:"type"`
	Coordinates [][]float64 `json:"coordinates"`
}

type GeoJSONProperties_Surface struct {
	Ranges        []SurfaceRange `json:"ranges"`
	MatchedMetres float64        `json:"matchedMetres"`
}

type GeoJSONProperties struct {
	Provider           string                     `json:"provider"`
	RouteID            int64                      `json:"routeId"`
	StageOrder         int                        `json:"stageOrder"`
	Title              string                     `json:"title"`
	RouteName          string                     `json:"routeName"`
	StageName          string                     `json:"stageName"`
	DistanceMetres     float64                    `json:"distanceMetres"`
	AscentMetres       float64                    `json:"ascentMetres"`
	MaxGradientPercent float64                    `json:"maxGradientPercent"`
	PointCount         int                        `json:"pointCount"`
	Surface            *GeoJSONProperties_Surface `json:"surface,omitempty"`
	CumulativeSeconds  []float64                  `json:"cumulativeSeconds,omitempty"`
}

type GeoJSONFeature struct {
	Type       string            `json:"type"`
	Bbox       []float64         `json:"bbox"`
	Geometry   GeoJSONLineString `json:"geometry"`
	Properties GeoJSONProperties `json:"properties"`
}

type WeatherPoint struct {
	Time                            time.Time `json:"time"`
	TemperatureCelsius              float64   `json:"temperatureCelsius"`
	ApparentTemperatureCelsius      float64   `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres        float64   `json:"precipitationMillimetres"`
	PrecipitationProbabilityPercent float64   `json:"precipitationProbabilityPercent"`
	WindSpeedKmh                    float64   `json:"windSpeedKmh"`
	WindDirectionDegrees            float64   `json:"windDirectionDegrees"`
	WeatherCode                     int       `json:"weatherCode"`
}

type WeatherForecast struct {
	Points []WeatherPoint `json:"points"`
}
