// Code generated by libopenapi generator/golang. DO NOT EDIT.

package contract

import (
	"encoding/json"
	"time"
)

type Error_Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type Error struct {
	Error Error_Error `json:"error"`
}

type Health struct {
	Status string `json:"status"`
}

type Readiness struct {
	Status string `json:"status"`
}

type Unready_Reason string

const (
	Unready_ReasonStateUnreadable Unready_Reason = "state_unreadable"
	Unready_ReasonStateIncomplete Unready_Reason = "state_incomplete"
)

type Unready struct {
	Status string         `json:"status"`
	Reason Unready_Reason `json:"reason"`
}

type Accepted struct {
	Status string `json:"status"`
}

type TargetRoutes struct {
	Current int `json:"current"`
	Pending int `json:"pending"`
}

type TargetRun struct {
	CompletedAt time.Time `json:"completedAt"`
	Result      string    `json:"result"`
	Failure     *string   `json:"failure,omitempty"`
}

type TargetStatus_Convergence string

const (
	TargetStatus_ConvergenceCurrent      TargetStatus_Convergence = "current"
	TargetStatus_ConvergenceLagging      TargetStatus_Convergence = "lagging"
	TargetStatus_ConvergenceFailed       TargetStatus_Convergence = "failed"
	TargetStatus_ConvergenceUnauthorized TargetStatus_Convergence = "unauthorized"
)

type TargetStatus struct {
	ID string `json:"id"`
	// Owner The subject that owns this target. Present only for an admin caller: a non-admin's own target is already known to be theirs, and never sees another's here at all.
	Owner *string `json:"owner,omitempty"`
	// Own True when this target belongs to the calling subject. Present only for an admin caller, whose list also carries other riders' targets; a non-admin's list holds only their own.
	Own *bool `json:"own,omitempty"`
	// OwnerNickname The owning subject's display nickname, when its sign-in's ID token carried one. Present only alongside owner, and only as a label: never a key, and never present without owner too.
	OwnerNickname *string                  `json:"ownerNickname,omitempty"`
	Authorisation string                   `json:"authorisation"`
	Convergence   TargetStatus_Convergence `json:"convergence"`
	Routes        TargetRoutes             `json:"routes"`
	LastRun       *TargetRun               `json:"lastRun,omitempty"`
}

type RouteValidation struct {
	BiasPercent    float64 `json:"biasPercent"`
	MaePercent     float64 `json:"maePercent"`
	P90percent     float64 `json:"p90Percent"`
	EvaluatedRides int     `json:"evaluatedRides"`
}

type Route struct {
	Provider           string           `json:"provider"`
	SourceRouteID      int64            `json:"sourceRouteId"`
	StageOrder         int              `json:"stageOrder"`
	Title              string           `json:"title"`
	SourceRouteName    string           `json:"sourceRouteName"`
	RouteName          string           `json:"routeName"`
	SourceRevision     string           `json:"sourceRevision"`
	ContentHash        string           `json:"contentHash"`
	DistanceMetres     float64          `json:"distanceMetres"`
	AscentMetres       float64          `json:"ascentMetres"`
	DescentMetres      float64          `json:"descentMetres"`
	MaxGradientPercent float64          `json:"maxGradientPercent"`
	PointCount         int              `json:"pointCount"`
	MovingSeconds      *float64         `json:"movingSeconds,omitempty"`
	Validation         *RouteValidation `json:"validation,omitempty"`
}

type Activity struct {
	ID             int64                   `json:"id"`
	StartedAt      time.Time               `json:"startedAt"`
	DistanceMetres float64                 `json:"distanceMetres"`
	MovingSeconds  float64                 `json:"movingSeconds"`
	ElapsedSeconds float64                 `json:"elapsedSeconds"`
	AscentMetres   float64                 `json:"ascentMetres"`
	TypeID         int                     `json:"typeId"`
	LocationID     int                     `json:"locationId"`
	Metrics        *ActivityMetrics        `json:"metrics,omitempty"`
	Weather        *ActivityWeatherSummary `json:"weather,omitempty"`
	RouteMatch     *ActivityRouteMatch     `json:"routeMatch,omitempty"`
}

// ActivityRouteMatch The library route this ride was ridden on. Absent where the ride was ridden on none of them, or has not been matched yet; the two are not distinguished, because neither gives a route to show.
type ActivityRouteMatch struct {
	Provider      string `json:"provider"`
	SourceRouteID int64  `json:"sourceRouteId"`
	StageOrder    int    `json:"stageOrder"`
	// RouteCoverage Share of the route's length this ride covered, 0 to 1.
	RouteCoverage float64 `json:"routeCoverage"`
	// RideCoverage Share of this ride's length that lay on the route, 0 to 1.
	RideCoverage float64            `json:"rideCoverage"`
	Direction    RouteRideDirection `json:"direction"`
}

// RouteRideDirection Which way round the route the ride went. Unknown where it could not be told, which a route ridden out and back never can: it advances as far one way as the other.
type RouteRideDirection string

const (
	RouteRideDirectionForward RouteRideDirection = "forward"
	RouteRideDirectionReverse RouteRideDirection = "reverse"
	RouteRideDirectionUnknown RouteRideDirection = "unknown"
)

type RouteActivity struct {
	ID            int64              `json:"id"`
	RouteCoverage float64            `json:"routeCoverage"`
	RideCoverage  float64            `json:"rideCoverage"`
	Direction     RouteRideDirection `json:"direction"`
}

type RouteActivityList struct {
	Activities []RouteActivity `json:"activities"`
}

type Fitness struct {
	Days  []FitnessDay  `json:"days"`
	Weeks []FitnessWeek `json:"weeks"`
	// PowerCurve The power-duration curve over the window: the best mean power the rider held at each of a fixed set of durations, shortest first. Folded from what each ride was derived to hold, so a ride awaiting derivation is not in it yet. Measured power only -- an estimate from the track never enters the curve. Absent where no ride in the window carried a meter; a duration no ride was long enough for carries no point rather than a nought.
	PowerCurve []PowerCurvePoint `json:"powerCurve,omitempty"`
}

type PowerCurvePoint struct {
	// Seconds The duration this point is the best mean power over.
	Seconds int     `json:"seconds"`
	Watts   float64 `json:"watts"`
}

// FitnessDay One day of the timeline. Fitness is the long average of daily load, fatigue the short one, and form their difference: fresh above zero, buried below it. A day nobody rode carries no load and still decays both averages, which is what makes rest visible.
type FitnessDay struct {
	Date         string  `json:"date"`
	TrimpLoad    float64 `json:"trimpLoad"`
	TrimpFitness float64 `json:"trimpFitness"`
	TrimpFatigue float64 `json:"trimpFatigue"`
	TrimpForm    float64 `json:"trimpForm"`
	// TssLoad Power TSS where the ride carried a meter and hrTSS otherwise, so the series stays continuous across the day a power meter arrives.
	TssLoad    float64 `json:"tssLoad"`
	TssFitness float64 `json:"tssFitness"`
	TssFatigue float64 `json:"tssFatigue"`
	TssForm    float64 `json:"tssForm"`
}

// FitnessWeek How long one week held each of the five heart-rate zones.
type FitnessWeek struct {
	// WeekStart The Monday the week began on, in the service's own zone.
	WeekStart   string    `json:"weekStart"`
	ZoneSeconds []float64 `json:"zoneSeconds"`
}

// ActivityWeatherSummary What the ride was ridden through, in one line: the range the temperature moved over, the wind it was ridden in, and what fell. Absent for a ride nobody has asked the weather about, and for one the provider had nothing to say about.
type ActivityWeatherSummary struct {
	TemperatureMinCelsius float64 `json:"temperatureMinCelsius"`
	TemperatureMaxCelsius float64 `json:"temperatureMaxCelsius"`
	// WindSpeedKmh The mean over the ride's steps.
	WindSpeedKmh float64 `json:"windSpeedKmh"`
	// PrecipitationMillimetres The whole of what fell over the ride, not an hourly rate.
	PrecipitationMillimetres float64 `json:"precipitationMillimetres"`
	// WeatherCode The worst of the ride's steps rather than a mean: half a ride in rain was ridden in rain, and a mean of two codes names no weather.
	WeatherCode int `json:"weatherCode"`
}

// RideWeatherStep One step of what a ride was actually ridden through.
type RideWeatherStep struct {
	Time time.Time `json:"time"`
	// StepSeconds How long this step covers: 3600 for a ride answered by the reanalysis, 900 for a recent one answered by the forecast endpoint.
	StepSeconds                int     `json:"stepSeconds"`
	TemperatureCelsius         float64 `json:"temperatureCelsius"`
	ApparentTemperatureCelsius float64 `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres   float64 `json:"precipitationMillimetres"`
	// PrecipitationProbabilityPercent Absent for a ride old enough to be answered by reanalysis, which records what fell rather than what might have.
	PrecipitationProbabilityPercent *float64 `json:"precipitationProbabilityPercent,omitempty"`
	WindSpeedKmh                    float64  `json:"windSpeedKmh"`
	WindDirectionDegrees            float64  `json:"windDirectionDegrees"`
	WeatherCode                     int      `json:"weatherCode"`
	CloudCoverPercent               float64  `json:"cloudCoverPercent"`
}

// ActivityMetrics What this ride's recorded samples say about how hard it was: the load figures the rider's profile shapes, and the plain averages its sensors came to on their own. Absent from a ride that has none, and each part is absent on its own: a ride carries the sensors it carries, and a profile holds what the rider entered. Average speed is not here — it is distance over moving time, both of which the activity already carries, and is known even for a ride whose file was never readable.
type ActivityMetrics struct {
	// ZoneSeconds How long the ride held each of five heart-rate zones, easiest first. Cut from the lactate threshold where the profile has one and from the maximum otherwise.
	ZoneSeconds []float64 `json:"zoneSeconds,omitempty"`
	// ZoneBoundsBpm The four heart rates the five zones were cut at, ascending, in beats per minute. Worked out from the profile values this ride was derived against, not the rider's current ones. Present whenever zoneSeconds is.
	ZoneBoundsBpm []float64 `json:"zoneBoundsBpm,omitempty"`
	// Trimp Banister's training impulse: how long the ride lasted, weighted by how much of the rider's heart-rate reserve it held.
	Trimp *float64 `json:"trimp,omitempty"`
	// HeartRateTss An hour held at the lactate threshold is a hundred.
	HeartRateTss *float64 `json:"heartRateTss,omitempty"`
	// NormalizedPowerWatts From measured power only. An estimate worked out from the track never feeds this.
	NormalizedPowerWatts *float64 `json:"normalizedPowerWatts,omitempty"`
	IntensityFactor      *float64 `json:"intensityFactor,omitempty"`
	PowerTss             *float64 `json:"powerTss,omitempty"`
	// EstimatedPowerWatts The ride's average estimated power, for a bicycle carrying no meter. An estimate from a physics model over the recorded track, never a measurement: it feeds none of the figures above and must not be presented as though it were one of them. Absent for a ride that measured its own power, one with no usable track, and one whose rider has entered no mass.
	EstimatedPowerWatts *float64         `json:"estimatedPowerWatts,omitempty"`
	EstimateQuality     *EstimateQuality `json:"estimateQuality,omitempty"`
	// AverageHeartRateBpm The mean of the ride's recorded heart-rate samples. Absent for a ride that carried no strap.
	AverageHeartRateBpm *float64 `json:"averageHeartRateBpm,omitempty"`
	// MaxHeartRateBpm The highest heart rate the ride recorded.
	MaxHeartRateBpm *float64 `json:"maxHeartRateBpm,omitempty"`
	// AverageCadenceRpm The mean of the ride's recorded cadence samples. A reading of zero is a reading — a stopped rider's cadence — and counts towards it.
	AverageCadenceRpm *float64 `json:"averageCadenceRpm,omitempty"`
	// AveragePowerWatts The mean of the ride's measured power samples. Never fed by an estimate: a bicycle with no meter has no average power.
	AveragePowerWatts *float64 `json:"averagePowerWatts,omitempty"`
	// DecouplingPercent How much of the ride's power-to-heart-rate ratio was lost over its second half, as a percentage of its first. Positive is the usual direction: the same watts cost more beats later on. From measured power only, over a ride of at least an hour, and absent otherwise. It describes a steady aerobic ride; over intervals the two halves are different efforts and the figure says nothing about drift. See docs/specs/measurement.md §Decoupling and heat drift.
	DecouplingPercent *float64   `json:"decouplingPercent,omitempty"`
	HeatDrift         *HeatDrift `json:"heatDrift,omitempty"`
}

// HeatDrift What one ride says about riding warm: the heart rate it held in the rider's endurance band and the temperature it was recorded at. One ride is a point rather than a trend, and the drift is these points over a season. Absent for a ride with no measured power, no thermometer, too few samples in the band, or a rider who has entered no threshold power to place the band with.
type HeatDrift struct {
	// HeartRateBpm The mean heart rate over the ride's samples inside the band.
	HeartRateBpm float64 `json:"heartRateBpm"`
	// TemperatureCelsius The mean temperature over those same samples.
	TemperatureCelsius float64 `json:"temperatureCelsius"`
	// Samples How many samples the pair was read from.
	Samples int `json:"samples"`
}

// EstimateQuality What the estimate's own shape says about whether to trust it: a real ride's power is strongly autocorrelated sample to sample and moves by a few watts a second, and a series driven by recorder noise is neither. Present beside estimatedPowerWatts once the ride has been derived since these existed; a ride derived before then omits it until it is derived again. See docs/specs/measurement.md §Estimated power.
type EstimateQuality struct {
	// Autocorrelation The lag-1 Pearson correlation of the estimated watts with themselves shifted by one sample.
	Autocorrelation float64 `json:"autocorrelation"`
	// MeanAbsDeltaWattsPerSecond The mean absolute change in watts per second of elapsed time between consecutive samples.
	MeanAbsDeltaWattsPerSecond float64 `json:"meanAbsDeltaWattsPerSecond"`
	// ClipBiasWatts The mean amount the zero clamp added: clamped watts minus the unclamped force times speed it would otherwise have reported.
	ClipBiasWatts float64 `json:"clipBiasWatts"`
}

type ActivityList struct {
	Activities []Activity `json:"activities"`
}

type RouteList struct {
	Routes []Route `json:"routes"`
}

type SyncPhaseRun struct {
	LastCompletedAt time.Time `json:"lastCompletedAt"`
	LastResult      string    `json:"lastResult"`
	LastFailure     *string   `json:"lastFailure,omitempty"`
	SourceRoutes    int       `json:"sourceRoutes"`
	Created         int       `json:"created"`
	Updated         int       `json:"updated"`
	Deleted         int       `json:"deleted"`
}

type SyncPhases struct {
	Source  *SyncPhaseRun `json:"source,omitempty"`
	Targets *SyncPhaseRun `json:"targets,omitempty"`
}

type SyncActive_Phase string

const (
	SyncActive_PhaseSource  SyncActive_Phase = "source"
	SyncActive_PhaseTargets SyncActive_Phase = "targets"
)

type SyncActive struct {
	Phase    *SyncActive_Phase `json:"phase,omitempty"`
	StartsAt *time.Time        `json:"startsAt,omitempty"`
	Targets  int               `json:"targets"`
	Routes   TargetRoutes      `json:"routes"`
}

type SurfaceCoverage struct {
	Generation *string    `json:"generation,omitempty"`
	BuiltAt    *time.Time `json:"builtAt,omitempty"`
	Classified int        `json:"classified"`
	Total      int        `json:"total"`
	Incomplete int        `json:"incomplete"`
	// EnrichmentFailures How many stages currently have a surface or duration enrichment pass recorded against them as unable to finish.
	EnrichmentFailures int `json:"enrichmentFailures"`
}

type WahooRateLimit struct {
	Remaining  int        `json:"remaining"`
	ResetsAt   *time.Time `json:"resetsAt,omitempty"`
	ObservedAt time.Time  `json:"observedAt"`
}

type TrustedInventory struct {
	LastSuccessAt *time.Time `json:"lastSuccessAt,omitempty"`
	AgeSeconds    int        `json:"ageSeconds"`
	MaxAgeSeconds int        `json:"maxAgeSeconds"`
	Fresh         bool       `json:"fresh"`
}

type SyncStatus struct {
	State            string            `json:"state"`
	Active           *SyncActive       `json:"active,omitempty"`
	LastResult       *string           `json:"lastResult,omitempty"`
	LastCompletedAt  *time.Time        `json:"lastCompletedAt,omitempty"`
	SourceRoutes     int               `json:"sourceRoutes"`
	Created          int               `json:"created"`
	Updated          int               `json:"updated"`
	Deleted          int               `json:"deleted"`
	Phases           SyncPhases        `json:"phases"`
	Surface          SurfaceCoverage   `json:"surface"`
	WahooRateLimit   *WahooRateLimit   `json:"wahooRateLimit,omitempty"`
	TrustedInventory *TrustedInventory `json:"trustedInventory,omitempty"`
}

type Build struct {
	Revision    string  `json:"revision"`
	ImageDigest *string `json:"imageDigest,omitempty"`
}

type Status struct {
	Ready     bool           `json:"ready"`
	Converged bool           `json:"converged"`
	Build     *Build         `json:"build,omitempty"`
	Targets   []TargetStatus `json:"targets"`
	Sync      SyncStatus     `json:"sync"`
}

type SyncRun_Phase string

const (
	SyncRun_PhaseSource  SyncRun_Phase = "source"
	SyncRun_PhaseTargets SyncRun_Phase = "targets"
)

type SyncRun struct {
	Reference    string        `json:"reference"`
	Phase        SyncRun_Phase `json:"phase"`
	CompletedAt  time.Time     `json:"completedAt"`
	Result       string        `json:"result"`
	Failure      *string       `json:"failure,omitempty"`
	SourceRoutes int           `json:"sourceRoutes"`
	Created      int           `json:"created"`
	Updated      int           `json:"updated"`
	Deleted      int           `json:"deleted"`
}

type SyncRunPage struct {
	Runs []SyncRun `json:"runs"`
	Next *string   `json:"next,omitempty"`
}

// Settings_SecretsSet Whether each credential is stored. This is the whole of what any observable surface is told about one: never the value, only that there is one to replace.
type Settings_SecretsSet struct {
	AdditionalProperties map[string]bool `json:"-"`
}

func (m *Settings_SecretsSet) UnmarshalJSON(data []byte) error {
	type Alias Settings_SecretsSet
	var known Alias
	if err := json.Unmarshal(data, &known); err != nil {
		return err
	}
	*m = Settings_SecretsSet(known)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	if len(raw) == 0 {
		return nil
	}
	m.AdditionalProperties = make(map[string]bool, len(raw))
	for key, value := range raw {
		var decoded bool
		if err := json.Unmarshal(value, &decoded); err != nil {
			return err
		}
		m.AdditionalProperties[key] = decoded
	}
	return nil
}

func (m Settings_SecretsSet) MarshalJSON() ([]byte, error) {
	type Alias Settings_SecretsSet
	encoded, err := json.Marshal(Alias(m))
	if err != nil {
		return nil, err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(encoded, &object); err != nil {
		return nil, err
	}
	for key, value := range m.AdditionalProperties {
		encodedValue, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		object[key] = encodedValue
	}
	return json.Marshal(object)
}

// Settings The settings held in the state database rather than in the configuration file, which take effect on the next run or the next request rather than on the next restart.
type Settings struct {
	// Timezone The IANA zone this service reads local time in: what a scheduled time of day means, and what hour a forecast describes.
	Timezone      string               `json:"timezone"`
	Sync          SyncSettings         `json:"sync"`
	Notifications NotificationSettings `json:"notifications"`
	Basemaps      []BrowserBasemap     `json:"basemaps"`
	Surface       SurfaceSettings      `json:"surface"`
	Wahoo         WahooSettings        `json:"wahoo"`
	// Sources The libraries a run reads, in the order it reads them. An empty list is a service nobody has configured yet, not an error.
	Sources   []SourceSettings `json:"sources"`
	RideModel RideModelStatus  `json:"rideModel"`
	// Alerts Every alert this service can raise, and whether it is delivered. An alert nobody has ruled on is delivered: a fault nobody has heard of is the one worth hearing about.
	Alerts []AlertSetting `json:"alerts"`
	// SecretsSet Whether each credential is stored. This is the whole of what any observable surface is told about one: never the value, only that there is one to replace.
	SecretsSet map[string]bool `json:"secretsSet"`
	// Missing The settings still to be entered, in the order the page offers them. Everything a run needs is here, and so are the Pushover credentials while notifications are on, which no run needs but every notification does. Empty is a configured service.
	Missing []string `json:"missing"`
}

// WahooApplicationUpdate The registered application, without the slots it writes to. Those are replaced on their own.
type WahooApplicationUpdate struct {
	// APIBaseURL The origin route reads and writes are sent to.
	APIBaseURL string `json:"apiBaseUrl"`
	// OauthBaseURL The origin an authorization and a token refresh are sent to.
	OauthBaseURL string `json:"oauthBaseUrl"`
	// ClientID The registered application's public identifier.
	ClientID string `json:"clientId"`
	// ClientSecret The application's secret, sent only when it was typed into the form. Left out it keeps the stored value, which is how a page that was never told the secret can save the rest of the application; sent empty it removes the credential.
	ClientSecret *string `json:"clientSecret,omitempty"`
	// WebhookToken The token Wahoo carries in every webhook body, sent only when it was typed into the form. It follows the same rule as the client secret: left out it keeps the stored value, sent empty it removes the credential, and it is never read back.
	WebhookToken *string `json:"webhookToken,omitempty"`
}

// SourceUpdate One library, and the account it is read with.
type SourceUpdate struct {
	// Read Whether a run reads this library at all. Off takes it out of the list without forgetting the account it was read with.
	Read bool `json:"read"`
	// BaseURL The source's own web application, which is both the origin the service reads and the one a route is linked back to.
	BaseURL string `json:"baseUrl"`
	// Email The account's email address, sent only when it was typed. The rules the application secret follows apply here too.
	Email *string `json:"email,omitempty"`
	// Password The account's password, on the same terms as the email address.
	Password *string `json:"password,omitempty"`
}

type AlertSetting struct {
	// Task The background activity the alert is about.
	Task string `json:"task"`
	// Alert The stable reason the alert names. It never carries provider text, a route name, or an upstream identifier.
	Alert string `json:"alert"`
	// Enabled Whether this alert is delivered.
	Enabled bool `json:"enabled"`
	// Decided Whether anybody has ruled on it. An alert nobody has ruled on is delivered, which is not the same as one somebody switched on.
	Decided bool `json:"decided"`
}

type AlertsUpdate struct {
	// Alerts What the operator has decided. Deciding is what creates a record, so an alert left out of this list keeps whatever it had.
	Alerts []AlertDecision `json:"alerts"`
}

type AlertDecision struct {
	Task    string `json:"task"`
	Alert   string `json:"alert"`
	Enabled bool   `json:"enabled"`
}

type NotificationsUpdate struct {
	// Enabled The switch for the whole channel. Off, nothing is sent at all: a failure, a blocked run, a recovery and a task that has stopped succeeding are held back as surely as a routine success is. Which alerts are sent while it is on is a decision per task and per reason, held in the alert matrix.
	Enabled bool `json:"enabled"`
	// PushoverBaseURL The origin the application token and user key are sent to.
	PushoverBaseURL string `json:"pushoverBaseUrl"`
	// ApplicationToken The Pushover application's token, sent only when it was typed. The rules the application secret follows apply here too.
	ApplicationToken *string `json:"applicationToken,omitempty"`
	// UserKey The recipient key, on the same terms as the application token.
	UserKey *string `json:"userKey,omitempty"`
}

type BasemapsUpdate struct {
	Basemaps []BrowserBasemap `json:"basemaps"`
}

type TaskScheduleUpdate struct {
	// Enabled Whether the schedule may start this task. It governs unattended runs only.
	Enabled bool `json:"enabled"`
}

type TaskList struct {
	Tasks []Task `json:"tasks"`
}

type Task struct {
	// Name What a trigger asks for.
	Name string `json:"name"`
	// Scheduled Whether the task has a schedule at all.
	Scheduled bool `json:"scheduled"`
	// Enabled Whether the schedule may start it. A task nobody has ruled on runs. It governs unattended runs only.
	Enabled bool `json:"enabled"`
	// Running How many attempts of this task are in flight.
	Running int `json:"running"`
	// IntervalSeconds The gap between runs for a task on a fixed schedule. Absent for a task with no schedule, or a calendar one, whose gap changes with the wall clock.
	IntervalSeconds *int `json:"intervalSeconds,omitempty"`
	// NextRunAt When the next scheduled run is due. Absent for a task nothing schedules, and while the task's own scheduled run is under way. A run somebody asked for does not disturb the schedule, so this stays put during one.
	NextRunAt *time.Time `json:"nextRunAt,omitempty"`
}

// TaskRun One recorded attempt. It carries the aggregate record and nothing about what the attempt touched.
type TaskRun struct {
	Task string `json:"task"`
	// Argument What the attempt was over, such as a target slot. Absent for a task that covers only one thing.
	Argument *string `json:"argument,omitempty"`
	// Trigger What started the attempt: `schedule`, `manual`, or `chain`. Absent for an attempt recorded before this was written down.
	Trigger    *string   `json:"trigger,omitempty"`
	StartedAt  time.Time `json:"startedAt"`
	FinishedAt time.Time `json:"finishedAt"`
	Outcome    string    `json:"outcome"`
	// Detail A stable, safe-to-display reason for the outcome. Never provider text, a route name, or an upstream identifier.
	Detail *string `json:"detail,omitempty"`
	// Reference The name an alert about this attempt carries.
	Reference string `json:"reference"`
}

type TaskRunPage struct {
	Runs []TaskRun `json:"runs"`
	Next *string   `json:"next,omitempty"`
}

type RiderProfile struct {
	Profile     RiderParameters  `json:"profile"`
	Suggestions RiderSuggestions `json:"suggestions"`
}

// RiderParameters One rider's own body and equipment. Every parameter is optional: one the rider has not entered is absent rather than zero, because nothing downstream can use a zero heart rate or a massless bicycle.
type RiderParameters struct {
	MaxHeartRateBpm     *float64 `json:"maxHeartRateBpm,omitempty"`
	RestingHeartRateBpm *float64 `json:"restingHeartRateBpm,omitempty"`
	// ThresholdHeartRateBpm The lactate threshold rate heart-rate zones are cut at.
	ThresholdHeartRateBpm         *float64 `json:"thresholdHeartRateBpm,omitempty"`
	FunctionalThresholdPowerWatts *float64 `json:"functionalThresholdPowerWatts,omitempty"`
	RiderMassKg                   *float64 `json:"riderMassKg,omitempty"`
	// BikeMassKg The bicycle and everything carried on it.
	BikeMassKg *float64 `json:"bikeMassKg,omitempty"`
}

// RiderSuggestions What the rider's rides of the last ninety days say some of these numbers could be, offered beside the controls and stored nowhere. A parameter no ride carried a sensor for is absent rather than zero.
type RiderSuggestions struct {
	// MaxHeartRateBpm The highest heart rate held over a rolling minute.
	MaxHeartRateBpm *float64 `json:"maxHeartRateBpm,omitempty"`
	// FunctionalThresholdPowerWatts The best twenty-minute average power, taken at 95%.
	FunctionalThresholdPowerWatts *float64            `json:"functionalThresholdPowerWatts,omitempty"`
	Stopping                      *StoppingSuggestion `json:"stopping,omitempty"`
}

// StoppingSuggestion How long the rider stood still per hour of moving over their own outdoor rides under their own power in the last ninety days, as a median and the quartiles either side of it. An indoor ride stands still without stopping and a motor does not stop for a cafe, so neither is counted. Measured over the caller's own targets alone and never pooled across riders, and absent until enough rides carry it.
type StoppingSuggestion struct {
	MedianSecondsPerHour        float64 `json:"medianSecondsPerHour"`
	LowerQuartileSecondsPerHour float64 `json:"lowerQuartileSecondsPerHour"`
	UpperQuartileSecondsPerHour float64 `json:"upperQuartileSecondsPerHour"`
	// Rides How many of the rider's rides the figures were read from.
	Rides int `json:"rides"`
}

type TimezoneUpdate struct {
	// Timezone An IANA zone name this service can load, such as Europe/Berlin.
	Timezone string `json:"timezone"`
}

type SyncSettings struct {
	// AllowEmptySourceDeletion Whether a source that reports an empty library may delete the last routes a target holds. It stays on until it is turned off again.
	AllowEmptySourceDeletion bool `json:"allowEmptySourceDeletion"`
	// StaleAfterSeconds How long the trusted source inventory may go without a successful refresh before it is reported and notified as stale.
	StaleAfterSeconds int `json:"staleAfterSeconds"`
	// InitialDelaySeconds How long after start the first run is attempted. It is read by the start it delays, so an edit reaches the next restart rather than the next run.
	InitialDelaySeconds int `json:"initialDelaySeconds"`
}

type NotificationSettings struct {
	// Enabled The switch for the whole channel. Off, nothing is sent at all: a failure, a blocked run, a recovery and a task that has stopped succeeding are held back as surely as a routine success is. Which alerts are sent while it is on is a decision per task and per reason, held in the alert matrix.
	Enabled bool `json:"enabled"`
	// PushoverBaseURL The origin the application token and user key are sent to.
	PushoverBaseURL string `json:"pushoverBaseUrl"`
}

type WahooSettings struct {
	// APIBaseURL The origin route reads and writes are sent to. Empty until the application is registered, which is a service that runs nothing rather than one that is broken.
	APIBaseURL string `json:"apiBaseUrl"`
	// OauthBaseURL The origin an authorization and a token refresh are sent to.
	OauthBaseURL string `json:"oauthBaseUrl"`
	// ClientID The registered application's public identifier. Its secret is not here: it is written through secrets and read back only as set.
	ClientID string `json:"clientId"`
}

type SourceSettings_Provider string

const (
	SourceSettings_ProviderVeloplanner SourceSettings_Provider = "veloplanner"
	SourceSettings_ProviderKomoot      SourceSettings_Provider = "komoot"
)

type SourceSettings struct {
	Provider SourceSettings_Provider `json:"provider"`
	// BaseURL The source's own web application, which is both the origin the service reads and the one a route is linked back to.
	BaseURL string `json:"baseUrl"`
}

// RideModelStatus_Source Whether these are the built-in values every deployment starts with or the ones a calibration fitted.
type RideModelStatus_Source string

const (
	RideModelStatus_SourceDefault    RideModelStatus_Source = "default"
	RideModelStatus_SourceCalibrated RideModelStatus_Source = "calibrated"
)

// RideModelStatus The coefficient pair predicted moving time is priced with. Read-only: it is replaced by a calibration, not by an operator.
type RideModelStatus struct {
	// SecondsPerKm Seconds added per kilometre ridden.
	SecondsPerKm float64 `json:"secondsPerKm"`
	// SecondsPerAscentM Seconds added per metre climbed.
	SecondsPerAscentM float64 `json:"secondsPerAscentM"`
	// Source Whether these are the built-in values every deployment starts with or the ones a calibration fitted.
	Source RideModelStatus_Source `json:"source"`
	// CalibrationCutoff The last day of riding the fit that produced them read.
	CalibrationCutoff *string `json:"calibrationCutoff,omitempty"`
	// EvaluatedRides How many unseen rides the fit's error was measured over. Zero is not measured, which is what the built-in pair always reports.
	EvaluatedRides int `json:"evaluatedRides"`
}

type SurfaceSettings struct {
	// Regions The Geofabrik region paths the surface index is built from. An empty list switches classification off.
	Regions []string `json:"regions"`
	// RebuildIntervalSeconds How often the index is rebuilt. Required whether or not a region is named: the rebuild schedule runs either way, and with no region it simply builds nothing.
	RebuildIntervalSeconds int `json:"rebuildIntervalSeconds"`
}

type BrowserBasemap struct {
	Name            string  `json:"name"`
	StyleURL        string  `json:"styleUrl"`
	StyleURLDark    *string `json:"styleUrlDark,omitempty"`
	DarkCartography *bool   `json:"darkCartography,omitempty"`
}

type WebUIConfig struct {
	Basemaps       []BrowserBasemap `json:"basemaps"`
	SourceBaseUrls *SourceBaseUrls  `json:"sourceBaseUrls,omitempty"`
	// Timezone The IANA zone the service reads local time in.
	Timezone string          `json:"timezone"`
	Identity BrowserIdentity `json:"identity"`
}

// BrowserIdentity Who the gate let through. It names the reader rather than identifying them: it is how a session can be seen to be the one intended.
type BrowserIdentity struct {
	Display string `json:"display"`
	// Admin Whether this subject holds cross-subject rights. Asserted by the same Auth0 Action that separately decides whether this subject may sign in at all — that decision is what admits the session in the first place, and holds regardless of this field's value.
	Admin bool `json:"admin"`
}

type SourceBaseUrls struct {
	Veloplanner *string `json:"veloplanner,omitempty"`
	Komoot      *string `json:"komoot,omitempty"`
}

type SurfaceRange_Kind string

const (
	SurfaceRange_KindAsphalt   SurfaceRange_Kind = "asphalt"
	SurfaceRange_KindPaving    SurfaceRange_Kind = "paving"
	SurfaceRange_KindCompacted SurfaceRange_Kind = "compacted"
	SurfaceRange_KindGravel    SurfaceRange_Kind = "gravel"
	SurfaceRange_KindGround    SurfaceRange_Kind = "ground"
	SurfaceRange_KindUnknown   SurfaceRange_Kind = "unknown"
)

type SurfaceRange struct {
	Kind       SurfaceRange_Kind `json:"kind"`
	StartIndex int               `json:"startIndex"`
	EndIndex   int               `json:"endIndex"`
}

type GeoJSONLineString struct {
	Type        string      `json:"type"`
	Coordinates [][]float64 `json:"coordinates"`
}

type ActivityTrackLineString struct {
	Type        string      `json:"type"`
	Coordinates [][]float64 `json:"coordinates"`
}

type ActivityTrack struct {
	Type       string                   `json:"type"`
	Bbox       []float64                `json:"bbox,omitempty"`
	Geometry   *ActivityTrackLineString `json:"geometry"`
	Properties ActivityTrackProperties  `json:"properties"`
}

type ActivityTrackProperties_State string

const (
	ActivityTrackProperties_StateStored     ActivityTrackProperties_State = "stored"
	ActivityTrackProperties_StatePending    ActivityTrackProperties_State = "pending"
	ActivityTrackProperties_StateEmpty      ActivityTrackProperties_State = "empty"
	ActivityTrackProperties_StateUnreadable ActivityTrackProperties_State = "unreadable"
)

type ActivityTrackProperties struct {
	State ActivityTrackProperties_State `json:"state"`
	// AltitudeMetres The altitude at each coordinate, indexed 1:1 with them; null where that sample recorded none. Omitted, never all null, when no positioned sample recorded an altitude.
	AltitudeMetres []*float64 `json:"altitudeMetres,omitempty"`
	// Weather What this ride was actually ridden through, one row per step of it, asked of the weather provider once after the ride's samples were stored. Absent for a ride nobody has asked about yet and for one the provider had nothing to say about.
	Weather []RideWeatherStep `json:"weather,omitempty"`
	// EstimatedPowerWatts Power this service worked out from the track itself, for a bicycle carrying no meter, indexed 1:1 with the coordinates; null where no estimate was made. Deliberately not `powerWatts`: it is an estimate from a physics model over position, altitude and time, never a measurement, and nothing may present it as one. Omitted entirely for a ride that carries real power, one with no usable track, and one whose rider has entered no mass.
	EstimatedPowerWatts []*float64 `json:"estimatedPowerWatts,omitempty"`
}

// ActivitySeriesName A series of a ride's samples. Every one but `speed` is read from the samples as recorded; `speed` is worked out from the distance covered between one sample and the next.
type ActivitySeriesName string

const (
	ActivitySeriesNameHeartRate   ActivitySeriesName = "heartRate"
	ActivitySeriesNameCadence     ActivitySeriesName = "cadence"
	ActivitySeriesNamePower       ActivitySeriesName = "power"
	ActivitySeriesNameTemperature ActivitySeriesName = "temperature"
	ActivitySeriesNameSpeed       ActivitySeriesName = "speed"
)

type ActivitySeries struct {
	Series ActivitySeriesName `json:"series"`
	// Values The series at each coordinate of the activity's track, indexed 1:1 with them; null where that sample recorded nothing. Units are beats per minute, revolutions per minute, watts, degrees Celsius and kilometres per hour respectively. A reading of zero is a reading — a stopped rider's cadence — and never stands in for an absent one.
	Values []*float64 `json:"values"`
}

// ActivitySplit One kilometre of a ride. A ride's last split is whatever was left over, which is what distanceMetres says; every other figure is of that stretch alone.
type ActivitySplit struct {
	DistanceMetres float64 `json:"distanceMetres"`
	// MovingSeconds The seconds the odometer advanced over. A stretch nothing was recorded across - a gap in the recording - carries nought.
	MovingSeconds float64 `json:"movingSeconds"`
	// AscentMetres The climbing parts of the stretch summed, unsmoothed, exactly as a route's own gain is cut. Nought for a ride that recorded no altitude.
	AscentMetres float64 `json:"ascentMetres"`
	// HeartRateBpm The mean of the samples over this stretch that carried a reading. Absent where none did.
	HeartRateBpm *float64 `json:"heartRateBpm,omitempty"`
	// PowerWatts The mean of the stretch's measured power. Never fed by an estimate: a bicycle with no meter has no average power.
	PowerWatts *float64 `json:"powerWatts,omitempty"`
}

type ActivitySplits struct {
	Splits []ActivitySplit `json:"splits"`
}

type GeoJSONProperties_Surface struct {
	Ranges        []SurfaceRange `json:"ranges"`
	MatchedMetres float64        `json:"matchedMetres"`
}

type GeoJSONProperties struct {
	Provider           string                     `json:"provider"`
	SourceRouteID      int64                      `json:"sourceRouteId"`
	StageOrder         int                        `json:"stageOrder"`
	Title              string                     `json:"title"`
	SourceRouteName    string                     `json:"sourceRouteName"`
	RouteName          string                     `json:"routeName"`
	DistanceMetres     float64                    `json:"distanceMetres"`
	AscentMetres       float64                    `json:"ascentMetres"`
	DescentMetres      float64                    `json:"descentMetres"`
	MaxGradientPercent float64                    `json:"maxGradientPercent"`
	PointCount         int                        `json:"pointCount"`
	Surface            *GeoJSONProperties_Surface `json:"surface,omitempty"`
	CumulativeSeconds  []float64                  `json:"cumulativeSeconds,omitempty"`
}

type GeoJSONFeature struct {
	Type       string            `json:"type"`
	Bbox       []float64         `json:"bbox"`
	Geometry   GeoJSONLineString `json:"geometry"`
	Properties GeoJSONProperties `json:"properties"`
}

type WeatherPoint struct {
	Time                            time.Time `json:"time"`
	TemperatureCelsius              float64   `json:"temperatureCelsius"`
	ApparentTemperatureCelsius      float64   `json:"apparentTemperatureCelsius"`
	PrecipitationMillimetres        float64   `json:"precipitationMillimetres"`
	PrecipitationProbabilityPercent float64   `json:"precipitationProbabilityPercent"`
	WindSpeedKmh                    float64   `json:"windSpeedKmh"`
	WindDirectionDegrees            float64   `json:"windDirectionDegrees"`
	WeatherCode                     int       `json:"weatherCode"`
	CloudCoverPercent               float64   `json:"cloudCoverPercent"`
}

type WeatherForecast struct {
	Points []WeatherPoint `json:"points"`
}

// WeatherGridManifest The provider's own capture manifest, relayed rather than reshaped: additional fields it publishes are passed through rather than rejected.
type WeatherGridManifest struct {
	ReferenceTime string   `json:"reference_time"`
	ValidTimes    []string `json:"valid_times"`
}
