// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

// Defines values for ReadinessStatus.
const (
	Ready ReadinessStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyReason.
const (
	StateIncomplete UnreadyReason = "state_incomplete"
	StateUnreadable UnreadyReason = "state_unreadable"
)

// Valid indicates whether the value is a known member of the UnreadyReason enum.
func (e UnreadyReason) Valid() bool {
	switch e {
	case StateIncomplete:
		return true
	case StateUnreadable:
		return true
	default:
		return false
	}
}

// Defines values for UnreadyStatus.
const (
	UnreadyStatusUnready UnreadyStatus = "unready"
)

// Valid indicates whether the value is a known member of the UnreadyStatus enum.
func (e UnreadyStatus) Valid() bool {
	switch e {
	case UnreadyStatusUnready:
		return true
	default:
		return false
	}
}

// Readiness defines model for Readiness.
type Readiness struct {
	Status ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// Unready defines model for Unready.
type Unready struct {
	Reason UnreadyReason `json:"reason"`
	Status UnreadyStatus `json:"status"`
}

// UnreadyReason defines model for Unready.Reason.
type UnreadyReason string

// UnreadyStatus defines model for Unready.Status.
type UnreadyStatus string
