// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const activityExists = `-- name: ActivityExists :one
SELECT EXISTS(SELECT 1 FROM activities WHERE target_slot = ? AND workout_id = ?)
`

type ActivityExistsParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) ActivityExists(ctx context.Context, arg ActivityExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, activityExists, arg.TargetSlot, arg.WorkoutID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const applyActivitySessionTotals = `-- name: ApplyActivitySessionTotals :exec
UPDATE activities SET
  distance_metres = COALESCE(?1, distance_metres),
  moving_seconds  = COALESCE(?2, moving_seconds),
  elapsed_seconds = COALESCE(?3, elapsed_seconds),
  ascent_metres   = COALESCE(?4, ascent_metres)
WHERE target_slot = ?5 AND workout_id = ?6
`

type ApplyActivitySessionTotalsParams struct {
	DistanceMetres sql.NullFloat64
	MovingSeconds  sql.NullFloat64
	ElapsedSeconds sql.NullFloat64
	AscentMetres   sql.NullFloat64
	TargetSlot     string
	WorkoutID      int64
}

func (q *Queries) ApplyActivitySessionTotals(ctx context.Context, arg ApplyActivitySessionTotalsParams) error {
	_, err := q.db.ExecContext(ctx, applyActivitySessionTotals,
		arg.DistanceMetres,
		arg.MovingSeconds,
		arg.ElapsedSeconds,
		arg.AscentMetres,
		arg.TargetSlot,
		arg.WorkoutID,
	)
	return err
}

const deleteActivityListings = `-- name: DeleteActivityListings :exec
DELETE FROM activity_listings WHERE target_slot = ?
`

func (q *Queries) DeleteActivityListings(ctx context.Context, targetSlot string) error {
	_, err := q.db.ExecContext(ctx, deleteActivityListings, targetSlot)
	return err
}

const deleteActivityRecords = `-- name: DeleteActivityRecords :exec
DELETE FROM activity_records WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivityRecordsParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityRecords(ctx context.Context, arg DeleteActivityRecordsParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityRecords, arg.TargetSlot, arg.WorkoutID)
	return err
}

const deleteActivitySession = `-- name: DeleteActivitySession :exec
DELETE FROM activity_session WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivitySessionParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivitySession(ctx context.Context, arg DeleteActivitySessionParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivitySession, arg.TargetSlot, arg.WorkoutID)
	return err
}

const deleteActivitySkip = `-- name: DeleteActivitySkip :exec
DELETE FROM activity_skips WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivitySkipParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivitySkip(ctx context.Context, arg DeleteActivitySkipParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivitySkip, arg.TargetSlot, arg.WorkoutID)
	return err
}

const deleteTrainerCopyActivity = `-- name: DeleteTrainerCopyActivity :execrows
DELETE FROM activities
WHERE target_slot = ?1 AND provider = 'wahoo'
  AND workout_type_id IN (SELECT value FROM json_each(CAST(?2 AS TEXT)))
  AND started_at_unix >= ?3 AND started_at_unix <= ?4
`

type DeleteTrainerCopyActivityParams struct {
	TargetSlot    string
	IndoorTypeIds string
	FromUnix      int64
	ToUnix        int64
}

// The head unit's copy of an indoor ride Zwift also recorded. Every derived row
// goes with it through the existing cascades; the skip and listing rows do not,
// and must not: those mirror the account rather than what is stored.
func (q *Queries) DeleteTrainerCopyActivity(ctx context.Context, arg DeleteTrainerCopyActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrainerCopyActivity,
		arg.TargetSlot,
		arg.IndoorTypeIds,
		arg.FromUnix,
		arg.ToUnix,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActivityRawSummary = `-- name: GetActivityRawSummary :one
SELECT raw_summary_json
FROM activities
WHERE target_slot = ? AND workout_id = ?
`

type GetActivityRawSummaryParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) GetActivityRawSummary(ctx context.Context, arg GetActivityRawSummaryParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getActivityRawSummary, arg.TargetSlot, arg.WorkoutID)
	var raw_summary_json []byte
	err := row.Scan(&raw_summary_json)
	return raw_summary_json, err
}

const getActivityRecordsState = `-- name: GetActivityRecordsState :one
SELECT records_state FROM activities WHERE target_slot = ? AND workout_id = ?
`

type GetActivityRecordsStateParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) GetActivityRecordsState(ctx context.Context, arg GetActivityRecordsStateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getActivityRecordsState, arg.TargetSlot, arg.WorkoutID)
	var records_state string
	err := row.Scan(&records_state)
	return records_state, err
}

const insertActivityListing = `-- name: InsertActivityListing :exec
INSERT INTO activity_listings (
  target_slot, workout_id, started_at_unix, workout_type_id, workout_type_location_id, read_at_unix
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  started_at_unix = excluded.started_at_unix,
  workout_type_id = excluded.workout_type_id,
  workout_type_location_id = excluded.workout_type_location_id,
  read_at_unix = excluded.read_at_unix
`

type InsertActivityListingParams struct {
	TargetSlot            string
	WorkoutID             int64
	StartedAtUnix         int64
	WorkoutTypeID         int64
	WorkoutTypeLocationID int64
	ReadAtUnix            int64
}

func (q *Queries) InsertActivityListing(ctx context.Context, arg InsertActivityListingParams) error {
	_, err := q.db.ExecContext(ctx, insertActivityListing,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.StartedAtUnix,
		arg.WorkoutTypeID,
		arg.WorkoutTypeLocationID,
		arg.ReadAtUnix,
	)
	return err
}

const listActivitiesAwaitingRecords = `-- name: ListActivitiesAwaitingRecords :many
SELECT workout_id, raw_summary_json
FROM activities
WHERE target_slot = ?1
  AND provider = ?2
  AND (records_state = 'pending'
    OR (records_state = 'stored' AND records_version < ?3))
ORDER BY records_state <> 'pending', started_at_unix DESC, workout_id DESC
LIMIT ?4
`

type ListActivitiesAwaitingRecordsParams struct {
	TargetSlot     string
	Provider       string
	RecordsVersion int64
	RowLimit       int64
}

type ListActivitiesAwaitingRecordsRow struct {
	WorkoutID      int64
	RawSummaryJson []byte
}

func (q *Queries) ListActivitiesAwaitingRecords(ctx context.Context, arg ListActivitiesAwaitingRecordsParams) ([]ListActivitiesAwaitingRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesAwaitingRecords,
		arg.TargetSlot,
		arg.Provider,
		arg.RecordsVersion,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesAwaitingRecordsRow{}
	for rows.Next() {
		var i ListActivitiesAwaitingRecordsRow
		if err := rows.Scan(&i.WorkoutID, &i.RawSummaryJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitiesBetween = `-- name: ListActivitiesBetween :many
SELECT workout_id, workout_type_id, workout_type_location_id, started_at_unix,
  distance_metres, moving_seconds, elapsed_seconds, ascent_metres, provider
FROM activities
WHERE target_slot = ?1 AND started_at_unix >= ?2 AND started_at_unix < ?3
ORDER BY started_at_unix DESC
LIMIT ?4
`

type ListActivitiesBetweenParams struct {
	TargetSlot string
	FromUnix   int64
	ToUnix     int64
	RowLimit   int64
}

type ListActivitiesBetweenRow struct {
	WorkoutID             int64
	WorkoutTypeID         int64
	WorkoutTypeLocationID int64
	StartedAtUnix         int64
	DistanceMetres        float64
	MovingSeconds         float64
	ElapsedSeconds        float64
	AscentMetres          float64
	Provider              string
}

func (q *Queries) ListActivitiesBetween(ctx context.Context, arg ListActivitiesBetweenParams) ([]ListActivitiesBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesBetween,
		arg.TargetSlot,
		arg.FromUnix,
		arg.ToUnix,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesBetweenRow{}
	for rows.Next() {
		var i ListActivitiesBetweenRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.WorkoutTypeID,
			&i.WorkoutTypeLocationID,
			&i.StartedAtUnix,
			&i.DistanceMetres,
			&i.MovingSeconds,
			&i.ElapsedSeconds,
			&i.AscentMetres,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityIDs = `-- name: ListActivityIDs :many
SELECT workout_id FROM activities WHERE target_slot = ? AND provider = ? ORDER BY workout_id
`

type ListActivityIDsParams struct {
	TargetSlot string
	Provider   string
}

func (q *Queries) ListActivityIDs(ctx context.Context, arg ListActivityIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActivityIDs, arg.TargetSlot, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workout_id int64
		if err := rows.Scan(&workout_id); err != nil {
			return nil, err
		}
		items = append(items, workout_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityListings = `-- name: ListActivityListings :many
SELECT workout_id, started_at_unix, workout_type_id, workout_type_location_id, read_at_unix
FROM activity_listings
WHERE target_slot = ?
ORDER BY started_at_unix, workout_id
`

type ListActivityListingsRow struct {
	WorkoutID             int64
	StartedAtUnix         int64
	WorkoutTypeID         int64
	WorkoutTypeLocationID int64
	ReadAtUnix            int64
}

func (q *Queries) ListActivityListings(ctx context.Context, targetSlot string) ([]ListActivityListingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityListings, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityListingsRow{}
	for rows.Next() {
		var i ListActivityListingsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.StartedAtUnix,
			&i.WorkoutTypeID,
			&i.WorkoutTypeLocationID,
			&i.ReadAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityRides = `-- name: ListActivityRides :many
SELECT target_slot, started_at_unix, distance_metres, moving_seconds, ascent_metres
FROM activities
WHERE started_at_unix >= ?1
  AND workout_type_id IN (/*SLICE:workout_type_ids*/?)
ORDER BY started_at_unix
`

type ListActivityRidesParams struct {
	SinceUnix      int64
	WorkoutTypeIds []int64
}

type ListActivityRidesRow struct {
	TargetSlot     string
	StartedAtUnix  int64
	DistanceMetres float64
	MovingSeconds  float64
	AscentMetres   float64
}

func (q *Queries) ListActivityRides(ctx context.Context, arg ListActivityRidesParams) ([]ListActivityRidesRow, error) {
	query := listActivityRides
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SinceUnix)
	if len(arg.WorkoutTypeIds) > 0 {
		for _, v := range arg.WorkoutTypeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workout_type_ids*/?", strings.Repeat(",?", len(arg.WorkoutTypeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workout_type_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRidesRow{}
	for rows.Next() {
		var i ListActivityRidesRow
		if err := rows.Scan(
			&i.TargetSlot,
			&i.StartedAtUnix,
			&i.DistanceMetres,
			&i.MovingSeconds,
			&i.AscentMetres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySeries = `-- name: ListActivitySeries :many
SELECT recorded_at_unix, distance_metres, altitude_metres,
  heart_rate_bpm, cadence_rpm, power_watts, temperature_celsius,
  speed_ms, grade_percent, calories_kcal, ascent_metres, descent_metres
FROM activity_records
WHERE target_slot = ?1 AND workout_id = ?2
  AND latitude IS NOT NULL AND longitude IS NOT NULL
ORDER BY record_index
`

type ListActivitySeriesParams struct {
	TargetSlot string
	WorkoutID  int64
}

type ListActivitySeriesRow struct {
	RecordedAtUnix     int64
	DistanceMetres     sql.NullFloat64
	AltitudeMetres     sql.NullFloat64
	HeartRateBpm       sql.NullFloat64
	CadenceRpm         sql.NullFloat64
	PowerWatts         sql.NullFloat64
	TemperatureCelsius sql.NullFloat64
	SpeedMs            sql.NullFloat64
	GradePercent       sql.NullFloat64
	CaloriesKcal       sql.NullFloat64
	AscentMetres       sql.NullFloat64
	DescentMetres      sql.NullFloat64
}

func (q *Queries) ListActivitySeries(ctx context.Context, arg ListActivitySeriesParams) ([]ListActivitySeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitySeries, arg.TargetSlot, arg.WorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySeriesRow{}
	for rows.Next() {
		var i ListActivitySeriesRow
		if err := rows.Scan(
			&i.RecordedAtUnix,
			&i.DistanceMetres,
			&i.AltitudeMetres,
			&i.HeartRateBpm,
			&i.CadenceRpm,
			&i.PowerWatts,
			&i.TemperatureCelsius,
			&i.SpeedMs,
			&i.GradePercent,
			&i.CaloriesKcal,
			&i.AscentMetres,
			&i.DescentMetres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySessions = `-- name: ListActivitySessions :many
SELECT workout_id, max_speed_kmh, average_speed_kmh, distance_metres,
  timer_seconds, elapsed_seconds, ascent_metres, descent_metres, calories_kcal,
  average_heart_rate_bpm, max_heart_rate_bpm, min_heart_rate_bpm,
  average_cadence_rpm, max_cadence_rpm,
  average_power_watts, max_power_watts, normalized_power_watts, threshold_power_watts,
  average_temperature_celsius, max_temperature_celsius,
  average_grade_percent, max_positive_grade_percent, max_negative_grade_percent,
  min_altitude_metres, max_altitude_metres, average_altitude_metres,
  sport, sub_sport,
  heart_rate_zone_seconds_json, heart_rate_zone_high_bpm_json,
  power_zone_seconds_json, power_zone_high_watts_json
FROM activity_session
WHERE target_slot = ?
ORDER BY workout_id
`

type ListActivitySessionsRow struct {
	WorkoutID                 int64
	MaxSpeedKmh               sql.NullFloat64
	AverageSpeedKmh           sql.NullFloat64
	DistanceMetres            sql.NullFloat64
	TimerSeconds              sql.NullFloat64
	ElapsedSeconds            sql.NullFloat64
	AscentMetres              sql.NullFloat64
	DescentMetres             sql.NullFloat64
	CaloriesKcal              sql.NullFloat64
	AverageHeartRateBpm       sql.NullFloat64
	MaxHeartRateBpm           sql.NullFloat64
	MinHeartRateBpm           sql.NullFloat64
	AverageCadenceRpm         sql.NullFloat64
	MaxCadenceRpm             sql.NullFloat64
	AveragePowerWatts         sql.NullFloat64
	MaxPowerWatts             sql.NullFloat64
	NormalizedPowerWatts      sql.NullFloat64
	ThresholdPowerWatts       sql.NullFloat64
	AverageTemperatureCelsius sql.NullFloat64
	MaxTemperatureCelsius     sql.NullFloat64
	AverageGradePercent       sql.NullFloat64
	MaxPositiveGradePercent   sql.NullFloat64
	MaxNegativeGradePercent   sql.NullFloat64
	MinAltitudeMetres         sql.NullFloat64
	MaxAltitudeMetres         sql.NullFloat64
	AverageAltitudeMetres     sql.NullFloat64
	Sport                     string
	SubSport                  string
	HeartRateZoneSecondsJson  sql.NullString
	HeartRateZoneHighBpmJson  sql.NullString
	PowerZoneSecondsJson      sql.NullString
	PowerZoneHighWattsJson    sql.NullString
}

func (q *Queries) ListActivitySessions(ctx context.Context, targetSlot string) ([]ListActivitySessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitySessions, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySessionsRow{}
	for rows.Next() {
		var i ListActivitySessionsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.MaxSpeedKmh,
			&i.AverageSpeedKmh,
			&i.DistanceMetres,
			&i.TimerSeconds,
			&i.ElapsedSeconds,
			&i.AscentMetres,
			&i.DescentMetres,
			&i.CaloriesKcal,
			&i.AverageHeartRateBpm,
			&i.MaxHeartRateBpm,
			&i.MinHeartRateBpm,
			&i.AverageCadenceRpm,
			&i.MaxCadenceRpm,
			&i.AveragePowerWatts,
			&i.MaxPowerWatts,
			&i.NormalizedPowerWatts,
			&i.ThresholdPowerWatts,
			&i.AverageTemperatureCelsius,
			&i.MaxTemperatureCelsius,
			&i.AverageGradePercent,
			&i.MaxPositiveGradePercent,
			&i.MaxNegativeGradePercent,
			&i.MinAltitudeMetres,
			&i.MaxAltitudeMetres,
			&i.AverageAltitudeMetres,
			&i.Sport,
			&i.SubSport,
			&i.HeartRateZoneSecondsJson,
			&i.HeartRateZoneHighBpmJson,
			&i.PowerZoneSecondsJson,
			&i.PowerZoneHighWattsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySkips = `-- name: ListActivitySkips :many
SELECT workout_id, attempts, last_attempt_unix FROM activity_skips WHERE target_slot = ? ORDER BY workout_id
`

type ListActivitySkipsRow struct {
	WorkoutID       int64
	Attempts        int64
	LastAttemptUnix int64
}

func (q *Queries) ListActivitySkips(ctx context.Context, targetSlot string) ([]ListActivitySkipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitySkips, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySkipsRow{}
	for rows.Next() {
		var i ListActivitySkipsRow
		if err := rows.Scan(&i.WorkoutID, &i.Attempts, &i.LastAttemptUnix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityTrack = `-- name: ListActivityTrack :many
SELECT recorded_at_unix, latitude, longitude, altitude_metres, estimated_power_watts
FROM activity_records
WHERE target_slot = ?1 AND workout_id = ?2
  AND latitude IS NOT NULL AND longitude IS NOT NULL
ORDER BY record_index
`

type ListActivityTrackParams struct {
	TargetSlot string
	WorkoutID  int64
}

type ListActivityTrackRow struct {
	RecordedAtUnix      int64
	Latitude            sql.NullFloat64
	Longitude           sql.NullFloat64
	AltitudeMetres      sql.NullFloat64
	EstimatedPowerWatts sql.NullFloat64
}

func (q *Queries) ListActivityTrack(ctx context.Context, arg ListActivityTrackParams) ([]ListActivityTrackRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityTrack, arg.TargetSlot, arg.WorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityTrackRow{}
	for rows.Next() {
		var i ListActivityTrackRow
		if err := rows.Scan(
			&i.RecordedAtUnix,
			&i.Latitude,
			&i.Longitude,
			&i.AltitudeMetres,
			&i.EstimatedPowerWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndoorRideStarts = `-- name: ListIndoorRideStarts :many
SELECT started_at_unix FROM activities
WHERE target_slot = ? AND provider = 'zwift'
ORDER BY started_at_unix
`

// Zwift rides alone: a Wahoo listing starting within a minute of one of these
// is the head unit's copy of that same indoor ride.
func (q *Queries) ListIndoorRideStarts(ctx context.Context, targetSlot string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listIndoorRideStarts, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var started_at_unix int64
		if err := rows.Scan(&started_at_unix); err != nil {
			return nil, err
		}
		items = append(items, started_at_unix)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedActivities = `-- name: ListRecordedActivities :many
SELECT target_slot, workout_id, ascent_metres, distance_metres, moving_seconds
FROM activities
WHERE records_state = 'stored'
ORDER BY target_slot, workout_id
`

type ListRecordedActivitiesRow struct {
	TargetSlot     string
	WorkoutID      int64
	AscentMetres   float64
	DistanceMetres float64
	MovingSeconds  float64
}

func (q *Queries) ListRecordedActivities(ctx context.Context) ([]ListRecordedActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecordedActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordedActivitiesRow{}
	for rows.Next() {
		var i ListRecordedActivitiesRow
		if err := rows.Scan(
			&i.TargetSlot,
			&i.WorkoutID,
			&i.AscentMetres,
			&i.DistanceMetres,
			&i.MovingSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActivityRecordsStored = `-- name: MarkActivityRecordsStored :exec
UPDATE activities SET records_state = 'stored', fit_checksum_failed = ?1,
  records_version = ?2
WHERE target_slot = ?3 AND workout_id = ?4
`

type MarkActivityRecordsStoredParams struct {
	FitChecksumFailed int64
	RecordsVersion    int64
	TargetSlot        string
	WorkoutID         int64
}

func (q *Queries) MarkActivityRecordsStored(ctx context.Context, arg MarkActivityRecordsStoredParams) error {
	_, err := q.db.ExecContext(ctx, markActivityRecordsStored,
		arg.FitChecksumFailed,
		arg.RecordsVersion,
		arg.TargetSlot,
		arg.WorkoutID,
	)
	return err
}

const markActivityRecordsUnreadable = `-- name: MarkActivityRecordsUnreadable :exec
UPDATE activities SET records_state = 'unreadable' WHERE target_slot = ? AND workout_id = ?
`

type MarkActivityRecordsUnreadableParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) MarkActivityRecordsUnreadable(ctx context.Context, arg MarkActivityRecordsUnreadableParams) error {
	_, err := q.db.ExecContext(ctx, markActivityRecordsUnreadable, arg.TargetSlot, arg.WorkoutID)
	return err
}

const upsertActivity = `-- name: UpsertActivity :execrows
INSERT INTO activities (
  target_slot, workout_id, workout_type_id, workout_type_location_id, started_at_unix,
  distance_metres, moving_seconds, elapsed_seconds, ascent_metres, raw_summary_json, updated_at_unix,
  provider
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  workout_type_id = excluded.workout_type_id,
  workout_type_location_id = excluded.workout_type_location_id,
  started_at_unix = excluded.started_at_unix,
  distance_metres = excluded.distance_metres,
  moving_seconds = excluded.moving_seconds,
  elapsed_seconds = excluded.elapsed_seconds,
  ascent_metres = excluded.ascent_metres,
  raw_summary_json = excluded.raw_summary_json,
  updated_at_unix = excluded.updated_at_unix
WHERE activities.provider = excluded.provider
`

type UpsertActivityParams struct {
	TargetSlot            string
	WorkoutID             int64
	WorkoutTypeID         int64
	WorkoutTypeLocationID int64
	StartedAtUnix         int64
	DistanceMetres        float64
	MovingSeconds         float64
	ElapsedSeconds        float64
	AscentMetres          float64
	RawSummaryJson        []byte
	UpdatedAtUnix         int64
	Provider              string
}

// Zero rows means the stored row belongs to another provider: two id spaces
// share this key, so a collision fails loudly rather than overwriting a ride.
func (q *Queries) UpsertActivity(ctx context.Context, arg UpsertActivityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertActivity,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.WorkoutTypeID,
		arg.WorkoutTypeLocationID,
		arg.StartedAtUnix,
		arg.DistanceMetres,
		arg.MovingSeconds,
		arg.ElapsedSeconds,
		arg.AscentMetres,
		arg.RawSummaryJson,
		arg.UpdatedAtUnix,
		arg.Provider,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertActivitySession = `-- name: UpsertActivitySession :exec
INSERT INTO activity_session (
  target_slot, workout_id, max_speed_kmh, average_speed_kmh, distance_metres,
  timer_seconds, elapsed_seconds, ascent_metres, descent_metres, calories_kcal,
  average_heart_rate_bpm, max_heart_rate_bpm, min_heart_rate_bpm,
  average_cadence_rpm, max_cadence_rpm,
  average_power_watts, max_power_watts, normalized_power_watts, threshold_power_watts,
  average_temperature_celsius, max_temperature_celsius,
  average_grade_percent, max_positive_grade_percent, max_negative_grade_percent,
  min_altitude_metres, max_altitude_metres, average_altitude_metres,
  sport, sub_sport,
  heart_rate_zone_seconds_json, heart_rate_zone_high_bpm_json,
  power_zone_seconds_json, power_zone_high_watts_json
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  max_speed_kmh = excluded.max_speed_kmh,
  average_speed_kmh = excluded.average_speed_kmh,
  distance_metres = excluded.distance_metres,
  timer_seconds = excluded.timer_seconds,
  elapsed_seconds = excluded.elapsed_seconds,
  ascent_metres = excluded.ascent_metres,
  descent_metres = excluded.descent_metres,
  calories_kcal = excluded.calories_kcal,
  average_heart_rate_bpm = excluded.average_heart_rate_bpm,
  max_heart_rate_bpm = excluded.max_heart_rate_bpm,
  min_heart_rate_bpm = excluded.min_heart_rate_bpm,
  average_cadence_rpm = excluded.average_cadence_rpm,
  max_cadence_rpm = excluded.max_cadence_rpm,
  average_power_watts = excluded.average_power_watts,
  max_power_watts = excluded.max_power_watts,
  normalized_power_watts = excluded.normalized_power_watts,
  threshold_power_watts = excluded.threshold_power_watts,
  average_temperature_celsius = excluded.average_temperature_celsius,
  max_temperature_celsius = excluded.max_temperature_celsius,
  average_grade_percent = excluded.average_grade_percent,
  max_positive_grade_percent = excluded.max_positive_grade_percent,
  max_negative_grade_percent = excluded.max_negative_grade_percent,
  min_altitude_metres = excluded.min_altitude_metres,
  max_altitude_metres = excluded.max_altitude_metres,
  average_altitude_metres = excluded.average_altitude_metres,
  sport = excluded.sport,
  sub_sport = excluded.sub_sport,
  heart_rate_zone_seconds_json = excluded.heart_rate_zone_seconds_json,
  heart_rate_zone_high_bpm_json = excluded.heart_rate_zone_high_bpm_json,
  power_zone_seconds_json = excluded.power_zone_seconds_json,
  power_zone_high_watts_json = excluded.power_zone_high_watts_json
`

type UpsertActivitySessionParams struct {
	TargetSlot                string
	WorkoutID                 int64
	MaxSpeedKmh               sql.NullFloat64
	AverageSpeedKmh           sql.NullFloat64
	DistanceMetres            sql.NullFloat64
	TimerSeconds              sql.NullFloat64
	ElapsedSeconds            sql.NullFloat64
	AscentMetres              sql.NullFloat64
	DescentMetres             sql.NullFloat64
	CaloriesKcal              sql.NullFloat64
	AverageHeartRateBpm       sql.NullFloat64
	MaxHeartRateBpm           sql.NullFloat64
	MinHeartRateBpm           sql.NullFloat64
	AverageCadenceRpm         sql.NullFloat64
	MaxCadenceRpm             sql.NullFloat64
	AveragePowerWatts         sql.NullFloat64
	MaxPowerWatts             sql.NullFloat64
	NormalizedPowerWatts      sql.NullFloat64
	ThresholdPowerWatts       sql.NullFloat64
	AverageTemperatureCelsius sql.NullFloat64
	MaxTemperatureCelsius     sql.NullFloat64
	AverageGradePercent       sql.NullFloat64
	MaxPositiveGradePercent   sql.NullFloat64
	MaxNegativeGradePercent   sql.NullFloat64
	MinAltitudeMetres         sql.NullFloat64
	MaxAltitudeMetres         sql.NullFloat64
	AverageAltitudeMetres     sql.NullFloat64
	Sport                     string
	SubSport                  string
	HeartRateZoneSecondsJson  sql.NullString
	HeartRateZoneHighBpmJson  sql.NullString
	PowerZoneSecondsJson      sql.NullString
	PowerZoneHighWattsJson    sql.NullString
}

func (q *Queries) UpsertActivitySession(ctx context.Context, arg UpsertActivitySessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivitySession,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.MaxSpeedKmh,
		arg.AverageSpeedKmh,
		arg.DistanceMetres,
		arg.TimerSeconds,
		arg.ElapsedSeconds,
		arg.AscentMetres,
		arg.DescentMetres,
		arg.CaloriesKcal,
		arg.AverageHeartRateBpm,
		arg.MaxHeartRateBpm,
		arg.MinHeartRateBpm,
		arg.AverageCadenceRpm,
		arg.MaxCadenceRpm,
		arg.AveragePowerWatts,
		arg.MaxPowerWatts,
		arg.NormalizedPowerWatts,
		arg.ThresholdPowerWatts,
		arg.AverageTemperatureCelsius,
		arg.MaxTemperatureCelsius,
		arg.AverageGradePercent,
		arg.MaxPositiveGradePercent,
		arg.MaxNegativeGradePercent,
		arg.MinAltitudeMetres,
		arg.MaxAltitudeMetres,
		arg.AverageAltitudeMetres,
		arg.Sport,
		arg.SubSport,
		arg.HeartRateZoneSecondsJson,
		arg.HeartRateZoneHighBpmJson,
		arg.PowerZoneSecondsJson,
		arg.PowerZoneHighWattsJson,
	)
	return err
}

const upsertActivitySkip = `-- name: UpsertActivitySkip :exec
INSERT INTO activity_skips (target_slot, workout_id, attempts, last_attempt_unix, observed)
VALUES (?, ?, 1, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  attempts = attempts + 1,
  last_attempt_unix = excluded.last_attempt_unix,
  observed = excluded.observed
`

type UpsertActivitySkipParams struct {
	TargetSlot      string
	WorkoutID       int64
	LastAttemptUnix int64
	Observed        string
}

func (q *Queries) UpsertActivitySkip(ctx context.Context, arg UpsertActivitySkipParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivitySkip,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.LastAttemptUnix,
		arg.Observed,
	)
	return err
}
