// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlcgen

import (
	"context"
)

const listActivityIDs = `-- name: ListActivityIDs :many
SELECT workout_id FROM activities WHERE target_slot = ? ORDER BY workout_id
`

func (q *Queries) ListActivityIDs(ctx context.Context, targetSlot string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActivityIDs, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workout_id int64
		if err := rows.Scan(&workout_id); err != nil {
			return nil, err
		}
		items = append(items, workout_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivity = `-- name: UpsertActivity :exec
INSERT INTO activities (
  target_slot, workout_id, workout_type_id, workout_type_location_id, started_at_unix,
  distance_metres, moving_seconds, elapsed_seconds, ascent_metres, raw_summary_json, updated_at_unix
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  workout_type_id = excluded.workout_type_id,
  workout_type_location_id = excluded.workout_type_location_id,
  started_at_unix = excluded.started_at_unix,
  distance_metres = excluded.distance_metres,
  moving_seconds = excluded.moving_seconds,
  elapsed_seconds = excluded.elapsed_seconds,
  ascent_metres = excluded.ascent_metres,
  raw_summary_json = excluded.raw_summary_json,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertActivityParams struct {
	TargetSlot            string
	WorkoutID             int64
	WorkoutTypeID         int64
	WorkoutTypeLocationID int64
	StartedAtUnix         int64
	DistanceMetres        float64
	MovingSeconds         float64
	ElapsedSeconds        float64
	AscentMetres          float64
	RawSummaryJson        []byte
	UpdatedAtUnix         int64
}

func (q *Queries) UpsertActivity(ctx context.Context, arg UpsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivity,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.WorkoutTypeID,
		arg.WorkoutTypeLocationID,
		arg.StartedAtUnix,
		arg.DistanceMetres,
		arg.MovingSeconds,
		arg.ElapsedSeconds,
		arg.AscentMetres,
		arg.RawSummaryJson,
		arg.UpdatedAtUnix,
	)
	return err
}
