// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package sqlcgen

import (
	"context"
)

const clearActivityAnalyses = `-- name: ClearActivityAnalyses :exec
DELETE FROM activity_analyses WHERE target_slot = ?
`

func (q *Queries) ClearActivityAnalyses(ctx context.Context, targetSlot string) error {
	_, err := q.db.ExecContext(ctx, clearActivityAnalyses, targetSlot)
	return err
}

const deleteActivityAnalysis = `-- name: DeleteActivityAnalysis :exec
DELETE FROM activity_analyses WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivityAnalysisParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityAnalysis(ctx context.Context, arg DeleteActivityAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityAnalysis, arg.TargetSlot, arg.WorkoutID)
	return err
}

const getAnalysisEnabledSince = `-- name: GetAnalysisEnabledSince :one
SELECT enabled_since_unix FROM analysis_state WHERE id = 1
`

func (q *Queries) GetAnalysisEnabledSince(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisEnabledSince)
	var enabled_since_unix int64
	err := row.Scan(&enabled_since_unix)
	return enabled_since_unix, err
}

const listActivitiesAwaitingAnalysis = `-- name: ListActivitiesAwaitingAnalysis :many
SELECT a.workout_id, a.started_at_unix
FROM activities AS a
JOIN activity_metrics AS m ON m.target_slot = a.target_slot AND m.workout_id = a.workout_id
LEFT JOIN activity_analyses AS x ON x.target_slot = a.target_slot AND x.workout_id = a.workout_id
WHERE a.target_slot = ?1
  AND a.started_at_unix >= ?2
  AND x.workout_id IS NULL
  AND NOT (a.provider = 'wahoo'
    AND a.started_at_unix >= ?3
    AND a.workout_type_id IN (SELECT value FROM json_each(CAST(?4 AS TEXT))))
ORDER BY a.started_at_unix, a.workout_id
LIMIT ?5
`

type ListActivitiesAwaitingAnalysisParams struct {
	TargetSlot       string
	EnabledSinceUnix int64
	HeldSinceUnix    int64
	HeldTypeIds      string
	RowLimit         int64
}

type ListActivitiesAwaitingAnalysisRow struct {
	WorkoutID     int64
	StartedAtUnix int64
}

// Derived rides with no analysis that started at or after the instant the
// analysis was enabled, oldest first so each answer can read the ones before it.
// A head unit's ride of a held type that started at or after held_since waits
// for the Zwift copy that may replace it.
func (q *Queries) ListActivitiesAwaitingAnalysis(ctx context.Context, arg ListActivitiesAwaitingAnalysisParams) ([]ListActivitiesAwaitingAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesAwaitingAnalysis,
		arg.TargetSlot,
		arg.EnabledSinceUnix,
		arg.HeldSinceUnix,
		arg.HeldTypeIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesAwaitingAnalysisRow{}
	for rows.Next() {
		var i ListActivitiesAwaitingAnalysisRow
		if err := rows.Scan(&i.WorkoutID, &i.StartedAtUnix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnalysesBefore = `-- name: ListAnalysesBefore :many
SELECT x.text, x.model, x.prompt_revision, x.analysed_at_unix, a.started_at_unix
FROM activity_analyses AS x
JOIN activities AS a ON a.target_slot = x.target_slot AND a.workout_id = x.workout_id
WHERE x.target_slot = ?1
  AND a.started_at_unix < ?2
ORDER BY a.started_at_unix DESC, a.workout_id DESC
LIMIT ?3
`

type ListAnalysesBeforeParams struct {
	TargetSlot        string
	StartedBeforeUnix int64
	RowLimit          int64
}

type ListAnalysesBeforeRow struct {
	Text           string
	Model          string
	PromptRevision int64
	AnalysedAtUnix int64
	StartedAtUnix  int64
}

// The analyses of rides that started before one, newest first.
func (q *Queries) ListAnalysesBefore(ctx context.Context, arg ListAnalysesBeforeParams) ([]ListAnalysesBeforeRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnalysesBefore, arg.TargetSlot, arg.StartedBeforeUnix, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnalysesBeforeRow{}
	for rows.Next() {
		var i ListAnalysesBeforeRow
		if err := rows.Scan(
			&i.Text,
			&i.Model,
			&i.PromptRevision,
			&i.AnalysedAtUnix,
			&i.StartedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAnalysisEnabled = `-- name: RecordAnalysisEnabled :exec
INSERT INTO analysis_state (id, enabled_since_unix) VALUES (1, ?)
ON CONFLICT(id) DO NOTHING
`

func (q *Queries) RecordAnalysisEnabled(ctx context.Context, enabledSinceUnix int64) error {
	_, err := q.db.ExecContext(ctx, recordAnalysisEnabled, enabledSinceUnix)
	return err
}

const upsertActivityAnalysis = `-- name: UpsertActivityAnalysis :exec
INSERT INTO activity_analyses (target_slot, workout_id, text, model, prompt_revision, analysed_at_unix)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  text = excluded.text,
  model = excluded.model,
  prompt_revision = excluded.prompt_revision,
  analysed_at_unix = excluded.analysed_at_unix
`

type UpsertActivityAnalysisParams struct {
	TargetSlot     string
	WorkoutID      int64
	Text           string
	Model          string
	PromptRevision int64
	AnalysedAtUnix int64
}

func (q *Queries) UpsertActivityAnalysis(ctx context.Context, arg UpsertActivityAnalysisParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivityAnalysis,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.Text,
		arg.Model,
		arg.PromptRevision,
		arg.AnalysedAtUnix,
	)
	return err
}
