// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const consumeOAuthTransaction = `-- name: ConsumeOAuthTransaction :execresult
UPDATE oauth_transactions
SET used_at_unix = ?
WHERE state_digest = ? AND used_at_unix IS NULL
`

type ConsumeOAuthTransactionParams struct {
	UsedAtUnix  sql.NullInt64
	StateDigest []byte
}

func (q *Queries) ConsumeOAuthTransaction(ctx context.Context, arg ConsumeOAuthTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, consumeOAuthTransaction, arg.UsedAtUnix, arg.StateDigest)
}

const deletePriorOAuthTransactions = `-- name: DeletePriorOAuthTransactions :exec
DELETE FROM oauth_transactions
WHERE expires_at_unix <= ? OR (target_slot = ? AND caller_login = ? AND used_at_unix IS NULL)
`

type DeletePriorOAuthTransactionsParams struct {
	ExpiresAtUnix int64
	TargetSlot    string
	CallerLogin   string
}

func (q *Queries) DeletePriorOAuthTransactions(ctx context.Context, arg DeletePriorOAuthTransactionsParams) error {
	_, err := q.db.ExecContext(ctx, deletePriorOAuthTransactions, arg.ExpiresAtUnix, arg.TargetSlot, arg.CallerLogin)
	return err
}

const findTargetByWahooUser = `-- name: FindTargetByWahooUser :one
SELECT slot FROM targets WHERE wahoo_user_id = ? AND slot != ?
`

type FindTargetByWahooUserParams struct {
	WahooUserID sql.NullString
	Slot        string
}

func (q *Queries) FindTargetByWahooUser(ctx context.Context, arg FindTargetByWahooUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findTargetByWahooUser, arg.WahooUserID, arg.Slot)
	var slot string
	err := row.Scan(&slot)
	return slot, err
}

const getOAuthTransaction = `-- name: GetOAuthTransaction :one
SELECT target_slot, caller_login, expires_at_unix, used_at_unix
FROM oauth_transactions
WHERE state_digest = ?
`

type GetOAuthTransactionRow struct {
	TargetSlot    string
	CallerLogin   string
	ExpiresAtUnix int64
	UsedAtUnix    sql.NullInt64
}

func (q *Queries) GetOAuthTransaction(ctx context.Context, stateDigest []byte) (GetOAuthTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getOAuthTransaction, stateDigest)
	var i GetOAuthTransactionRow
	err := row.Scan(
		&i.TargetSlot,
		&i.CallerLogin,
		&i.ExpiresAtUnix,
		&i.UsedAtUnix,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT refresh_token FROM targets WHERE slot = ?
`

func (q *Queries) GetRefreshToken(ctx context.Context, slot string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, slot)
	var refresh_token []byte
	err := row.Scan(&refresh_token)
	return refresh_token, err
}

const getTargetByWahooUser = `-- name: GetTargetByWahooUser :one
SELECT slot FROM targets WHERE wahoo_user_id = ?
`

func (q *Queries) GetTargetByWahooUser(ctx context.Context, wahooUserID sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetByWahooUser, wahooUserID)
	var slot string
	err := row.Scan(&slot)
	return slot, err
}

const insertOAuthTransaction = `-- name: InsertOAuthTransaction :exec
INSERT INTO oauth_transactions (
  id, target_slot, state_digest, code_verifier, expires_at_unix, caller_login
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOAuthTransactionParams struct {
	ID            string
	TargetSlot    string
	StateDigest   []byte
	CodeVerifier  []byte
	ExpiresAtUnix int64
	CallerLogin   string
}

func (q *Queries) InsertOAuthTransaction(ctx context.Context, arg InsertOAuthTransactionParams) error {
	_, err := q.db.ExecContext(ctx, insertOAuthTransaction,
		arg.ID,
		arg.TargetSlot,
		arg.StateDigest,
		arg.CodeVerifier,
		arg.ExpiresAtUnix,
		arg.CallerLogin,
	)
	return err
}

const listPendingAuthorizations = `-- name: ListPendingAuthorizations :many
SELECT DISTINCT target_slot
FROM oauth_transactions
WHERE used_at_unix IS NULL AND expires_at_unix > ?
ORDER BY target_slot
`

func (q *Queries) ListPendingAuthorizations(ctx context.Context, expiresAtUnix int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAuthorizations, expiresAtUnix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var target_slot string
		if err := rows.Scan(&target_slot); err != nil {
			return nil, err
		}
		items = append(items, target_slot)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTargetNeedsReauthorization = `-- name: MarkTargetNeedsReauthorization :execresult
UPDATE targets
SET refresh_token = NULL, authorization_state = ?, updated_at_unix = ?
WHERE slot = ?
`

type MarkTargetNeedsReauthorizationParams struct {
	AuthorizationState string
	UpdatedAtUnix      int64
	Slot               string
}

func (q *Queries) MarkTargetNeedsReauthorization(ctx context.Context, arg MarkTargetNeedsReauthorizationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markTargetNeedsReauthorization, arg.AuthorizationState, arg.UpdatedAtUnix, arg.Slot)
}

const targetExists = `-- name: TargetExists :one
SELECT EXISTS(SELECT 1 FROM targets WHERE slot = ?)
`

func (q *Queries) TargetExists(ctx context.Context, slot string) (bool, error) {
	row := q.db.QueryRowContext(ctx, targetExists, slot)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :execresult
UPDATE targets
SET refresh_token = ?, authorization_state = ?, updated_at_unix = ?
WHERE slot = ?
`

type UpdateRefreshTokenParams struct {
	RefreshToken       []byte
	AuthorizationState string
	UpdatedAtUnix      int64
	Slot               string
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRefreshToken,
		arg.RefreshToken,
		arg.AuthorizationState,
		arg.UpdatedAtUnix,
		arg.Slot,
	)
}

const updateTargetAuthorization = `-- name: UpdateTargetAuthorization :execresult
UPDATE targets
SET wahoo_user_id = ?, refresh_token = ?, authorization_state = ?, updated_at_unix = ?
WHERE slot = ?
`

type UpdateTargetAuthorizationParams struct {
	WahooUserID        sql.NullString
	RefreshToken       []byte
	AuthorizationState string
	UpdatedAtUnix      int64
	Slot               string
}

func (q *Queries) UpdateTargetAuthorization(ctx context.Context, arg UpdateTargetAuthorizationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTargetAuthorization,
		arg.WahooUserID,
		arg.RefreshToken,
		arg.AuthorizationState,
		arg.UpdatedAtUnix,
		arg.Slot,
	)
}
