// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const clearActivityMetrics = `-- name: ClearActivityMetrics :execrows
DELETE FROM activity_metrics WHERE target_slot = ?
`

// Every row one target holds, for a rider who has cleared the profile the rows
// were worked out from. Reports how many went, so a derivation can tell a
// clearing from a rider who never had a profile at all.
func (q *Queries) ClearActivityMetrics(ctx context.Context, targetSlot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearActivityMetrics, targetSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEstimatedPower = `-- name: ClearEstimatedPower :execrows
UPDATE activity_records SET estimated_power_watts = NULL
WHERE target_slot = ? AND workout_id = ? AND estimated_power_watts IS NOT NULL
`

type ClearEstimatedPowerParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) ClearEstimatedPower(ctx context.Context, arg ClearEstimatedPowerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearEstimatedPower, arg.TargetSlot, arg.WorkoutID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteActivityMetrics = `-- name: DeleteActivityMetrics :exec
DELETE FROM activity_metrics WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivityMetricsParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityMetrics(ctx context.Context, arg DeleteActivityMetricsParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityMetrics, arg.TargetSlot, arg.WorkoutID)
	return err
}

const getTargetOwner = `-- name: GetTargetOwner :one
SELECT COALESCE(owner_subject, '') AS owner_subject FROM targets WHERE slot = ?
`

func (q *Queries) GetTargetOwner(ctx context.Context, slot string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTargetOwner, slot)
	var owner_subject string
	err := row.Scan(&owner_subject)
	return owner_subject, err
}

const listActivitiesAwaitingDerivation = `-- name: ListActivitiesAwaitingDerivation :many
SELECT a.workout_id
FROM activities AS a
LEFT JOIN activity_metrics AS m ON m.target_slot = a.target_slot AND m.workout_id = a.workout_id
WHERE a.target_slot = ?1
  AND a.records_state = 'stored'
  AND (m.workout_id IS NULL
    OR m.input_max_heart_rate <> ?2
    OR m.input_resting_heart_rate <> ?3
    OR m.input_threshold_heart_rate <> ?4
    OR m.input_threshold_power <> ?5
    OR m.input_total_mass <> ?6
    OR (m.estimated_power_watts IS NOT NULL AND (m.input_drag_area <> ?7
      OR m.input_rolling_resistance <> ?8))
    OR m.derivation_version <> ?9)
ORDER BY a.started_at_unix DESC, a.workout_id DESC
`

type ListActivitiesAwaitingDerivationParams struct {
	TargetSlot         string
	MaxHeartRate       float64
	RestingHeartRate   float64
	ThresholdHeartRate float64
	ThresholdPower     float64
	TotalMass          float64
	DragArea           float64
	RollingResistance  float64
	DerivationVersion  int64
}

// Rides whose stored samples could still yield something this derivation now
// allows: those with no metrics row at all, those whose row was worked out
// against different profile values, those holding an estimate worked out
// against a different bicycle, and those whose row an earlier derivation
// wrote and so cannot hold every figure this one produces. A ride still
// awaiting its FIT has nothing to derive from and is left for the download
// to bring in.
func (q *Queries) ListActivitiesAwaitingDerivation(ctx context.Context, arg ListActivitiesAwaitingDerivationParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesAwaitingDerivation,
		arg.TargetSlot,
		arg.MaxHeartRate,
		arg.RestingHeartRate,
		arg.ThresholdHeartRate,
		arg.ThresholdPower,
		arg.TotalMass,
		arg.DragArea,
		arg.RollingResistance,
		arg.DerivationVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workout_id int64
		if err := rows.Scan(&workout_id); err != nil {
			return nil, err
		}
		items = append(items, workout_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityMetrics = `-- name: ListActivityMetrics :many
SELECT workout_id,
  zone_1_seconds, zone_2_seconds, zone_3_seconds, zone_4_seconds, zone_5_seconds,
  trimp, heart_rate_tss, normalized_power_watts, intensity_factor, power_tss,
  estimated_power_watts, estimated_pedalling_share,
  input_max_heart_rate, input_threshold_heart_rate, input_drag_area, input_rolling_resistance,
  average_heart_rate_bpm, max_heart_rate_bpm, average_cadence_rpm, average_power_watts, max_speed_kmh,
  decoupling_percent, heat_drift_heart_rate_bpm, heat_drift_temperature_celsius, heat_drift_samples,
  best_power_5s, best_power_30s, best_power_60s, best_power_300s, best_power_1200s, best_power_3600s
FROM activity_metrics
WHERE target_slot = ?
ORDER BY workout_id
`

type ListActivityMetricsRow struct {
	WorkoutID                   int64
	Zone1Seconds                sql.NullFloat64
	Zone2Seconds                sql.NullFloat64
	Zone3Seconds                sql.NullFloat64
	Zone4Seconds                sql.NullFloat64
	Zone5Seconds                sql.NullFloat64
	Trimp                       sql.NullFloat64
	HeartRateTss                sql.NullFloat64
	NormalizedPowerWatts        sql.NullFloat64
	IntensityFactor             sql.NullFloat64
	PowerTss                    sql.NullFloat64
	EstimatedPowerWatts         sql.NullFloat64
	EstimatedPedallingShare     sql.NullFloat64
	InputMaxHeartRate           float64
	InputThresholdHeartRate     float64
	InputDragArea               float64
	InputRollingResistance      float64
	AverageHeartRateBpm         sql.NullFloat64
	MaxHeartRateBpm             sql.NullFloat64
	AverageCadenceRpm           sql.NullFloat64
	AveragePowerWatts           sql.NullFloat64
	MaxSpeedKmh                 sql.NullFloat64
	DecouplingPercent           sql.NullFloat64
	HeatDriftHeartRateBpm       sql.NullFloat64
	HeatDriftTemperatureCelsius sql.NullFloat64
	HeatDriftSamples            sql.NullInt64
	BestPower5s                 sql.NullFloat64
	BestPower30s                sql.NullFloat64
	BestPower60s                sql.NullFloat64
	BestPower300s               sql.NullFloat64
	BestPower1200s              sql.NullFloat64
	BestPower3600s              sql.NullFloat64
}

func (q *Queries) ListActivityMetrics(ctx context.Context, targetSlot string) ([]ListActivityMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityMetrics, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityMetricsRow{}
	for rows.Next() {
		var i ListActivityMetricsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.Zone1Seconds,
			&i.Zone2Seconds,
			&i.Zone3Seconds,
			&i.Zone4Seconds,
			&i.Zone5Seconds,
			&i.Trimp,
			&i.HeartRateTss,
			&i.NormalizedPowerWatts,
			&i.IntensityFactor,
			&i.PowerTss,
			&i.EstimatedPowerWatts,
			&i.EstimatedPedallingShare,
			&i.InputMaxHeartRate,
			&i.InputThresholdHeartRate,
			&i.InputDragArea,
			&i.InputRollingResistance,
			&i.AverageHeartRateBpm,
			&i.MaxHeartRateBpm,
			&i.AverageCadenceRpm,
			&i.AveragePowerWatts,
			&i.MaxSpeedKmh,
			&i.DecouplingPercent,
			&i.HeatDriftHeartRateBpm,
			&i.HeatDriftTemperatureCelsius,
			&i.HeatDriftSamples,
			&i.BestPower5s,
			&i.BestPower30s,
			&i.BestPower60s,
			&i.BestPower300s,
			&i.BestPower1200s,
			&i.BestPower3600s,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityRideLoads = `-- name: ListActivityRideLoads :many
SELECT a.started_at_unix,
  m.trimp, m.heart_rate_tss, m.power_tss,
  m.zone_1_seconds, m.zone_2_seconds, m.zone_3_seconds, m.zone_4_seconds, m.zone_5_seconds
FROM activity_metrics AS m
JOIN activities AS a ON a.target_slot = m.target_slot AND a.workout_id = m.workout_id
WHERE m.target_slot = ?
ORDER BY a.started_at_unix
`

type ListActivityRideLoadsRow struct {
	StartedAtUnix int64
	Trimp         sql.NullFloat64
	HeartRateTss  sql.NullFloat64
	PowerTss      sql.NullFloat64
	Zone1Seconds  sql.NullFloat64
	Zone2Seconds  sql.NullFloat64
	Zone3Seconds  sql.NullFloat64
	Zone4Seconds  sql.NullFloat64
	Zone5Seconds  sql.NullFloat64
}

// Every derived ride of one target with the day it was ridden, which the
// fitness timeline is a fold over. Ordered so a fold reads it once.
func (q *Queries) ListActivityRideLoads(ctx context.Context, targetSlot string) ([]ListActivityRideLoadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityRideLoads, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRideLoadsRow{}
	for rows.Next() {
		var i ListActivityRideLoadsRow
		if err := rows.Scan(
			&i.StartedAtUnix,
			&i.Trimp,
			&i.HeartRateTss,
			&i.PowerTss,
			&i.Zone1Seconds,
			&i.Zone2Seconds,
			&i.Zone3Seconds,
			&i.Zone4Seconds,
			&i.Zone5Seconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivitySensorRecords = `-- name: ListActivitySensorRecords :many
SELECT record_index, recorded_at_unix, heart_rate_bpm, cadence_rpm, power_watts,
  distance_metres, altitude_metres, latitude, longitude, temperature_celsius, speed_ms
FROM activity_records
WHERE target_slot = ?1 AND workout_id = ?2
  AND (heart_rate_bpm IS NOT NULL
    OR cadence_rpm IS NOT NULL
    OR power_watts IS NOT NULL
    OR speed_ms IS NOT NULL
    OR distance_metres IS NOT NULL)
ORDER BY record_index
`

type ListActivitySensorRecordsParams struct {
	TargetSlot string
	WorkoutID  int64
}

type ListActivitySensorRecordsRow struct {
	RecordIndex        int64
	RecordedAtUnix     int64
	HeartRateBpm       sql.NullFloat64
	CadenceRpm         sql.NullFloat64
	PowerWatts         sql.NullFloat64
	DistanceMetres     sql.NullFloat64
	AltitudeMetres     sql.NullFloat64
	Latitude           sql.NullFloat64
	Longitude          sql.NullFloat64
	TemperatureCelsius sql.NullFloat64
	SpeedMs            sql.NullFloat64
}

// Every record a derivation can do something with: one carrying a sensor, one
// carrying a distance or a device speed reading, or one carrying a whole track
// sample. A record that is none of these is skipped here rather than scanned
// and discarded in Go. The track test is latitude and longitude together,
// which is what ListActivityTrack calls a positioned sample: a record the
// track would not serve must not shape an estimate.
func (q *Queries) ListActivitySensorRecords(ctx context.Context, arg ListActivitySensorRecordsParams) ([]ListActivitySensorRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitySensorRecords, arg.TargetSlot, arg.WorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySensorRecordsRow{}
	for rows.Next() {
		var i ListActivitySensorRecordsRow
		if err := rows.Scan(
			&i.RecordIndex,
			&i.RecordedAtUnix,
			&i.HeartRateBpm,
			&i.CadenceRpm,
			&i.PowerWatts,
			&i.DistanceMetres,
			&i.AltitudeMetres,
			&i.Latitude,
			&i.Longitude,
			&i.TemperatureCelsius,
			&i.SpeedMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerBests = `-- name: ListPowerBests :many
SELECT m.best_power_5s, m.best_power_30s, m.best_power_60s,
  m.best_power_300s, m.best_power_1200s, m.best_power_3600s
FROM activity_metrics AS m
JOIN activities AS a ON a.target_slot = m.target_slot AND a.workout_id = m.workout_id
WHERE a.started_at_unix >= ?1 AND a.started_at_unix < ?2
  AND m.target_slot IN (/*SLICE:target_slots*/?)
`

type ListPowerBestsParams struct {
	FromUnix    int64
	ToUnix      int64
	TargetSlots []string
}

type ListPowerBestsRow struct {
	BestPower5s    sql.NullFloat64
	BestPower30s   sql.NullFloat64
	BestPower60s   sql.NullFloat64
	BestPower300s  sql.NullFloat64
	BestPower1200s sql.NullFloat64
	BestPower3600s sql.NullFloat64
}

// Every stored per-ride best in the half-open window, over the rider's own
// targets, so the curve covers exactly the rides the timeline beside it does. The
// fold to a curve is done in Go: an aggregate here would leave sqlc with no
// type to scan into, and a rider's ninety days is a hundred rows of six floats.
// The scalar bound before the slice, as ListActivitySensorSamples does.
func (q *Queries) ListPowerBests(ctx context.Context, arg ListPowerBestsParams) ([]ListPowerBestsRow, error) {
	query := listPowerBests
	var queryParams []interface{}
	queryParams = append(queryParams, arg.FromUnix)
	queryParams = append(queryParams, arg.ToUnix)
	if len(arg.TargetSlots) > 0 {
		for _, v := range arg.TargetSlots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:target_slots*/?", strings.Repeat(",?", len(arg.TargetSlots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:target_slots*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPowerBestsRow{}
	for rows.Next() {
		var i ListPowerBestsRow
		if err := rows.Scan(
			&i.BestPower5s,
			&i.BestPower30s,
			&i.BestPower60s,
			&i.BestPower300s,
			&i.BestPower1200s,
			&i.BestPower3600s,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivityMetrics = `-- name: UpsertActivityMetrics :exec
INSERT INTO activity_metrics (
  target_slot, workout_id,
  zone_1_seconds, zone_2_seconds, zone_3_seconds, zone_4_seconds, zone_5_seconds,
  trimp, heart_rate_tss, normalized_power_watts, intensity_factor, power_tss,
  estimated_power_watts, estimated_pedalling_share,
  average_heart_rate_bpm, max_heart_rate_bpm, average_cadence_rpm, average_power_watts, max_speed_kmh,
  decoupling_percent, heat_drift_heart_rate_bpm, heat_drift_temperature_celsius, heat_drift_samples,
  best_power_5s, best_power_30s, best_power_60s, best_power_300s, best_power_1200s, best_power_3600s,
  input_max_heart_rate, input_resting_heart_rate, input_threshold_heart_rate, input_threshold_power,
  input_total_mass, input_drag_area, input_rolling_resistance, derivation_version, computed_at_unix
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  zone_1_seconds = excluded.zone_1_seconds,
  zone_2_seconds = excluded.zone_2_seconds,
  zone_3_seconds = excluded.zone_3_seconds,
  zone_4_seconds = excluded.zone_4_seconds,
  zone_5_seconds = excluded.zone_5_seconds,
  trimp = excluded.trimp,
  heart_rate_tss = excluded.heart_rate_tss,
  normalized_power_watts = excluded.normalized_power_watts,
  intensity_factor = excluded.intensity_factor,
  power_tss = excluded.power_tss,
  estimated_power_watts = excluded.estimated_power_watts,
  estimated_pedalling_share = excluded.estimated_pedalling_share,
  average_heart_rate_bpm = excluded.average_heart_rate_bpm,
  max_heart_rate_bpm = excluded.max_heart_rate_bpm,
  average_cadence_rpm = excluded.average_cadence_rpm,
  average_power_watts = excluded.average_power_watts,
  max_speed_kmh = excluded.max_speed_kmh,
  decoupling_percent = excluded.decoupling_percent,
  heat_drift_heart_rate_bpm = excluded.heat_drift_heart_rate_bpm,
  heat_drift_temperature_celsius = excluded.heat_drift_temperature_celsius,
  heat_drift_samples = excluded.heat_drift_samples,
  best_power_5s = excluded.best_power_5s,
  best_power_30s = excluded.best_power_30s,
  best_power_60s = excluded.best_power_60s,
  best_power_300s = excluded.best_power_300s,
  best_power_1200s = excluded.best_power_1200s,
  best_power_3600s = excluded.best_power_3600s,
  input_max_heart_rate = excluded.input_max_heart_rate,
  input_resting_heart_rate = excluded.input_resting_heart_rate,
  input_threshold_heart_rate = excluded.input_threshold_heart_rate,
  input_threshold_power = excluded.input_threshold_power,
  input_total_mass = excluded.input_total_mass,
  input_drag_area = excluded.input_drag_area,
  input_rolling_resistance = excluded.input_rolling_resistance,
  derivation_version = excluded.derivation_version,
  computed_at_unix = excluded.computed_at_unix
`

type UpsertActivityMetricsParams struct {
	TargetSlot                  string
	WorkoutID                   int64
	Zone1Seconds                sql.NullFloat64
	Zone2Seconds                sql.NullFloat64
	Zone3Seconds                sql.NullFloat64
	Zone4Seconds                sql.NullFloat64
	Zone5Seconds                sql.NullFloat64
	Trimp                       sql.NullFloat64
	HeartRateTss                sql.NullFloat64
	NormalizedPowerWatts        sql.NullFloat64
	IntensityFactor             sql.NullFloat64
	PowerTss                    sql.NullFloat64
	EstimatedPowerWatts         sql.NullFloat64
	EstimatedPedallingShare     sql.NullFloat64
	AverageHeartRateBpm         sql.NullFloat64
	MaxHeartRateBpm             sql.NullFloat64
	AverageCadenceRpm           sql.NullFloat64
	AveragePowerWatts           sql.NullFloat64
	MaxSpeedKmh                 sql.NullFloat64
	DecouplingPercent           sql.NullFloat64
	HeatDriftHeartRateBpm       sql.NullFloat64
	HeatDriftTemperatureCelsius sql.NullFloat64
	HeatDriftSamples            sql.NullInt64
	BestPower5s                 sql.NullFloat64
	BestPower30s                sql.NullFloat64
	BestPower60s                sql.NullFloat64
	BestPower300s               sql.NullFloat64
	BestPower1200s              sql.NullFloat64
	BestPower3600s              sql.NullFloat64
	InputMaxHeartRate           float64
	InputRestingHeartRate       float64
	InputThresholdHeartRate     float64
	InputThresholdPower         float64
	InputTotalMass              float64
	InputDragArea               float64
	InputRollingResistance      float64
	DerivationVersion           int64
	ComputedAtUnix              int64
}

func (q *Queries) UpsertActivityMetrics(ctx context.Context, arg UpsertActivityMetricsParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivityMetrics,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.Zone1Seconds,
		arg.Zone2Seconds,
		arg.Zone3Seconds,
		arg.Zone4Seconds,
		arg.Zone5Seconds,
		arg.Trimp,
		arg.HeartRateTss,
		arg.NormalizedPowerWatts,
		arg.IntensityFactor,
		arg.PowerTss,
		arg.EstimatedPowerWatts,
		arg.EstimatedPedallingShare,
		arg.AverageHeartRateBpm,
		arg.MaxHeartRateBpm,
		arg.AverageCadenceRpm,
		arg.AveragePowerWatts,
		arg.MaxSpeedKmh,
		arg.DecouplingPercent,
		arg.HeatDriftHeartRateBpm,
		arg.HeatDriftTemperatureCelsius,
		arg.HeatDriftSamples,
		arg.BestPower5s,
		arg.BestPower30s,
		arg.BestPower60s,
		arg.BestPower300s,
		arg.BestPower1200s,
		arg.BestPower3600s,
		arg.InputMaxHeartRate,
		arg.InputRestingHeartRate,
		arg.InputThresholdHeartRate,
		arg.InputThresholdPower,
		arg.InputTotalMass,
		arg.InputDragArea,
		arg.InputRollingResistance,
		arg.DerivationVersion,
		arg.ComputedAtUnix,
	)
	return err
}
