// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlcgen

import (
	"context"
)

const deletePlan = `-- name: DeletePlan :execrows
DELETE FROM plans WHERE id = ? AND version = ?
`

type DeletePlanParams struct {
	ID      int64
	Version int64
}

func (q *Queries) DeletePlan(ctx context.Context, arg DeletePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlan, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, profile, waypoints, coordinates, distance_metres, ascent_metres,
  published, version, created_at_unix_nano, updated_at_unix_nano, pushing
FROM plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Profile,
		&i.Waypoints,
		&i.Coordinates,
		&i.DistanceMetres,
		&i.AscentMetres,
		&i.Published,
		&i.Version,
		&i.CreatedAtUnixNano,
		&i.UpdatedAtUnixNano,
		&i.Pushing,
	)
	return i, err
}

const insertPlan = `-- name: InsertPlan :exec
INSERT INTO plans (
  id, name, profile, waypoints, coordinates, distance_metres, ascent_metres,
  pushing, published, version, created_at_unix_nano, updated_at_unix_nano
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanParams struct {
	ID                int64
	Name              string
	Profile           string
	Waypoints         string
	Coordinates       []byte
	DistanceMetres    float64
	AscentMetres      float64
	Pushing           string
	Published         int64
	Version           int64
	CreatedAtUnixNano int64
	UpdatedAtUnixNano int64
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) error {
	_, err := q.db.ExecContext(ctx, insertPlan,
		arg.ID,
		arg.Name,
		arg.Profile,
		arg.Waypoints,
		arg.Coordinates,
		arg.DistanceMetres,
		arg.AscentMetres,
		arg.Pushing,
		arg.Published,
		arg.Version,
		arg.CreatedAtUnixNano,
		arg.UpdatedAtUnixNano,
	)
	return err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, profile, waypoints, coordinates, distance_metres, ascent_metres,
  published, version, created_at_unix_nano, updated_at_unix_nano, pushing
FROM plans ORDER BY id
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Profile,
			&i.Waypoints,
			&i.Coordinates,
			&i.DistanceMetres,
			&i.AscentMetres,
			&i.Published,
			&i.Version,
			&i.CreatedAtUnixNano,
			&i.UpdatedAtUnixNano,
			&i.Pushing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPlans = `-- name: ListPublishedPlans :many
SELECT id, name, profile, waypoints, coordinates, distance_metres, ascent_metres,
  published, version, created_at_unix_nano, updated_at_unix_nano, pushing
FROM plans WHERE published = 1 ORDER BY id
`

func (q *Queries) ListPublishedPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Profile,
			&i.Waypoints,
			&i.Coordinates,
			&i.DistanceMetres,
			&i.AscentMetres,
			&i.Published,
			&i.Version,
			&i.CreatedAtUnixNano,
			&i.UpdatedAtUnixNano,
			&i.Pushing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :execrows
UPDATE plans SET
  name = ?, profile = ?, waypoints = ?, coordinates = ?, distance_metres = ?,
  ascent_metres = ?, pushing = ?, published = ?, version = ?, updated_at_unix_nano = ?
WHERE id = ? AND version = ?
`

type UpdatePlanParams struct {
	Name              string
	Profile           string
	Waypoints         string
	Coordinates       []byte
	DistanceMetres    float64
	AscentMetres      float64
	Pushing           string
	Published         int64
	Version           int64
	UpdatedAtUnixNano int64
	ID                int64
	Version_2         int64
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlan,
		arg.Name,
		arg.Profile,
		arg.Waypoints,
		arg.Coordinates,
		arg.DistanceMetres,
		arg.AscentMetres,
		arg.Pushing,
		arg.Published,
		arg.Version,
		arg.UpdatedAtUnixNano,
		arg.ID,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
