// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rider.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const getRiderProfile = `-- name: GetRiderProfile :one
SELECT max_heart_rate_bpm, resting_heart_rate_bpm, threshold_heart_rate_bpm,
  functional_threshold_power_watts, rider_mass_kg, bike_mass_kg
FROM rider_profiles
WHERE subject = ?
`

type GetRiderProfileRow struct {
	MaxHeartRateBpm               sql.NullFloat64
	RestingHeartRateBpm           sql.NullFloat64
	ThresholdHeartRateBpm         sql.NullFloat64
	FunctionalThresholdPowerWatts sql.NullFloat64
	RiderMassKg                   sql.NullFloat64
	BikeMassKg                    sql.NullFloat64
}

func (q *Queries) GetRiderProfile(ctx context.Context, subject string) (GetRiderProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getRiderProfile, subject)
	var i GetRiderProfileRow
	err := row.Scan(
		&i.MaxHeartRateBpm,
		&i.RestingHeartRateBpm,
		&i.ThresholdHeartRateBpm,
		&i.FunctionalThresholdPowerWatts,
		&i.RiderMassKg,
		&i.BikeMassKg,
	)
	return i, err
}

const listActivitySensorSamples = `-- name: ListActivitySensorSamples :many
SELECT r.target_slot, r.workout_id, r.recorded_at_unix, r.heart_rate_bpm, r.power_watts
FROM activity_records AS r
JOIN activities AS a ON a.target_slot = r.target_slot AND a.workout_id = r.workout_id
WHERE a.started_at_unix >= ?1
  AND r.target_slot IN (/*SLICE:target_slots*/?)
  AND (r.heart_rate_bpm IS NOT NULL OR r.power_watts IS NOT NULL)
ORDER BY r.target_slot, r.workout_id, r.record_index
`

type ListActivitySensorSamplesParams struct {
	SinceUnix   int64
	TargetSlots []string
}

type ListActivitySensorSamplesRow struct {
	TargetSlot     string
	WorkoutID      int64
	RecordedAtUnix int64
	HeartRateBpm   sql.NullFloat64
	PowerWatts     sql.NullFloat64
}

// The scalar bound before the slice, as ListActivityRides does: sqlc numbers a
// parameter that follows an expanded slice by its source position, which is no
// longer the position it binds at.
func (q *Queries) ListActivitySensorSamples(ctx context.Context, arg ListActivitySensorSamplesParams) ([]ListActivitySensorSamplesRow, error) {
	query := listActivitySensorSamples
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SinceUnix)
	if len(arg.TargetSlots) > 0 {
		for _, v := range arg.TargetSlots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:target_slots*/?", strings.Repeat(",?", len(arg.TargetSlots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:target_slots*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySensorSamplesRow{}
	for rows.Next() {
		var i ListActivitySensorSamplesRow
		if err := rows.Scan(
			&i.TargetSlot,
			&i.WorkoutID,
			&i.RecordedAtUnix,
			&i.HeartRateBpm,
			&i.PowerWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRiderProfile = `-- name: UpsertRiderProfile :exec
INSERT INTO rider_profiles (
  subject, max_heart_rate_bpm, resting_heart_rate_bpm, threshold_heart_rate_bpm,
  functional_threshold_power_watts, rider_mass_kg, bike_mass_kg, updated_at_unix
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(subject) DO UPDATE SET
  max_heart_rate_bpm = excluded.max_heart_rate_bpm,
  resting_heart_rate_bpm = excluded.resting_heart_rate_bpm,
  threshold_heart_rate_bpm = excluded.threshold_heart_rate_bpm,
  functional_threshold_power_watts = excluded.functional_threshold_power_watts,
  rider_mass_kg = excluded.rider_mass_kg,
  bike_mass_kg = excluded.bike_mass_kg,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertRiderProfileParams struct {
	Subject                       string
	MaxHeartRateBpm               sql.NullFloat64
	RestingHeartRateBpm           sql.NullFloat64
	ThresholdHeartRateBpm         sql.NullFloat64
	FunctionalThresholdPowerWatts sql.NullFloat64
	RiderMassKg                   sql.NullFloat64
	BikeMassKg                    sql.NullFloat64
	UpdatedAtUnix                 int64
}

func (q *Queries) UpsertRiderProfile(ctx context.Context, arg UpsertRiderProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertRiderProfile,
		arg.Subject,
		arg.MaxHeartRateBpm,
		arg.RestingHeartRateBpm,
		arg.ThresholdHeartRateBpm,
		arg.FunctionalThresholdPowerWatts,
		arg.RiderMassKg,
		arg.BikeMassKg,
		arg.UpdatedAtUnix,
	)
	return err
}
