// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ridemodel.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getRideModelCoefficients = `-- name: GetRideModelCoefficients :one
SELECT seconds_per_km, seconds_per_ascent_m, calibration_cutoff_unix, evaluated_rides,
  bias_percent, mae_percent, p90_percent, training_window_months
FROM ridemodel_coefficients
WHERE id = 1
`

type GetRideModelCoefficientsRow struct {
	SecondsPerKm          float64
	SecondsPerAscentM     float64
	CalibrationCutoffUnix sql.NullInt64
	EvaluatedRides        int64
	BiasPercent           float64
	MaePercent            float64
	P90Percent            float64
	TrainingWindowMonths  int64
}

func (q *Queries) GetRideModelCoefficients(ctx context.Context) (GetRideModelCoefficientsRow, error) {
	row := q.db.QueryRowContext(ctx, getRideModelCoefficients)
	var i GetRideModelCoefficientsRow
	err := row.Scan(
		&i.SecondsPerKm,
		&i.SecondsPerAscentM,
		&i.CalibrationCutoffUnix,
		&i.EvaluatedRides,
		&i.BiasPercent,
		&i.MaePercent,
		&i.P90Percent,
		&i.TrainingWindowMonths,
	)
	return i, err
}

const upsertRideModelCoefficients = `-- name: UpsertRideModelCoefficients :exec
INSERT INTO ridemodel_coefficients (id, seconds_per_km, seconds_per_ascent_m, calibration_cutoff_unix,
  evaluated_rides, bias_percent, mae_percent, p90_percent, training_window_months, updated_at_unix)
VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET seconds_per_km = excluded.seconds_per_km,
  seconds_per_ascent_m = excluded.seconds_per_ascent_m,
  calibration_cutoff_unix = excluded.calibration_cutoff_unix,
  evaluated_rides = excluded.evaluated_rides, bias_percent = excluded.bias_percent,
  mae_percent = excluded.mae_percent, p90_percent = excluded.p90_percent,
  training_window_months = excluded.training_window_months,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertRideModelCoefficientsParams struct {
	SecondsPerKm          float64
	SecondsPerAscentM     float64
	CalibrationCutoffUnix sql.NullInt64
	EvaluatedRides        int64
	BiasPercent           float64
	MaePercent            float64
	P90Percent            float64
	TrainingWindowMonths  int64
	UpdatedAtUnix         int64
}

func (q *Queries) UpsertRideModelCoefficients(ctx context.Context, arg UpsertRideModelCoefficientsParams) error {
	_, err := q.db.ExecContext(ctx, upsertRideModelCoefficients,
		arg.SecondsPerKm,
		arg.SecondsPerAscentM,
		arg.CalibrationCutoffUnix,
		arg.EvaluatedRides,
		arg.BiasPercent,
		arg.MaePercent,
		arg.P90Percent,
		arg.TrainingWindowMonths,
		arg.UpdatedAtUnix,
	)
	return err
}
