// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rider.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const deleteRiderCredential = `-- name: DeleteRiderCredential :exec
DELETE FROM rider_credentials WHERE subject = ? AND name = ?
`

type DeleteRiderCredentialParams struct {
	Subject string
	Name    string
}

func (q *Queries) DeleteRiderCredential(ctx context.Context, arg DeleteRiderCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteRiderCredential, arg.Subject, arg.Name)
	return err
}

const deleteRiderCredentials = `-- name: DeleteRiderCredentials :exec
DELETE FROM rider_credentials WHERE subject = ?
`

func (q *Queries) DeleteRiderCredentials(ctx context.Context, subject string) error {
	_, err := q.db.ExecContext(ctx, deleteRiderCredentials, subject)
	return err
}

const getRiderProfile = `-- name: GetRiderProfile :one
SELECT max_heart_rate_bpm, resting_heart_rate_bpm, threshold_heart_rate_bpm,
  functional_threshold_power_watts, rider_mass_kg, bike_mass_kg,
  drag_area_m2, rolling_resistance
FROM rider_profiles
WHERE subject = ?
`

type GetRiderProfileRow struct {
	MaxHeartRateBpm               sql.NullFloat64
	RestingHeartRateBpm           sql.NullFloat64
	ThresholdHeartRateBpm         sql.NullFloat64
	FunctionalThresholdPowerWatts sql.NullFloat64
	RiderMassKg                   sql.NullFloat64
	BikeMassKg                    sql.NullFloat64
	DragAreaM2                    sql.NullFloat64
	RollingResistance             sql.NullFloat64
}

func (q *Queries) GetRiderProfile(ctx context.Context, subject string) (GetRiderProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getRiderProfile, subject)
	var i GetRiderProfileRow
	err := row.Scan(
		&i.MaxHeartRateBpm,
		&i.RestingHeartRateBpm,
		&i.ThresholdHeartRateBpm,
		&i.FunctionalThresholdPowerWatts,
		&i.RiderMassKg,
		&i.BikeMassKg,
		&i.DragAreaM2,
		&i.RollingResistance,
	)
	return i, err
}

const listActivitySensorSamples = `-- name: ListActivitySensorSamples :many
SELECT r.target_slot, r.workout_id, r.recorded_at_unix, r.heart_rate_bpm, r.power_watts
FROM activity_records AS r
JOIN activities AS a ON a.target_slot = r.target_slot AND a.workout_id = r.workout_id
WHERE a.started_at_unix >= ?1
  AND r.target_slot IN (/*SLICE:target_slots*/?)
  AND (r.heart_rate_bpm IS NOT NULL OR r.power_watts IS NOT NULL)
ORDER BY r.target_slot, r.workout_id, r.record_index
`

type ListActivitySensorSamplesParams struct {
	SinceUnix   int64
	TargetSlots []string
}

type ListActivitySensorSamplesRow struct {
	TargetSlot     string
	WorkoutID      int64
	RecordedAtUnix int64
	HeartRateBpm   sql.NullFloat64
	PowerWatts     sql.NullFloat64
}

// The scalar bound before the slice, as ListActivityRides does: sqlc numbers a
// parameter that follows an expanded slice by its source position, which is no
// longer the position it binds at.
func (q *Queries) ListActivitySensorSamples(ctx context.Context, arg ListActivitySensorSamplesParams) ([]ListActivitySensorSamplesRow, error) {
	query := listActivitySensorSamples
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SinceUnix)
	if len(arg.TargetSlots) > 0 {
		for _, v := range arg.TargetSlots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:target_slots*/?", strings.Repeat(",?", len(arg.TargetSlots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:target_slots*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitySensorSamplesRow{}
	for rows.Next() {
		var i ListActivitySensorSamplesRow
		if err := rows.Scan(
			&i.TargetSlot,
			&i.WorkoutID,
			&i.RecordedAtUnix,
			&i.HeartRateBpm,
			&i.PowerWatts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiderCredentials = `-- name: ListRiderCredentials :many
SELECT name, value FROM rider_credentials WHERE subject = ?
`

type ListRiderCredentialsRow struct {
	Name  string
	Value []byte
}

func (q *Queries) ListRiderCredentials(ctx context.Context, subject string) ([]ListRiderCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRiderCredentials, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRiderCredentialsRow{}
	for rows.Next() {
		var i ListRiderCredentialsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiderRampCandidates = `-- name: ListRiderRampCandidates :many
SELECT a.moving_seconds, m.best_power_60s, m.best_power_300s
FROM activity_metrics AS m
JOIN activities AS a ON a.target_slot = m.target_slot AND a.workout_id = m.workout_id
WHERE a.started_at_unix >= ?1
  AND a.target_slot IN (/*SLICE:target_slots*/?)
  AND m.best_power_60s IS NOT NULL
  AND m.best_power_300s IS NOT NULL
`

type ListRiderRampCandidatesParams struct {
	SinceUnix   int64
	TargetSlots []string
}

type ListRiderRampCandidatesRow struct {
	MovingSeconds float64
	BestPower60s  sql.NullFloat64
	BestPower300s sql.NullFloat64
}

// Every ride that could be a ramp test, over the rider's own targets. The
// shape test itself (moving time, the one-to-five-minute power ratio) is
// rider.RampThresholdPower's job; this only needs a ride whose derivation
// actually reached the power curve, so a ride still awaiting it is left out
// rather than forwarded as a zero.
// The scalar bound before the slice, as ListActivitySensorSamples does.
func (q *Queries) ListRiderRampCandidates(ctx context.Context, arg ListRiderRampCandidatesParams) ([]ListRiderRampCandidatesRow, error) {
	query := listRiderRampCandidates
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SinceUnix)
	if len(arg.TargetSlots) > 0 {
		for _, v := range arg.TargetSlots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:target_slots*/?", strings.Repeat(",?", len(arg.TargetSlots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:target_slots*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRiderRampCandidatesRow{}
	for rows.Next() {
		var i ListRiderRampCandidatesRow
		if err := rows.Scan(&i.MovingSeconds, &i.BestPower60s, &i.BestPower300s); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRiderStoppingRides = `-- name: ListRiderStoppingRides :many
SELECT moving_seconds, elapsed_seconds, distance_metres
FROM activities
WHERE started_at_unix >= ?1
  AND target_slot IN (/*SLICE:target_slots*/?)
  AND workout_type_id IN (/*SLICE:workout_type_ids*/?)
`

type ListRiderStoppingRidesParams struct {
	SinceUnix      int64
	TargetSlots    []string
	WorkoutTypeIds []int64
}

type ListRiderStoppingRidesRow struct {
	MovingSeconds  float64
	ElapsedSeconds float64
	DistanceMetres float64
}

// The scalar bound before the slices, as ListActivitySensorSamples does.
func (q *Queries) ListRiderStoppingRides(ctx context.Context, arg ListRiderStoppingRidesParams) ([]ListRiderStoppingRidesRow, error) {
	query := listRiderStoppingRides
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SinceUnix)
	if len(arg.TargetSlots) > 0 {
		for _, v := range arg.TargetSlots {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:target_slots*/?", strings.Repeat(",?", len(arg.TargetSlots))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:target_slots*/?", "NULL", 1)
	}
	if len(arg.WorkoutTypeIds) > 0 {
		for _, v := range arg.WorkoutTypeIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:workout_type_ids*/?", strings.Repeat(",?", len(arg.WorkoutTypeIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:workout_type_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRiderStoppingRidesRow{}
	for rows.Next() {
		var i ListRiderStoppingRidesRow
		if err := rows.Scan(&i.MovingSeconds, &i.ElapsedSeconds, &i.DistanceMetres); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRiderCredential = `-- name: UpsertRiderCredential :exec
INSERT INTO rider_credentials (subject, name, value, updated_at_unix)
VALUES (?, ?, ?, ?)
ON CONFLICT(subject, name) DO UPDATE SET value = excluded.value,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertRiderCredentialParams struct {
	Subject       string
	Name          string
	Value         []byte
	UpdatedAtUnix int64
}

func (q *Queries) UpsertRiderCredential(ctx context.Context, arg UpsertRiderCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertRiderCredential,
		arg.Subject,
		arg.Name,
		arg.Value,
		arg.UpdatedAtUnix,
	)
	return err
}

const upsertRiderProfile = `-- name: UpsertRiderProfile :exec
INSERT INTO rider_profiles (
  subject, max_heart_rate_bpm, resting_heart_rate_bpm, threshold_heart_rate_bpm,
  functional_threshold_power_watts, rider_mass_kg, bike_mass_kg,
  drag_area_m2, rolling_resistance, updated_at_unix
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(subject) DO UPDATE SET
  max_heart_rate_bpm = excluded.max_heart_rate_bpm,
  resting_heart_rate_bpm = excluded.resting_heart_rate_bpm,
  threshold_heart_rate_bpm = excluded.threshold_heart_rate_bpm,
  functional_threshold_power_watts = excluded.functional_threshold_power_watts,
  rider_mass_kg = excluded.rider_mass_kg,
  bike_mass_kg = excluded.bike_mass_kg,
  drag_area_m2 = excluded.drag_area_m2,
  rolling_resistance = excluded.rolling_resistance,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertRiderProfileParams struct {
	Subject                       string
	MaxHeartRateBpm               sql.NullFloat64
	RestingHeartRateBpm           sql.NullFloat64
	ThresholdHeartRateBpm         sql.NullFloat64
	FunctionalThresholdPowerWatts sql.NullFloat64
	RiderMassKg                   sql.NullFloat64
	BikeMassKg                    sql.NullFloat64
	DragAreaM2                    sql.NullFloat64
	RollingResistance             sql.NullFloat64
	UpdatedAtUnix                 int64
}

func (q *Queries) UpsertRiderProfile(ctx context.Context, arg UpsertRiderProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertRiderProfile,
		arg.Subject,
		arg.MaxHeartRateBpm,
		arg.RestingHeartRateBpm,
		arg.ThresholdHeartRateBpm,
		arg.FunctionalThresholdPowerWatts,
		arg.RiderMassKg,
		arg.BikeMassKg,
		arg.DragAreaM2,
		arg.RollingResistance,
		arg.UpdatedAtUnix,
	)
	return err
}
