// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routematch.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearActivityClimbAttempts = `-- name: ClearActivityClimbAttempts :execrows
DELETE FROM activity_climb_attempt WHERE target_slot = ?
`

func (q *Queries) ClearActivityClimbAttempts(ctx context.Context, targetSlot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearActivityClimbAttempts, targetSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEstimatedActivityClimbAttemptsForTarget = `-- name: ClearEstimatedActivityClimbAttemptsForTarget :execrows
DELETE FROM activity_climb_attempt AS c
WHERE c.target_slot = ?1
  AND c.workout_id IN (
    SELECT DISTINCT r.workout_id FROM activity_records AS r
    WHERE r.target_slot = ?1 AND r.estimated_power_watts IS NOT NULL
  )
`

// A rider clearing their profile takes only the climbs and matches an
// estimate shaped with it: a metered ride's route match owes the profile
// nothing, and must survive a clear that names no bicycle or mass at all.
func (q *Queries) ClearEstimatedActivityClimbAttemptsForTarget(ctx context.Context, targetSlot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearEstimatedActivityClimbAttemptsForTarget, targetSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearEstimatedActivityRouteMatchesForTarget = `-- name: ClearEstimatedActivityRouteMatchesForTarget :execrows
DELETE FROM activity_route_match AS m
WHERE m.target_slot = ?1
  AND m.workout_id IN (
    SELECT DISTINCT r.workout_id FROM activity_records AS r
    WHERE r.target_slot = ?1 AND r.estimated_power_watts IS NOT NULL
  )
`

func (q *Queries) ClearEstimatedActivityRouteMatchesForTarget(ctx context.Context, targetSlot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearEstimatedActivityRouteMatchesForTarget, targetSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteActivityClimbAttempts = `-- name: DeleteActivityClimbAttempts :exec
DELETE FROM activity_climb_attempt WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivityClimbAttemptsParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityClimbAttempts(ctx context.Context, arg DeleteActivityClimbAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityClimbAttempts, arg.TargetSlot, arg.WorkoutID)
	return err
}

const deleteActivityRouteMatch = `-- name: DeleteActivityRouteMatch :exec
DELETE FROM activity_route_match
WHERE target_slot = ?1 AND workout_id = ?2
`

type DeleteActivityRouteMatchParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityRouteMatch(ctx context.Context, arg DeleteActivityRouteMatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityRouteMatch, arg.TargetSlot, arg.WorkoutID)
	return err
}

const deleteActivityRouteMatchesForTarget = `-- name: DeleteActivityRouteMatchesForTarget :execrows
DELETE FROM activity_route_match WHERE target_slot = ?1
`

func (q *Queries) DeleteActivityRouteMatchesForTarget(ctx context.Context, targetSlot string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteActivityRouteMatchesForTarget, targetSlot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertActivityClimbAttempt = `-- name: InsertActivityClimbAttempt :exec
INSERT INTO activity_climb_attempt (
  target_slot, workout_id, climb_index, seconds, heart_rate_bpm, power_watts, estimated_power_watts
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertActivityClimbAttemptParams struct {
	TargetSlot          string
	WorkoutID           int64
	ClimbIndex          int64
	Seconds             float64
	HeartRateBpm        sql.NullFloat64
	PowerWatts          sql.NullFloat64
	EstimatedPowerWatts sql.NullFloat64
}

func (q *Queries) InsertActivityClimbAttempt(ctx context.Context, arg InsertActivityClimbAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertActivityClimbAttempt,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.ClimbIndex,
		arg.Seconds,
		arg.HeartRateBpm,
		arg.PowerWatts,
		arg.EstimatedPowerWatts,
	)
	return err
}

const listActivitiesAwaitingRouteMatch = `-- name: ListActivitiesAwaitingRouteMatch :many
SELECT a.workout_id
FROM activities AS a
LEFT JOIN activity_route_match AS m ON m.target_slot = a.target_slot AND m.workout_id = a.workout_id
WHERE a.target_slot = ?1
  AND a.records_state = 'stored'
  AND a.workout_type_id NOT IN (SELECT value FROM json_each(CAST(?2 AS TEXT)))
  AND (m.workout_id IS NULL OR m.library_hash <> ?3)
ORDER BY a.started_at_unix DESC, a.workout_id DESC
`

type ListActivitiesAwaitingRouteMatchParams struct {
	TargetSlot    string
	IndoorTypeIds string
	LibraryHash   string
}

// Rides whose samples are stored and whose match was never worked out, or was
// worked out against a library that has since changed.
func (q *Queries) ListActivitiesAwaitingRouteMatch(ctx context.Context, arg ListActivitiesAwaitingRouteMatchParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesAwaitingRouteMatch, arg.TargetSlot, arg.IndoorTypeIds, arg.LibraryHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workout_id int64
		if err := rows.Scan(&workout_id); err != nil {
			return nil, err
		}
		items = append(items, workout_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityRouteMatches = `-- name: ListActivityRouteMatches :many
SELECT workout_id, provider, route_id, stage_order, route_coverage, ride_coverage, direction
FROM activity_route_match
WHERE target_slot = ?1 AND provider IS NOT NULL
`

type ListActivityRouteMatchesRow struct {
	WorkoutID     int64
	Provider      sql.NullString
	RouteID       sql.NullInt64
	StageOrder    sql.NullInt64
	RouteCoverage sql.NullFloat64
	RideCoverage  sql.NullFloat64
	Direction     sql.NullString
}

// Every match one target holds, for the ride list and the ride page.
func (q *Queries) ListActivityRouteMatches(ctx context.Context, targetSlot string) ([]ListActivityRouteMatchesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityRouteMatches, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityRouteMatchesRow{}
	for rows.Next() {
		var i ListActivityRouteMatchesRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.Provider,
			&i.RouteID,
			&i.StageOrder,
			&i.RouteCoverage,
			&i.RideCoverage,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryStageGeometry = `-- name: ListLibraryStageGeometry :many
SELECT provider, route_id, stage_order, coordinates
FROM stage_geometry
ORDER BY provider, route_id, stage_order
`

type ListLibraryStageGeometryRow struct {
	Provider    string
	RouteID     int64
	StageOrder  int64
	Coordinates []byte
}

// Every route a ride may be matched to, with the line it is matched against.
// The stage's content hash is deliberately not read: it covers the title and
// the source revision too, and a rename owes no ride a fresh match.
func (q *Queries) ListLibraryStageGeometry(ctx context.Context) ([]ListLibraryStageGeometryRow, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryStageGeometry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLibraryStageGeometryRow{}
	for rows.Next() {
		var i ListLibraryStageGeometryRow
		if err := rows.Scan(
			&i.Provider,
			&i.RouteID,
			&i.StageOrder,
			&i.Coordinates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteActivities = `-- name: ListRouteActivities :many
SELECT m.workout_id, m.route_coverage, m.ride_coverage, m.direction
FROM activity_route_match AS m
JOIN activities AS a ON a.target_slot = m.target_slot AND a.workout_id = m.workout_id
WHERE m.target_slot = ?1
  AND m.provider = ?2
  AND m.route_id = ?3
  AND m.stage_order = ?4
ORDER BY a.started_at_unix DESC, m.workout_id DESC
`

type ListRouteActivitiesParams struct {
	TargetSlot string
	Provider   sql.NullString
	RouteID    sql.NullInt64
	StageOrder sql.NullInt64
}

type ListRouteActivitiesRow struct {
	WorkoutID     int64
	RouteCoverage sql.NullFloat64
	RideCoverage  sql.NullFloat64
	Direction     sql.NullString
}

// The rides one target rode on one route, newest first.
func (q *Queries) ListRouteActivities(ctx context.Context, arg ListRouteActivitiesParams) ([]ListRouteActivitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRouteActivities,
		arg.TargetSlot,
		arg.Provider,
		arg.RouteID,
		arg.StageOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteActivitiesRow{}
	for rows.Next() {
		var i ListRouteActivitiesRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.RouteCoverage,
			&i.RideCoverage,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteClimbAttempts = `-- name: ListRouteClimbAttempts :many
SELECT c.workout_id, c.climb_index, c.seconds, c.heart_rate_bpm, c.power_watts,
  c.estimated_power_watts, a.started_at_unix
FROM activity_climb_attempt AS c
JOIN activities AS a ON a.target_slot = c.target_slot AND a.workout_id = c.workout_id
JOIN activity_route_match AS m ON m.target_slot = c.target_slot AND m.workout_id = c.workout_id
WHERE c.target_slot = ?1 AND m.provider = ?2
  AND m.route_id = ?3 AND m.stage_order = ?4
ORDER BY a.started_at_unix DESC, c.climb_index
`

type ListRouteClimbAttemptsParams struct {
	TargetSlot string
	Provider   sql.NullString
	RouteID    sql.NullInt64
	StageOrder sql.NullInt64
}

type ListRouteClimbAttemptsRow struct {
	WorkoutID           int64
	ClimbIndex          int64
	Seconds             float64
	HeartRateBpm        sql.NullFloat64
	PowerWatts          sql.NullFloat64
	EstimatedPowerWatts sql.NullFloat64
	StartedAtUnix       int64
}

// Every attempt one target's rides made at one route's climbs. The order is for
// a stable read, not the order they are served in: the endpoint sorts a climb's
// attempts by how long each took, quickest first.
func (q *Queries) ListRouteClimbAttempts(ctx context.Context, arg ListRouteClimbAttemptsParams) ([]ListRouteClimbAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRouteClimbAttempts,
		arg.TargetSlot,
		arg.Provider,
		arg.RouteID,
		arg.StageOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRouteClimbAttemptsRow{}
	for rows.Next() {
		var i ListRouteClimbAttemptsRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.ClimbIndex,
			&i.Seconds,
			&i.HeartRateBpm,
			&i.PowerWatts,
			&i.EstimatedPowerWatts,
			&i.StartedAtUnix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertActivityRouteMatch = `-- name: UpsertActivityRouteMatch :exec
INSERT INTO activity_route_match (
  target_slot, workout_id, provider, route_id, stage_order,
  route_coverage, ride_coverage, direction, library_hash, matched_at_unix
) VALUES (
  ?1, ?2, ?3, ?4, ?5,
  ?6, ?7, ?8,
  ?9, ?10
)
ON CONFLICT (target_slot, workout_id) DO UPDATE SET
  provider = excluded.provider,
  route_id = excluded.route_id,
  stage_order = excluded.stage_order,
  route_coverage = excluded.route_coverage,
  ride_coverage = excluded.ride_coverage,
  direction = excluded.direction,
  library_hash = excluded.library_hash,
  matched_at_unix = excluded.matched_at_unix
`

type UpsertActivityRouteMatchParams struct {
	TargetSlot    string
	WorkoutID     int64
	Provider      sql.NullString
	RouteID       sql.NullInt64
	StageOrder    sql.NullInt64
	RouteCoverage sql.NullFloat64
	RideCoverage  sql.NullFloat64
	Direction     sql.NullString
	LibraryHash   string
	MatchedAtUnix int64
}

func (q *Queries) UpsertActivityRouteMatch(ctx context.Context, arg UpsertActivityRouteMatchParams) error {
	_, err := q.db.ExecContext(ctx, upsertActivityRouteMatch,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.Provider,
		arg.RouteID,
		arg.StageOrder,
		arg.RouteCoverage,
		arg.RideCoverage,
		arg.Direction,
		arg.LibraryHash,
		arg.MatchedAtUnix,
	)
	return err
}
