// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const deleteRuntimeBasemaps = `-- name: DeleteRuntimeBasemaps :exec
DELETE FROM runtime_basemap
`

func (q *Queries) DeleteRuntimeBasemaps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeBasemaps)
	return err
}

const deleteRuntimeSecret = `-- name: DeleteRuntimeSecret :exec
DELETE FROM runtime_secret WHERE name = ?
`

func (q *Queries) DeleteRuntimeSecret(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeSecret, name)
	return err
}

const deleteRuntimeSources = `-- name: DeleteRuntimeSources :exec
DELETE FROM runtime_source
`

func (q *Queries) DeleteRuntimeSources(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeSources)
	return err
}

const deleteRuntimeSurfaceRegions = `-- name: DeleteRuntimeSurfaceRegions :exec
DELETE FROM runtime_surface_region
`

func (q *Queries) DeleteRuntimeSurfaceRegions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRuntimeSurfaceRegions)
	return err
}

const getRuntimeSettings = `-- name: GetRuntimeSettings :one
SELECT allow_empty_source_deletion, stale_after_seconds, sync_initial_delay_seconds,
  notifications_enabled, pushover_base_url, surface_rebuild_interval_seconds,
  wahoo_api_base_url, wahoo_oauth_base_url, wahoo_client_id,
  timezone
FROM runtime_settings
WHERE id = 1
`

type GetRuntimeSettingsRow struct {
	AllowEmptySourceDeletion      int64
	StaleAfterSeconds             int64
	SyncInitialDelaySeconds       int64
	NotificationsEnabled          int64
	PushoverBaseUrl               string
	SurfaceRebuildIntervalSeconds int64
	WahooApiBaseUrl               string
	WahooOauthBaseUrl             string
	WahooClientID                 string
	Timezone                      string
}

func (q *Queries) GetRuntimeSettings(ctx context.Context) (GetRuntimeSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getRuntimeSettings)
	var i GetRuntimeSettingsRow
	err := row.Scan(
		&i.AllowEmptySourceDeletion,
		&i.StaleAfterSeconds,
		&i.SyncInitialDelaySeconds,
		&i.NotificationsEnabled,
		&i.PushoverBaseUrl,
		&i.SurfaceRebuildIntervalSeconds,
		&i.WahooApiBaseUrl,
		&i.WahooOauthBaseUrl,
		&i.WahooClientID,
		&i.Timezone,
	)
	return i, err
}

const insertRuntimeBasemap = `-- name: InsertRuntimeBasemap :exec
INSERT INTO runtime_basemap (position, name, style_url, style_url_dark, dark_cartography)
VALUES (?, ?, ?, ?, ?)
`

type InsertRuntimeBasemapParams struct {
	Position        int64
	Name            string
	StyleUrl        string
	StyleUrlDark    string
	DarkCartography int64
}

func (q *Queries) InsertRuntimeBasemap(ctx context.Context, arg InsertRuntimeBasemapParams) error {
	_, err := q.db.ExecContext(ctx, insertRuntimeBasemap,
		arg.Position,
		arg.Name,
		arg.StyleUrl,
		arg.StyleUrlDark,
		arg.DarkCartography,
	)
	return err
}

const insertRuntimeSource = `-- name: InsertRuntimeSource :exec
INSERT INTO runtime_source (position, provider, base_url) VALUES (?, ?, ?)
`

type InsertRuntimeSourceParams struct {
	Position int64
	Provider string
	BaseUrl  string
}

func (q *Queries) InsertRuntimeSource(ctx context.Context, arg InsertRuntimeSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertRuntimeSource, arg.Position, arg.Provider, arg.BaseUrl)
	return err
}

const insertRuntimeSurfaceRegion = `-- name: InsertRuntimeSurfaceRegion :exec
INSERT INTO runtime_surface_region (position, region) VALUES (?, ?)
`

type InsertRuntimeSurfaceRegionParams struct {
	Position int64
	Region   string
}

func (q *Queries) InsertRuntimeSurfaceRegion(ctx context.Context, arg InsertRuntimeSurfaceRegionParams) error {
	_, err := q.db.ExecContext(ctx, insertRuntimeSurfaceRegion, arg.Position, arg.Region)
	return err
}

const listRuntimeBasemaps = `-- name: ListRuntimeBasemaps :many
SELECT name, style_url, style_url_dark, dark_cartography
FROM runtime_basemap
ORDER BY position
`

type ListRuntimeBasemapsRow struct {
	Name            string
	StyleUrl        string
	StyleUrlDark    string
	DarkCartography int64
}

func (q *Queries) ListRuntimeBasemaps(ctx context.Context) ([]ListRuntimeBasemapsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeBasemaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeBasemapsRow{}
	for rows.Next() {
		var i ListRuntimeBasemapsRow
		if err := rows.Scan(
			&i.Name,
			&i.StyleUrl,
			&i.StyleUrlDark,
			&i.DarkCartography,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeSecrets = `-- name: ListRuntimeSecrets :many
SELECT name, value FROM runtime_secret
`

type ListRuntimeSecretsRow struct {
	Name  string
	Value []byte
}

func (q *Queries) ListRuntimeSecrets(ctx context.Context) ([]ListRuntimeSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeSecretsRow{}
	for rows.Next() {
		var i ListRuntimeSecretsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeSources = `-- name: ListRuntimeSources :many
SELECT provider, base_url FROM runtime_source ORDER BY position
`

type ListRuntimeSourcesRow struct {
	Provider string
	BaseUrl  string
}

func (q *Queries) ListRuntimeSources(ctx context.Context) ([]ListRuntimeSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRuntimeSourcesRow{}
	for rows.Next() {
		var i ListRuntimeSourcesRow
		if err := rows.Scan(&i.Provider, &i.BaseUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeSurfaceRegions = `-- name: ListRuntimeSurfaceRegions :many
SELECT region FROM runtime_surface_region ORDER BY position
`

func (q *Queries) ListRuntimeSurfaceRegions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRuntimeSurfaceRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var region string
		if err := rows.Scan(&region); err != nil {
			return nil, err
		}
		items = append(items, region)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuntimeSettings = `-- name: UpdateRuntimeSettings :exec
UPDATE runtime_settings
SET allow_empty_source_deletion = ?, stale_after_seconds = ?, sync_initial_delay_seconds = ?,
  notifications_enabled = ?, pushover_base_url = ?, surface_rebuild_interval_seconds = ?,
  wahoo_api_base_url = ?, wahoo_oauth_base_url = ?, wahoo_client_id = ?,
  timezone = ?, updated_at_unix = ?
WHERE id = 1
`

type UpdateRuntimeSettingsParams struct {
	AllowEmptySourceDeletion      int64
	StaleAfterSeconds             int64
	SyncInitialDelaySeconds       int64
	NotificationsEnabled          int64
	PushoverBaseUrl               string
	SurfaceRebuildIntervalSeconds int64
	WahooApiBaseUrl               string
	WahooOauthBaseUrl             string
	WahooClientID                 string
	Timezone                      string
	UpdatedAtUnix                 int64
}

func (q *Queries) UpdateRuntimeSettings(ctx context.Context, arg UpdateRuntimeSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateRuntimeSettings,
		arg.AllowEmptySourceDeletion,
		arg.StaleAfterSeconds,
		arg.SyncInitialDelaySeconds,
		arg.NotificationsEnabled,
		arg.PushoverBaseUrl,
		arg.SurfaceRebuildIntervalSeconds,
		arg.WahooApiBaseUrl,
		arg.WahooOauthBaseUrl,
		arg.WahooClientID,
		arg.Timezone,
		arg.UpdatedAtUnix,
	)
	return err
}

const upsertRuntimeSecret = `-- name: UpsertRuntimeSecret :exec
INSERT INTO runtime_secret (name, value, updated_at_unix)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET value = excluded.value,
  updated_at_unix = excluded.updated_at_unix
`

type UpsertRuntimeSecretParams struct {
	Name          string
	Value         []byte
	UpdatedAtUnix int64
}

func (q *Queries) UpsertRuntimeSecret(ctx context.Context, arg UpsertRuntimeSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertRuntimeSecret, arg.Name, arg.Value, arg.UpdatedAtUnix)
	return err
}
