// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: taskruns.sql

package sqlcgen

import (
	"context"
)

const getLastTaskOutcome = `-- name: GetLastTaskOutcome :one
SELECT outcome FROM task_runs WHERE task = ? AND argument = ?
ORDER BY finished_at_unix DESC, id DESC LIMIT 1
`

type GetLastTaskOutcomeParams struct {
	Task     string
	Argument string
}

func (q *Queries) GetLastTaskOutcome(ctx context.Context, arg GetLastTaskOutcomeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastTaskOutcome, arg.Task, arg.Argument)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const getLastTaskRunPosition = `-- name: GetLastTaskRunPosition :one
SELECT CAST(COALESCE(MAX(finished_at_unix), 0) AS INTEGER) AS finished_at_unix,
  CAST(COALESCE(MAX(id), 0) AS INTEGER) AS id
FROM task_runs
`

type GetLastTaskRunPositionRow struct {
	FinishedAtUnix int64
	ID             int64
}

func (q *Queries) GetLastTaskRunPosition(ctx context.Context) (GetLastTaskRunPositionRow, error) {
	row := q.db.QueryRowContext(ctx, getLastTaskRunPosition)
	var i GetLastTaskRunPositionRow
	err := row.Scan(&i.FinishedAtUnix, &i.ID)
	return i, err
}

const getLastTaskSuccess = `-- name: GetLastTaskSuccess :one
SELECT finished_at_unix FROM task_runs
WHERE task = ? AND argument = ? AND outcome = ?
ORDER BY finished_at_unix DESC, id DESC LIMIT 1
`

type GetLastTaskSuccessParams struct {
	Task     string
	Argument string
	Outcome  string
}

func (q *Queries) GetLastTaskSuccess(ctx context.Context, arg GetLastTaskSuccessParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastTaskSuccess, arg.Task, arg.Argument, arg.Outcome)
	var finished_at_unix int64
	err := row.Scan(&finished_at_unix)
	return finished_at_unix, err
}

const insertTaskRun = `-- name: InsertTaskRun :exec
INSERT INTO task_runs (task, argument, trigger, started_at_unix, finished_at_unix, outcome, detail, reference)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTaskRunParams struct {
	Task           string
	Argument       string
	Trigger        string
	StartedAtUnix  int64
	FinishedAtUnix int64
	Outcome        string
	Detail         string
	Reference      string
}

func (q *Queries) InsertTaskRun(ctx context.Context, arg InsertTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, insertTaskRun,
		arg.Task,
		arg.Argument,
		arg.Trigger,
		arg.StartedAtUnix,
		arg.FinishedAtUnix,
		arg.Outcome,
		arg.Detail,
		arg.Reference,
	)
	return err
}

const listTaskOutcomesForFaultStreak = `-- name: ListTaskOutcomesForFaultStreak :many
SELECT outcome, finished_at_unix FROM task_runs
WHERE task = ? AND argument = ?
ORDER BY finished_at_unix DESC, id DESC LIMIT ?
`

type ListTaskOutcomesForFaultStreakParams struct {
	Task     string
	Argument string
	Limit    int64
}

type ListTaskOutcomesForFaultStreakRow struct {
	Outcome        string
	FinishedAtUnix int64
}

func (q *Queries) ListTaskOutcomesForFaultStreak(ctx context.Context, arg ListTaskOutcomesForFaultStreakParams) ([]ListTaskOutcomesForFaultStreakRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskOutcomesForFaultStreak, arg.Task, arg.Argument, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskOutcomesForFaultStreakRow{}
	for rows.Next() {
		var i ListTaskOutcomesForFaultStreakRow
		if err := rows.Scan(&i.Outcome, &i.FinishedAtUnix); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRuns = `-- name: ListTaskRuns :many
SELECT argument, started_at_unix, finished_at_unix, outcome, detail
FROM task_runs WHERE task = ? ORDER BY finished_at_unix DESC, id DESC
`

type ListTaskRunsRow struct {
	Argument       string
	StartedAtUnix  int64
	FinishedAtUnix int64
	Outcome        string
	Detail         string
}

func (q *Queries) ListTaskRuns(ctx context.Context, task string) ([]ListTaskRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRuns, task)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskRunsRow{}
	for rows.Next() {
		var i ListTaskRunsRow
		if err := rows.Scan(
			&i.Argument,
			&i.StartedAtUnix,
			&i.FinishedAtUnix,
			&i.Outcome,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRunsPage = `-- name: ListTaskRunsPage :many
SELECT id, task, argument, trigger, started_at_unix, finished_at_unix, outcome, detail, reference
FROM task_runs
WHERE (finished_at_unix, id) < (?1, ?2)
  AND (?3 = '' OR task = ?3)
ORDER BY finished_at_unix DESC, id DESC
LIMIT ?4
`

type ListTaskRunsPageParams struct {
	FinishedBefore int64
	IDBefore       int64
	TaskFilter     interface{}
	RowLimit       int64
}

type ListTaskRunsPageRow struct {
	ID             int64
	Task           string
	Argument       string
	Trigger        string
	StartedAtUnix  int64
	FinishedAtUnix int64
	Outcome        string
	Detail         string
	Reference      string
}

func (q *Queries) ListTaskRunsPage(ctx context.Context, arg ListTaskRunsPageParams) ([]ListTaskRunsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRunsPage,
		arg.FinishedBefore,
		arg.IDBefore,
		arg.TaskFilter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskRunsPageRow{}
	for rows.Next() {
		var i ListTaskRunsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Task,
			&i.Argument,
			&i.Trigger,
			&i.StartedAtUnix,
			&i.FinishedAtUnix,
			&i.Outcome,
			&i.Detail,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTaskRuns = `-- name: PruneTaskRuns :exec
DELETE FROM task_runs
WHERE task_runs.task = ?1
  AND id NOT IN (
    SELECT id FROM task_runs
    WHERE task_runs.task = ?1
    ORDER BY finished_at_unix DESC, id DESC
    LIMIT ?2
  )
  AND EXISTS (
    SELECT 1 FROM task_runs newer
    WHERE newer.task = task_runs.task AND newer.argument = task_runs.argument
      AND (newer.finished_at_unix, newer.id) > (task_runs.finished_at_unix, task_runs.id)
  )
`

type PruneTaskRunsParams struct {
	TaskName string
	Retain   int64
}

func (q *Queries) PruneTaskRuns(ctx context.Context, arg PruneTaskRunsParams) error {
	_, err := q.db.ExecContext(ctx, pruneTaskRuns, arg.TaskName, arg.Retain)
	return err
}
