// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteActivityWeather = `-- name: DeleteActivityWeather :exec
DELETE FROM activity_weather WHERE target_slot = ? AND workout_id = ?
`

type DeleteActivityWeatherParams struct {
	TargetSlot string
	WorkoutID  int64
}

func (q *Queries) DeleteActivityWeather(ctx context.Context, arg DeleteActivityWeatherParams) error {
	_, err := q.db.ExecContext(ctx, deleteActivityWeather, arg.TargetSlot, arg.WorkoutID)
	return err
}

const insertActivityWeather = `-- name: InsertActivityWeather :exec
INSERT INTO activity_weather (
  target_slot, workout_id, hour_unix, step_seconds, temperature_celsius, apparent_temperature_celsius,
  precipitation_millimetres, precipitation_probability_percent, wind_speed_kmh,
  wind_direction_degrees, weather_code, cloud_cover_percent
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id, hour_unix) DO UPDATE SET
  step_seconds = excluded.step_seconds,
  temperature_celsius = excluded.temperature_celsius,
  apparent_temperature_celsius = excluded.apparent_temperature_celsius,
  precipitation_millimetres = excluded.precipitation_millimetres,
  precipitation_probability_percent = excluded.precipitation_probability_percent,
  wind_speed_kmh = excluded.wind_speed_kmh,
  wind_direction_degrees = excluded.wind_direction_degrees,
  weather_code = excluded.weather_code,
  cloud_cover_percent = excluded.cloud_cover_percent
`

type InsertActivityWeatherParams struct {
	TargetSlot                      string
	WorkoutID                       int64
	HourUnix                        int64
	StepSeconds                     int64
	TemperatureCelsius              float64
	ApparentTemperatureCelsius      float64
	PrecipitationMillimetres        float64
	PrecipitationProbabilityPercent sql.NullFloat64
	WindSpeedKmh                    float64
	WindDirectionDegrees            float64
	WeatherCode                     int64
	CloudCoverPercent               float64
}

func (q *Queries) InsertActivityWeather(ctx context.Context, arg InsertActivityWeatherParams) error {
	_, err := q.db.ExecContext(ctx, insertActivityWeather,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.HourUnix,
		arg.StepSeconds,
		arg.TemperatureCelsius,
		arg.ApparentTemperatureCelsius,
		arg.PrecipitationMillimetres,
		arg.PrecipitationProbabilityPercent,
		arg.WindSpeedKmh,
		arg.WindDirectionDegrees,
		arg.WeatherCode,
		arg.CloudCoverPercent,
	)
	return err
}

const listActivitiesAwaitingWeather = `-- name: ListActivitiesAwaitingWeather :many
SELECT a.workout_id, a.started_at_unix, a.elapsed_seconds
FROM activities AS a
LEFT JOIN activity_weather_reads AS r ON r.target_slot = a.target_slot AND r.workout_id = a.workout_id
WHERE a.target_slot = ?1
  AND a.records_state = 'stored'
  AND r.workout_id IS NULL
ORDER BY a.started_at_unix DESC, a.workout_id DESC
LIMIT ?2
`

type ListActivitiesAwaitingWeatherParams struct {
	TargetSlot string
	RowLimit   int64
}

type ListActivitiesAwaitingWeatherRow struct {
	WorkoutID      int64
	StartedAtUnix  int64
	ElapsedSeconds float64
}

// Rides whose weather has never been asked about. A read that failed for good
// left a row saying so, which is what keeps it out of this list.
func (q *Queries) ListActivitiesAwaitingWeather(ctx context.Context, arg ListActivitiesAwaitingWeatherParams) ([]ListActivitiesAwaitingWeatherRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivitiesAwaitingWeather, arg.TargetSlot, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesAwaitingWeatherRow{}
	for rows.Next() {
		var i ListActivitiesAwaitingWeatherRow
		if err := rows.Scan(&i.WorkoutID, &i.StartedAtUnix, &i.ElapsedSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityWeatherSteps = `-- name: ListActivityWeatherSteps :many
SELECT hour_unix AS at_unix, step_seconds, temperature_celsius, apparent_temperature_celsius,
  precipitation_millimetres, precipitation_probability_percent, wind_speed_kmh,
  wind_direction_degrees, weather_code, cloud_cover_percent
FROM activity_weather
WHERE target_slot = ? AND workout_id = ?
ORDER BY hour_unix
`

type ListActivityWeatherStepsParams struct {
	TargetSlot string
	WorkoutID  int64
}

type ListActivityWeatherStepsRow struct {
	AtUnix                          int64
	StepSeconds                     int64
	TemperatureCelsius              float64
	ApparentTemperatureCelsius      float64
	PrecipitationMillimetres        float64
	PrecipitationProbabilityPercent sql.NullFloat64
	WindSpeedKmh                    float64
	WindDirectionDegrees            float64
	WeatherCode                     int64
	CloudCoverPercent               float64
}

// Aliased to at_unix rather than the stored hour_unix: the column keeps its
// name so a preceding release can still read and write it, but every step of
// a ride is not necessarily an hour any more.
func (q *Queries) ListActivityWeatherSteps(ctx context.Context, arg ListActivityWeatherStepsParams) ([]ListActivityWeatherStepsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityWeatherSteps, arg.TargetSlot, arg.WorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityWeatherStepsRow{}
	for rows.Next() {
		var i ListActivityWeatherStepsRow
		if err := rows.Scan(
			&i.AtUnix,
			&i.StepSeconds,
			&i.TemperatureCelsius,
			&i.ApparentTemperatureCelsius,
			&i.PrecipitationMillimetres,
			&i.PrecipitationProbabilityPercent,
			&i.WindSpeedKmh,
			&i.WindDirectionDegrees,
			&i.WeatherCode,
			&i.CloudCoverPercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordActivityWeatherRead = `-- name: RecordActivityWeatherRead :exec
INSERT INTO activity_weather_reads (target_slot, workout_id, read_at_unix, hours)
VALUES (?, ?, ?, ?)
ON CONFLICT(target_slot, workout_id) DO UPDATE SET
  read_at_unix = excluded.read_at_unix,
  hours = excluded.hours
`

type RecordActivityWeatherReadParams struct {
	TargetSlot string
	WorkoutID  int64
	ReadAtUnix int64
	Hours      int64
}

func (q *Queries) RecordActivityWeatherRead(ctx context.Context, arg RecordActivityWeatherReadParams) error {
	_, err := q.db.ExecContext(ctx, recordActivityWeatherRead,
		arg.TargetSlot,
		arg.WorkoutID,
		arg.ReadAtUnix,
		arg.Hours,
	)
	return err
}

const summariseActivityWeather = `-- name: SummariseActivityWeather :many
SELECT workout_id,
  CAST(MIN(temperature_celsius) AS REAL) AS temperature_min_celsius,
  CAST(MAX(temperature_celsius) AS REAL) AS temperature_max_celsius,
  CAST(AVG(wind_speed_kmh) AS REAL) AS wind_speed_kmh,
  CAST(SUM(precipitation_millimetres) AS REAL) AS precipitation_millimetres,
  CAST(MAX(weather_code) AS INTEGER) AS weather_code
FROM activity_weather
WHERE target_slot = ?
GROUP BY workout_id
ORDER BY workout_id
`

type SummariseActivityWeatherRow struct {
	WorkoutID                int64
	TemperatureMinCelsius    float64
	TemperatureMaxCelsius    float64
	WindSpeedKmh             float64
	PrecipitationMillimetres float64
	WeatherCode              int64
}

// One row per ride rather than one per step: the listing wants a line about
// each ride, and a rider with years of history has a step of weather for every
// step they have ridden. The wind is a mean speed and never a mean direction: a
// bearing does not average, so the summary carries none.
func (q *Queries) SummariseActivityWeather(ctx context.Context, targetSlot string) ([]SummariseActivityWeatherRow, error) {
	rows, err := q.db.QueryContext(ctx, summariseActivityWeather, targetSlot)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummariseActivityWeatherRow{}
	for rows.Next() {
		var i SummariseActivityWeatherRow
		if err := rows.Scan(
			&i.WorkoutID,
			&i.TemperatureMinCelsius,
			&i.TemperatureMaxCelsius,
			&i.WindSpeedKmh,
			&i.PrecipitationMillimetres,
			&i.WeatherCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
