package sqlite

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/nobbs/domestique/internal/activity"
	"github.com/nobbs/domestique/internal/powerestimate"
	"github.com/nobbs/domestique/internal/sqlite/internal/sqlcgen"
	"github.com/nobbs/domestique/internal/trainingload"
)

// derivationVersion is which derivation wrote a stored row. Bumped whenever a
// derivation starts producing a figure the rows before it cannot hold, so those
// rows are listed again rather than keeping the new columns null for good.
const derivationVersion = 1

// ActivitiesAwaitingDerivation lists the target's rides whose stored samples
// could yield something this derivation now allows: those never derived, those
// derived against different profile values, and those an earlier derivation
// wrote. Newest first, so a rider watching a long recompute sees the rides they
// care about settle first.
func (s *Store) ActivitiesAwaitingDerivation(
	ctx context.Context, targetID string, inputs trainingload.Inputs,
) ([]int64, error) {
	ids, err := s.queries.ListActivitiesAwaitingDerivation(ctx, sqlcgen.ListActivitiesAwaitingDerivationParams{
		TargetSlot:         targetID,
		MaxHeartRate:       inputs.MaxHeartRateBPM,
		RestingHeartRate:   inputs.RestingHeartRateBPM,
		ThresholdHeartRate: inputs.ThresholdHeartRateBPM,
		ThresholdPower:     inputs.FunctionalThresholdPowerWatts,
		TotalMass:          inputs.TotalMassKG,
		DerivationVersion:  derivationVersion,
	})
	if err != nil {
		return nil, fmt.Errorf("listing activities awaiting derivation: %w", err)
	}

	return ids, nil
}

// ActivityRideSamples reads one ride's recorded series, split by what each of
// them is for. A record that carried no reading for a sensor is left out of
// that sensor's series rather than read as a zero, which would be rest the
// rider never took.
func (s *Store) ActivityRideSamples(
	ctx context.Context, targetID string, id int64,
) (activity.RideSamples, error) {
	rows, err := s.queries.ListActivitySensorRecords(ctx, sqlcgen.ListActivitySensorRecordsParams{
		TargetSlot: targetID,
		WorkoutID:  id,
	})
	if err != nil {
		return activity.RideSamples{}, fmt.Errorf("reading the recorded samples: %w", err)
	}
	samples := activity.RideSamples{}
	for index := range rows {
		row := &rows[index]
		at := time.Unix(row.RecordedAtUnix, 0).UTC()
		if row.HeartRateBpm.Valid {
			samples.HeartRate = append(samples.HeartRate, trainingload.Sample{At: at, Value: row.HeartRateBpm.Float64})
		}
		if row.CadenceRpm.Valid {
			samples.Cadence = append(samples.Cadence, trainingload.Sample{At: at, Value: row.CadenceRpm.Float64})
		}
		if row.PowerWatts.Valid {
			samples.Power = append(samples.Power, trainingload.Sample{At: at, Value: row.PowerWatts.Float64})
		}
		// A whole positioned sample — latitude and longitude both, as the track
		// endpoint defines one — plus an altitude and a distance. Without all of
		// them the model has no track, and a trainer ride's "grade" means
		// nothing; with fewer than the track itself needs, the estimate would be
		// shaped by samples nobody is ever shown.
		if row.Latitude.Valid && row.Longitude.Valid && row.AltitudeMetres.Valid && row.DistanceMetres.Valid {
			samples.Track = append(samples.Track, powerestimate.Sample{
				At:             at,
				DistanceMetres: row.DistanceMetres.Float64,
				AltitudeMetres: row.AltitudeMetres.Float64,
			})
			samples.TrackRecords = append(samples.TrackRecords, row.RecordIndex)
		}
	}

	return samples, nil
}

// setEstimatedPowerSQL is prepared once per ride rather than generated by
// sqlc, for the reason insertActivityRecordSQL is: a ride holds thousands of
// samples, and compiling the update per row is most of the cost of storing one.
const setEstimatedPowerSQL = `UPDATE activity_records SET estimated_power_watts = ?
WHERE target_slot = ? AND workout_id = ? AND record_index = ?`

// StoreEstimatedPower replaces one ride's estimated power series, in one
// transaction so a partial rewrite is never left behind as complete. An empty
// series clears whatever was there, which is what a ride that has stopped
// yielding an estimate needs.
func (s *Store) StoreEstimatedPower(
	ctx context.Context, targetID string, id int64, recordIndices []int64, estimates []powerestimate.Estimate,
) error {
	if len(recordIndices) != len(estimates) {
		return errors.New("an estimate per record or none")
	}
	transaction, beginErr := s.database.BeginTx(ctx, nil)
	if beginErr != nil {
		return fmt.Errorf("starting the estimated power write: %w", beginErr)
	}
	defer rollback(transaction)
	queries := s.queries.WithTx(transaction)
	// Cleared first, so a record that no longer yields an estimate does not keep
	// the one it had from a mass the rider has since changed.
	if clearErr := queries.ClearEstimatedPower(ctx, sqlcgen.ClearEstimatedPowerParams{
		TargetSlot: targetID, WorkoutID: id,
	}); clearErr != nil {
		return fmt.Errorf("clearing the estimated power: %w", clearErr)
	}
	// Prepared once for the whole ride, as the sample insert is: a long ride is
	// thousands of these, and preparing each one costs more than running it.
	update, prepareErr := transaction.PrepareContext(ctx, setEstimatedPowerSQL)
	if prepareErr != nil {
		return fmt.Errorf("preparing the estimated power update: %w", prepareErr)
	}
	defer closeStatement(update)
	for index, estimate := range estimates {
		if !estimate.Known {
			continue
		}
		if _, execErr := update.ExecContext(ctx, estimate.Watts, targetID, id, recordIndices[index]); execErr != nil {
			return fmt.Errorf("recording an estimated power: %w", execErr)
		}
	}
	if commitErr := transaction.Commit(); commitErr != nil {
		return fmt.Errorf("committing the estimated power: %w", commitErr)
	}

	return nil
}

// StoreActivityMetrics replaces one ride's derived numbers. A derivation that
// yielded nothing removes the row instead of writing one full of nulls: no row
// is what "this ride has nothing to say" already means everywhere else.
//
//nolint:gocritic // value param: metrics are plain numbers, copied as cheaply as a pointer.
func (s *Store) StoreActivityMetrics(
	ctx context.Context, targetID string, id int64, stored activity.RideMetrics,
) error {
	metrics, averages := stored.Load, stored.Averages
	if !stored.Derived() {
		if err := s.queries.DeleteActivityMetrics(ctx, sqlcgen.DeleteActivityMetricsParams{
			TargetSlot: targetID, WorkoutID: id,
		}); err != nil {
			return fmt.Errorf("clearing the activity metrics: %w", err)
		}

		return nil
	}
	zones := [5]sql.NullFloat64{}
	for index := range zones {
		zones[index] = nullFloat(metrics.Zones[index], metrics.HasZones)
	}
	if err := s.queries.UpsertActivityMetrics(ctx, sqlcgen.UpsertActivityMetricsParams{
		TargetSlot: targetID, WorkoutID: id,
		Zone1Seconds: zones[0], Zone2Seconds: zones[1], Zone3Seconds: zones[2],
		Zone4Seconds: zones[3], Zone5Seconds: zones[4],
		Trimp:                   nullFloat(metrics.TRIMP, metrics.HasTRIMP),
		HeartRateTss:            nullFloat(metrics.HeartRateTSS, metrics.HasHeartRateTSS),
		NormalizedPowerWatts:    nullFloat(metrics.Power.NormalizedWatts, metrics.HasPower),
		IntensityFactor:         nullFloat(metrics.Power.IntensityFactor, metrics.HasPower),
		PowerTss:                nullFloat(metrics.Power.TSS, metrics.HasPower),
		EstimatedPowerWatts:     nullFloat(metrics.EstimatedPowerWatts, metrics.HasEstimatedPower),
		AverageHeartRateBpm:     nullFloat(averages.HeartRateBPM, averages.HasHeartRate),
		MaxHeartRateBpm:         nullFloat(averages.MaxHeartRateBPM, averages.HasHeartRate),
		AverageCadenceRpm:       nullFloat(averages.CadenceRPM, averages.HasCadence),
		AveragePowerWatts:       nullFloat(averages.PowerWatts, averages.HasPower),
		InputMaxHeartRate:       metrics.Inputs.MaxHeartRateBPM,
		InputRestingHeartRate:   metrics.Inputs.RestingHeartRateBPM,
		InputThresholdHeartRate: metrics.Inputs.ThresholdHeartRateBPM,
		InputThresholdPower:     metrics.Inputs.FunctionalThresholdPowerWatts,
		InputTotalMass:          metrics.Inputs.TotalMassKG,
		DerivationVersion:       derivationVersion,
		ComputedAtUnix:          time.Now().Unix(),
	}); err != nil {
		return fmt.Errorf("storing the activity metrics: %w", err)
	}

	return nil
}

// ActivityMetrics reads every derived row one target holds, keyed by ride.
func (s *Store) ActivityMetrics(ctx context.Context, targetID string) (map[int64]activity.RideMetrics, error) {
	rows, err := s.queries.ListActivityMetrics(ctx, targetID)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("reading the activity metrics: %w", err)
	}
	metrics := make(map[int64]activity.RideMetrics, len(rows))
	for index := range rows {
		row := &rows[index]
		one := trainingload.Metrics{
			HasZones:            row.Zone1Seconds.Valid,
			TRIMP:               row.Trimp.Float64,
			HasTRIMP:            row.Trimp.Valid,
			HeartRateTSS:        row.HeartRateTss.Float64,
			HasHeartRateTSS:     row.HeartRateTss.Valid,
			HasPower:            row.NormalizedPowerWatts.Valid,
			EstimatedPowerWatts: row.EstimatedPowerWatts.Float64,
			HasEstimatedPower:   row.EstimatedPowerWatts.Valid,
			Power: trainingload.Power{
				NormalizedWatts: row.NormalizedPowerWatts.Float64,
				IntensityFactor: row.IntensityFactor.Float64,
				TSS:             row.PowerTss.Float64,
			},
		}
		one.Zones = trainingload.Zones{
			row.Zone1Seconds.Float64, row.Zone2Seconds.Float64, row.Zone3Seconds.Float64,
			row.Zone4Seconds.Float64, row.Zone5Seconds.Float64,
		}
		metrics[row.WorkoutID] = activity.RideMetrics{Load: one, Averages: activity.RideAverages{
			HeartRateBPM:    row.AverageHeartRateBpm.Float64,
			MaxHeartRateBPM: row.MaxHeartRateBpm.Float64,
			CadenceRPM:      row.AverageCadenceRpm.Float64,
			PowerWatts:      row.AveragePowerWatts.Float64,
			HasHeartRate:    row.AverageHeartRateBpm.Valid,
			HasCadence:      row.AverageCadenceRpm.Valid,
			HasPower:        row.AveragePowerWatts.Valid,
		}}
	}

	return metrics, nil
}

// TargetOwner is the subject whose target this is, empty for a slot that
// predates ownership. A slot this deployment does not have is not an error:
// a target can go while work about it is still queued.
func (s *Store) TargetOwner(ctx context.Context, targetID string) (string, error) {
	subject, err := s.queries.GetTargetOwner(ctx, targetID)
	if errors.Is(err, sql.ErrNoRows) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("reading the target owner: %w", err)
	}

	return subject, nil
}

// ClearActivityMetrics removes every derived row one target holds and reports
// how many went. It is what a rider clearing their whole profile leaves behind:
// numbers worked out from parameters nobody holds any more must not go on being
// served.
func (s *Store) ClearActivityMetrics(ctx context.Context, targetID string) (int, error) {
	removed, err := s.queries.ClearActivityMetrics(ctx, targetID)
	if err != nil {
		return 0, fmt.Errorf("clearing the activity metrics: %w", err)
	}

	return int(removed), nil
}

// ActivityRideLoads is every derived ride of one target, with the moment it was
// ridden, oldest first. It is the whole of what the fitness timeline folds: one
// row per ride rather than per hour or per sample, so a rider's whole history
// is a few hundred rows.
func (s *Store) ActivityRideLoads(ctx context.Context, targetID string) ([]trainingload.RideLoad, error) {
	rows, err := s.queries.ListActivityRideLoads(ctx, targetID)
	if err != nil {
		return nil, fmt.Errorf("reading the activity ride loads: %w", err)
	}
	loads := make([]trainingload.RideLoad, 0, len(rows))
	for index := range rows {
		row := &rows[index]
		metrics := trainingload.Metrics{
			TRIMP: row.Trimp.Float64, HasTRIMP: row.Trimp.Valid,
			HeartRateTSS: row.HeartRateTss.Float64, HasHeartRateTSS: row.HeartRateTss.Valid,
			Power:    trainingload.Power{TSS: row.PowerTss.Float64},
			HasPower: row.PowerTss.Valid,
			Zones: trainingload.Zones{
				row.Zone1Seconds.Float64, row.Zone2Seconds.Float64, row.Zone3Seconds.Float64,
				row.Zone4Seconds.Float64, row.Zone5Seconds.Float64,
			},
		}
		loads = append(loads, trainingload.LoadOf(time.Unix(row.StartedAtUnix, 0).UTC(), &metrics))
	}

	return loads, nil
}
